#
# SPDX-License-Identifier:	GPL-2.0+
#
#a18
obj-$(CONFIG_SOC_SFA18_MPW0)		+= sfa18_mpw0/
obj-$(CONFIG_SOC_SFA18_MPW1)		+= sfa18_mpw1/
obj-$(CONFIG_SOC_SFA18_FULLMASK)	+= sfa18_fullmask/
#a28
obj-$(CONFIG_SOC_SFA28_MPW0)		+= sfa28_mpw0/
obj-$(CONFIG_SOC_SFA28_FULLMASK)	+= sfa28_fullmask/
#pcba
obj-$(CONFIG_SFA18_PCBA_TEST)		+= pcba-test/
