/*
 * =====================================================================================
 *
 *       Filename:  wifi_ldfw.h
 *
 *    Description:
 *
 *        Version:  1.0
 *        Created:  08/07/2016 10:55:45 AM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  franklin (), franklin.wang@siflower.com.cn
 *        Company:  Siflower Communication Tenology Co.,Ltd
 *
 * =====================================================================================
 */

#ifndef _WIFI_LDFW_H_
#define _WIFI_LDFW_H_


/**
 ****************************************************************************************
 * @brief This function to load the agc ram bin to agc memory
 * @note once the agc firmware changed ,the agc_ram_bin.h file should be updated
 *       the tester must call this file before doing any other things
 ****************************************************************************************
 */
void load_agc_ram_bin(void);


/**
 ****************************************************************************************
 *  @brief This function to load the rf digital micro code to the program memory
 *  TODO: now this function is not implemented
 ****************************************************************************************
 */
void load_rf_pmem_bin(void);

/**
 ****************************************************************************************
 *  @brief return 1 inidicate that RF has been boot finished, BB can use all the region under the clock generated by rf
 ****************************************************************************************
 */
#ifdef WITH_CATRF
char is_rf_boot_finished(void);
#endif
#endif
