#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh

uci set network.wan.connect='0'
uci commit network
proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

echo "$(date) INFO ppp down" >> /tmp/sf_log.txt
