#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += pcba_test.o cmd.o aligned_malloc.o pcba_net.o
obj-y += i2c/
obj-$(CONFIG_SFAX8_GPIO_TEST) += gpio_test.o
obj-$(CONFIG_SFAX8_BUTTON_TEST) += button_test.o
obj-$(CONFIG_SFAX8_WIFI_TEST) += wifi/
obj-$(CONFIG_SFAX8_AUDIO_TEST) += audio/
obj-$(CONFIG_SFAX8_PMU_TEST) += pmu/
obj-$(CONFIG_SFAX8_NPU_TEST) += eth_test.o
obj-$(CONFIG_SFAX8_GMAC_TEST) += gmac_test.o
obj-$(CONFIG_SFAX8_GDU_TEST) += gdu/
obj-$(CONFIG_SFAX8_SD_TEST) += sd_test.o
obj-$(CONFIG_SFAX8_USB_TEST) += usb_test.o
obj-$(CONFIG_SFAX8_SHARE_MEM_TEST) += share_memory_test.o
