#
# Makefile for http stuff
#
obj-y += uip.o
obj-y += uip_arch.o
obj-y += uip_arp.o
obj-y += httpd.o
obj-y += fs.o
CFLAGS_uip.o  +=  -fno-strict-aliasing
CFLAGS_uip_arch.o  +=  -fno-strict-aliasing
CFLAGS_uip_arp.o  +=  -fno-strict-aliasing
