/**  @file
  *  @brief    brief  description
  *  @author   
  *  @date     2020.5.7
  *  @version  1.0
  *  @note
  *  detailed  description
  *  $LastChangedDate$
  *  $LastChangedRevision$
  *  $LastChangedBy$
  */

#ifndef _L2SW_ASICDRV_H_
#define _L2SW_ASICDRV_H_

#include "l2sw_types.h"
#include "l2sw_error.h"
#include "l2sw_base.h"

#define L2SW_REGBITLENGTH               16
#define L2SW_REGDATAMAX                 0xFFFF

#define L2SW_VIDMAX                     0xFFF
#define L2SW_EVIDMAX                    0x1FFF
#define L2SW_CVIDXNO                    32
#define L2SW_CVIDXMAX                   (L2SW_CVIDXNO-1)

#define L2SW_PRIMAX                     7
#define L2SW_DSCPMAX                    63

#define L2SW_PORTNO                     11
#define L2SW_PORTIDMAX                  (L2SW_PORTNO-1)
#define L2SW_PMSKMAX                    ((1<<(L2SW_PORTNO))-1)
#define L2SW_PORTMASK                   0x7FF

#define L2SW_PHYNO                      5
#define L2SW_PHYIDMAX                  (L2SW_PHYNO-1)

#define L2SW_SVIDXNO                    64
#define L2SW_SVIDXMAX                   (L2SW_SVIDXNO-1)
#define L2SW_MSTIMAX                    15

#define L2SW_METERNO                    64
#define L2SW_METERMAX                   (L2SW_METERNO-1)
#define L2SW_METERBUCKETSIZEMAX         0x1FFFFF

#define L2SW_QUEUENO                    8
#define L2SW_QIDMAX                     (L2SW_QUEUENO-1)

#define L2SW_PHY_BUSY_CHECK_COUNTER     1000

#define L2SW_QOS_GRANULARTY_MAX         0x7FFFF
#define L2SW_QOS_GRANULARTY_LSB_MASK    0xFFFF
#define L2SW_QOS_GRANULARTY_LSB_OFFSET  0
#define L2SW_QOS_GRANULARTY_MSB_MASK    0x70000
#define L2SW_QOS_GRANULARTY_MSB_OFFSET  16

#define L2SW_QOS_GRANULARTY_UNIT_KBPS   8

#define L2SW_QOS_RATE_INPUT_MAX         (0x1FFFF * 8)
#define L2SW_QOS_RATE_INPUT_MAX_HSG     (0x7FFFF * 8)
#define L2SW_QOS_RATE_INPUT_MIN         8
#define L2SW_QOS_PPS_INPUT_MAX          (0x1FFFFF)//(0x7FFFF)
#define L2SW_QOS_PPS_INPUT_MIN          1

#define L2SW_QUEUE_MASK                 0xFF

#define L2SW_EFIDMAX                    0x7
#define L2SW_FIDMAX                     0xF

#define L2SW_EAV_SECONDMAX                  0xFFFFFFFF
#define L2SW_EAV_NANOSECONDMAX          0x3B9AC9FF


/* the above macro is generated by genDotH */
#define L2SW_VALID_REG_NO               3869

/*=======================================================================
 *  Enum
 *========================================================================*/
enum L2SW_TABLE_ACCESS_OP
{
    TB_OP_READ = 0,
    TB_OP_WRITE
};

enum L2SW_TABLE_ACCESS_TARGET
{
    TB_TARGET_ACLRULE = 1,
    TB_TARGET_ACLACT,
    TB_TARGET_CVLAN,
    TB_TARGET_L2,
    TB_TARGET_IGMP_GROUP
};

#define L2SW_TABLE_ACCESS_REG_DATA(op, target)    ((op << 3) | target)

/*=======================================================================
 *  Structures
 *========================================================================*/


#ifdef __cplusplus
extern "C" {
#endif
extern ret_t l2sw_setAsicRegBit(l2sw_uint8 units, l2sw_uint32 reg, l2sw_uint32 bit, l2sw_uint32 value);
extern ret_t l2sw_getAsicRegBit(l2sw_uint8 units, l2sw_uint32 reg, l2sw_uint32 bit, l2sw_uint32 *pValue);

extern ret_t l2sw_setAsicRegBits(l2sw_uint8 units, l2sw_uint32 reg, l2sw_uint32 bits, l2sw_uint32 value);
extern ret_t l2sw_getAsicRegBits(l2sw_uint8 units, l2sw_uint32 reg, l2sw_uint32 bits, l2sw_uint32 *pValue);

extern ret_t l2sw_setAsicReg(l2sw_uint8 units, l2sw_uint32 reg, l2sw_uint32 value);
extern ret_t l2sw_getAsicReg(l2sw_uint8 units, l2sw_uint32 reg, l2sw_uint32 *pValue);

#ifdef __cplusplus
}
#endif


int sf_l2sw_getAsicReg(unsigned int reg, unsigned int *pValue);
int sf_l2sw_setAsicReg(unsigned int reg, unsigned int pValue);

#endif /*#ifndef _L2SW_ASICDRV_H_*/

