# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MTD_NAND_SPI) += spinand.o

spinand-objs := bbt.o nand_core.o spi_nand_core.o macronix.o micron.o winbond.o fudanmicro.o icmax.o esmt.o toshiba.o gigadevice.o
