#
# Copyright (C) 2016 Siflower Technology Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SFAX8_DDR3) += ddr3_timing.o ddr.o
obj-$(CONFIG_SFAX8_DDR2) += ddr2_timing.o ddr.o

ddr-y = ddr_init.o ddr_common.o
