/*This file is auto generated by Python script. 2022-08-09 09:54:23.*/



#include "hal_mem.h"
#include "fal_tiger_struct.h"



const field_id_t global_ctrl0m_field[] = { 
    {GLOBAL_CTRL0_CHIP_SW_RSTf,1,0,1},
};

const field_id_t global_ctrl1m_field[] = { 
    {GLOBAL_CTRL1_METER_ENf,1,0,4},
    {GLOBAL_CTRL1_AC_ENf,1,0,3},
    {GLOBAL_CTRL1_ACL_ENf,1,0,2},
    {GLOBAL_CTRL1_MIB_ENf,1,0,1},
    {GLOBAL_CTRL1_INTERRUP_POLARITYf,1,0,0},
};

const field_id_t ext_cpu_port_ctrlm_field[] = { 
    {EXT_CPU_PORT_CTRL_EXT_CPU_TAG_ENf,1,0,15},
    {EXT_CPU_PORT_CTRL_EXT_CPU_PORT_ENf,1,0,14},
    {EXT_CPU_PORT_CTRL_EXT_CPU_PORT_NUMf,4,0,0},
};

const field_id_t cpu_tag_tpidm_field[] = { 
    {CPU_TAG_TPID_TPIDf,16,0,0},
};

const field_id_t look_up_vlan_selm_field[] = { 
    {LOOK_UP_VLAN_SEL_LOOK_UP_VLAN_SELf,11,0,0},
};

const field_id_t intr_maskm_field[] = { 
    {INTR_MASK_OVER_TEMP_INRPT_STATUSf,1,0,28},
    {INTR_MASK_MDIO_TRANS_DONE_INTf,1,0,27},
    {INTR_MASK_ACL_HITf,1,0,26},
    {INTR_MASK_DYING_GASP_INT_Pf,1,0,25},
    {INTR_MASK_PKT_WOL_MAGIC_INT_Pf,1,0,24},
    {INTR_MASK_QM_FLUSH_DONE_Pf,1,0,23},
    {INTR_MASK_HW_INI_DONEf,1,0,22},
    {INTR_MASK_IGMP_LEARN_FULLf,1,0,21},
    {INTR_MASK_IGMP_DELETEf,1,0,20},
    {INTR_MASK_FDB_LEARN_CREATEf,1,0,19},
    {INTR_MASK_FDB_LEARN_MOVEf,1,0,18},
    {INTR_MASK_FDB_DELETEf,1,0,17},
    {INTR_MASK_FDB_LEARN_FULLf,1,0,16},
    {INTR_MASK_CPU_OP_DONEf,1,0,15},
    {INTR_MASK_ACL_ACTf,1,0,14},
    {INTR_MASK_BRIDGE_CONGESTIONf,1,0,13},
    {INTR_MASK_LOOP_DETECTf,1,0,12},
    {INTR_MASK_EEPROM_LOAD_DONEf,1,0,11},
    {INTR_MASK_SG_INT1f,1,0,10},
    {INTR_MASK_SG_INT0f,1,0,9},
    {INTR_MASK_PHY_INT7f,1,0,8},
    {INTR_MASK_PHY_INT6f,1,0,7},
    {INTR_MASK_PHY_INT5f,1,0,6},
    {INTR_MASK_PHY_INT4f,1,0,5},
    {INTR_MASK_PHY_INT3f,1,0,4},
    {INTR_MASK_PHY_INT2f,1,0,3},
    {INTR_MASK_PHY_INT1f,1,0,2},
    {INTR_MASK_PHY_INT0f,1,0,1},
    {INTR_MASK_HW_EXCEPTIONf,1,0,0},
};

const field_id_t intr_statusm_field[] = { 
};

const field_id_t global_mac_addr0m_field[] = { 
    {GLOBAL_MAC_ADDR0_MAC_ADDR_BYTE4f,8,0,8},
    {GLOBAL_MAC_ADDR0_MAC_ADDR_BYTE5f,8,0,0},
};

const field_id_t global_mac_addr1m_field[] = { 
    {GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE0f,8,0,24},
    {GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE1f,8,0,16},
    {GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE2f,8,0,8},
    {GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE3f,8,0,0},
};

const field_id_t eee_ctrlm_field[] = { 
};

const field_id_t sg_phym_field[] = { 
    {SG_PHY_APPLICATION_MODEf,3,0,7},
    {SG_PHY_PAUSEf,2,0,5},
    {SG_PHY_LINKf,1,0,4},
    {SG_PHY_DUPLEX_MODEf,1,0,3},
    {SG_PHY_SPEED_MODEf,3,0,0},
};

const field_id_t port_ctrlm_field[] = { 
    {PORT_CTRL_FLOW_LINK_ANf,1,0,10},
    {PORT_CTRL_AN_LINK_ENf,1,0,9},
    {PORT_CTRL_HALF_FC_ENf,1,0,8},
    {PORT_CTRL_DUPLEX_MODEf,1,0,7},
    {PORT_CTRL_RX_FC_ENf,1,0,6},
    {PORT_CTRL_TX_FC_ENf,1,0,5},
    {PORT_CTRL_RXMAC_ENf,1,0,4},
    {PORT_CTRL_TXMAC_ENf,1,0,3},
    {PORT_CTRL_SPEED_MODEf,3,0,0},
};

const field_id_t port_statusm_field[] = { 
    {PORT_STATUS_LINKf,1,0,8},
    {PORT_STATUS_DUPLEX_MODEf,1,0,7},
    {PORT_STATUS_RX_FC_ENf,1,0,6},
    {PORT_STATUS_TX_FC_ENf,1,0,5},
    {PORT_STATUS_RXMAC_ENf,1,0,4},
    {PORT_STATUS_TXMAC_ENf,1,0,3},
    {PORT_STATUS_SPEED_MODEf,3,0,0},
};

const field_id_t loop_detect_top_ctrlm_field[] = { 
    {LOOP_DETECT_TOP_CTRL_BUZZER_MODEf,2,0,26},
    {LOOP_DETECT_TOP_CTRL_BUZZER_ENf,1,0,25},
    {LOOP_DETECT_TOP_CTRL_UNIT_ID_REMOTE1f,2,0,23},
    {LOOP_DETECT_TOP_CTRL_UNIT_ID_REMOTE0f,2,0,21},
    {LOOP_DETECT_TOP_CTRL_UNIT_ID_LOCALf,2,0,19},
    {LOOP_DETECT_TOP_CTRL_ENf,1,0,18},
    {LOOP_DETECT_TOP_CTRL_LOOP_DETECT_TPIDf,16,0,2},
    {LOOP_DETECT_TOP_CTRL_GENERATE_MODEf,1,0,1},
    {LOOP_DETECT_TOP_CTRL_GENERATE_WAYf,1,0,0},
};

const field_id_t pon_strap_enm_field[] = { 
};

const field_id_t pon_strap_valm_field[] = { 
};

const field_id_t pon_strapm_field[] = { 
};

const field_id_t mdio_pollingm_field[] = { 
    {MDIO_POLLING_DUPLEXf,1,0,4},
    {MDIO_POLLING_LINKf,1,0,3},
    {MDIO_POLLING_SPEEDf,3,0,0},
};

const field_id_t oam_dying_gaspm_field[] = { 
};

const field_id_t acl2gpiom_field[] = { 
};

const field_id_t extif0_modem_field[] = { 
    {EXTIF0_MODE_XMII_MODEf,3,0,29},
    {EXTIF0_MODE_RGMII_DELAY_TYPE_SELf,1,0,28},
    {EXTIF0_MODE_EN_MACMODE_LNKDN_SWHf,1,0,26},
    {EXTIF0_MODE_RGMII_TXC_DLY100_10_ENf,1,0,20},
    {EXTIF0_MODE_XMII_LINK_UPf,1,0,19},
    {EXTIF0_MODE_XMII_PORT_ENf,1,0,18},
    {EXTIF0_MODE_XMII_SOFT_RSTf,1,0,17},
    {EXTIF0_MODE_RGMII_TXC_DELAY_SELf,4,0,13},
    {EXTIF0_MODE_REMII_RX_XMII_SELf,1,0,12},
    {EXTIF0_MODE_XMII_TXC_IN_SELf,1,0,11},
    {EXTIF0_MODE_XMII_RXC_IN_SELf,1,0,10},
    {EXTIF0_MODE_REVERT_TXDf,1,0,9},
    {EXTIF0_MODE_RGMII_TXC_DELAY_ENf,1,0,8},
    {EXTIF0_MODE_RGMII_TXC_OUT_SELf,1,0,7},
    {EXTIF0_MODE_RGMII_RXC_DELAY_SELf,4,0,3},
    {EXTIF0_MODE_RMII_PHY_TXC_OUT_SELf,1,0,2},
    {EXTIF0_MODE_REMII_TXC_OUT_SELf,1,0,1},
    {EXTIF0_MODE_REMII_RXC_OUT_SELf,1,0,0},
};

const field_id_t extif0_mode2m_field[] = { 
};

const field_id_t extif1_modem_field[] = { 
    {EXTIF1_MODE_XMII_MODEf,3,0,29},
    {EXTIF1_MODE_RGMII_DELAY_TYPE_SELf,1,0,28},
    {EXTIF1_MODE_EN_MACMODE_LNKDN_SWHf,1,0,26},
    {EXTIF1_MODE_RGMII_TXC_DLY100_10_ENf,1,0,20},
    {EXTIF1_MODE_XMII_LINK_UPf,1,0,19},
    {EXTIF1_MODE_XMII_PORT_ENf,1,0,18},
    {EXTIF1_MODE_XMII_SOFT_RSTf,1,0,17},
    {EXTIF1_MODE_RGMII_TXC_DELAY_SELf,4,0,13},
    {EXTIF1_MODE_REMII_RX_XMII_SELf,1,0,12},
    {EXTIF1_MODE_XMII_TXC_IN_SELf,1,0,11},
    {EXTIF1_MODE_XMII_RXC_IN_SELf,1,0,10},
    {EXTIF1_MODE_REVERT_TXDf,1,0,9},
    {EXTIF1_MODE_RGMII_TXC_DELAY_ENf,1,0,8},
    {EXTIF1_MODE_RGMII_TXC_OUT_SELf,1,0,7},
    {EXTIF1_MODE_RGMII_RXC_DELAY_SELf,4,0,3},
    {EXTIF1_MODE_RMII_PHY_TXC_OUT_SELf,1,0,2},
    {EXTIF1_MODE_REMII_TXC_OUT_SELf,1,0,1},
    {EXTIF1_MODE_REMII_RXC_OUT_SELf,1,0,0},
};

const field_id_t extif1_mode2m_field[] = { 
};

const field_id_t tpid_profile0m_field[] = { 
    {TPID_PROFILE0_TPIDf,16,0,0},
};

const field_id_t tpid_profile1m_field[] = { 
    {TPID_PROFILE1_TPIDf,16,0,0},
};

const field_id_t parser_port_ctrlnm_field[] = { 
    {PARSER_PORT_CTRLN_STAG_TPID_MASKf,4,0,4},
    {PARSER_PORT_CTRLN_CTAG_TPID_MASKf,4,0,0},
};

const field_id_t link_agg_hash_ctrlm_field[] = { 
    {LINK_AGG_HASH_CTRL_HASH_FIELD_SELf,8,0,0},
};

const field_id_t udf_ctrlnm_field[] = { 
    {UDF_CTRLN_UDF_TYPEf,2,0,7},
    {UDF_CTRLN_UDF_OFFSETf,7,0,0},
};

const field_id_t parser_erp_ouim_field[] = { 
};

const field_id_t parser_erp_ethtypem_field[] = { 
};

const field_id_t parser_erp_udf_ctrlm_field[] = { 
};

const field_id_t parser_erp_udfnm_field[] = { 
};

const field_id_t dos_tcp_flags0m_field[] = { 
    {DOS_TCP_FLAGS0_COPY_TO_CPUf,1,0,16},
    {DOS_TCP_FLAGS0_TCP_FLAGS_MASKf,6,0,10},
    {DOS_TCP_FLAGS0_SEQ_NUM0_MASKf,1,0,9},
    {DOS_TCP_FLAGS0_PUBLIC_TCP_SPORT_MASKf,1,0,8},
    {DOS_TCP_FLAGS0_TCP_FLAGSf,6,0,2},
    {DOS_TCP_FLAGS0_SEQ_NUM0f,1,0,1},
    {DOS_TCP_FLAGS0_PUBLIC_TCP_SPORTf,1,0,0},
};

const field_id_t dos_tcp_flags1m_field[] = { 
};

const field_id_t dos_tcp_flags2m_field[] = { 
};

const field_id_t dos_tcp_flags3m_field[] = { 
};

const field_id_t dos_tcp_flags4m_field[] = { 
};

const field_id_t dos_tcp_flags5m_field[] = { 
};

const field_id_t dos_ctrlm_field[] = { 
    {DOS_CTRL_VLAN_CFI1DROP_ENf,1,0,29},
    {DOS_CTRL_PORT_EN_MASKf,11,0,18},
    {DOS_CTRL_TCP_HEADER_PARTIAL_COPY_TO_CPUf,1,0,17},
    {DOS_CTRL_LARGE_IPV6_ICMP_COPY_TO_CPUf,1,0,16},
    {DOS_CTRL_LARGE_IPV4_ICMP_COPY_TO_CPUf,1,0,15},
    {DOS_CTRL_TCP_FRAG_OFFSET1_COPY_TO_CPUf,1,0,14},
    {DOS_CTRL_TCP_SPORT_EQ_DPORT_COPY_TO_CPUf,1,0,13},
    {DOS_CTRL_UDP_SPORT_EQ_DPORT_COPY_TO_CPUf,1,0,12},
    {DOS_CTRL_ICMP_PRAG_COPY_TO_CPUf,1,0,11},
    {DOS_CTRL_SIP_EQ_DIP_COPY_TO_CPUf,1,0,10},
    {DOS_CTRL_MACSA_EQ_MACDA_COPY_TO_CPUf,1,0,9},
    {DOS_CTRL_TCP_HEADER_PARTIAL_DROPf,1,0,8},
    {DOS_CTRL_LARGE_IPV6_ICMP_DROPf,1,0,7},
    {DOS_CTRL_LARGE_IPV4_ICMP_DROPf,1,0,6},
    {DOS_CTRL_TCP_FRAG_OFFSET1_DROPf,1,0,5},
    {DOS_CTRL_TCP_SPORT_EQ_DPORT_DROPf,1,0,4},
    {DOS_CTRL_UDP_SPORT_EQ_DPORT_DROPf,1,0,3},
    {DOS_CTRL_ICMP_PRAG_DROPf,1,0,2},
    {DOS_CTRL_SIP_EQ_DIP_DROPf,1,0,1},
    {DOS_CTRL_MACSA_EQ_MACDA_DROPf,1,0,0},
};

const field_id_t dos_large_icmp_ctrlm_field[] = { 
    {DOS_LARGE_ICMP_CTRL_IPV6_ICMP_MAX_SIZEf,13,0,16},
    {DOS_LARGE_ICMP_CTRL_IPV4_ICMP_MAX_SIZEf,13,0,0},
};

const field_id_t oam_en_ctrlm_field[] = { 
    {OAM_EN_CTRL_ENf,11,0,0},
};

const field_id_t wol_ctrlm_field[] = { 
    {WOL_CTRL_WOL_ETH_TYPEf,16,0,1},
    {WOL_CTRL_WOL_ENf,1,0,0},
};

const field_id_t dos_ctrl1m_field[] = { 
    {DOS_CTRL1_DA_ZERO_DROP_ENf,1,0,3},
    {DOS_CTRL1_SA_ZERO_DROP_ENf,1,0,2},
    {DOS_CTRL1_SA_BC_DROP_ENf,1,0,1},
    {DOS_CTRL1_SA_MC_DROP_ENf,1,0,0},
};

const field_id_t protocol_based_vlannm_field[] = { 
};

const field_id_t port_vlan_ctrlnm_field[] = { 
    {PORT_VLAN_CTRLN_PRIORITY_TAG_SVID_ENf,1,0,31},
    {PORT_VLAN_CTRLN_PRIORITY_TAG_CVID_ENf,1,0,30},
    {PORT_VLAN_CTRLN_DEFAULT_SVIDf,12,0,18},
    {PORT_VLAN_CTRLN_DEFAULT_CVIDf,12,0,6},
    {PORT_VLAN_CTRLN_DEFAULT_SPRIOf,3,0,3},
    {PORT_VLAN_CTRLN_DEFAULT_CPRIOf,3,0,0},
};

const field_id_t port_vlan_ctrl1nm_field[] = { 
    {PORT_VLAN_CTRL1N_VLAN_RANGE_MODEf,1,0,8},
    {PORT_VLAN_CTRL1N_VLAN_RANGE_PROFILE_IDf,4,0,4},
    {PORT_VLAN_CTRL1N_STAG_AFTf,2,0,2},
    {PORT_VLAN_CTRL1N_CTAG_AFTf,2,0,0},
};

const field_id_t vlan_trans_untag_vid_mode_ctrlm_field[] = { 
    {VLAN_TRANS_UNTAG_VID_MODE_CTRL_MODEf,22,0,0},
};

const field_id_t vlan_range_profilenm_field[] = { 
    {VLAN_RANGE_PROFILEN_MAX_VID3f,12,2,20},
    {VLAN_RANGE_PROFILEN_MIN_VID3f,12,2,8},
    {VLAN_RANGE_PROFILEN_MAX_VID2_1f,8,2,0},
    {VLAN_RANGE_PROFILEN_MAX_VID2_0f,4,1,28},
    {VLAN_RANGE_PROFILEN_MIN_VID2f,12,1,16},
    {VLAN_RANGE_PROFILEN_MAX_VID1f,12,1,4},
    {VLAN_RANGE_PROFILEN_MIN_VID1_1f,4,1,0},
    {VLAN_RANGE_PROFILEN_MIN_VID1_0f,8,0,24},
    {VLAN_RANGE_PROFILEN_MAX_VID0f,12,0,12},
    {VLAN_RANGE_PROFILEN_MIN_VID0f,12,0,0},
};

const field_id_t protocol_based_vlan_data_tblm_field[] = { 
};

const field_id_t vlan_xlate_action_tblm_field[] = { 
    {VLAN_XLATE_ACTION_TBL_SVID_CMDf,2,1,6},
    {VLAN_XLATE_ACTION_TBL_NEW_SVID_1f,6,1,0},
    {VLAN_XLATE_ACTION_TBL_NEW_SVID_0f,6,0,26},
    {VLAN_XLATE_ACTION_TBL_CVID_CMDf,2,0,24},
    {VLAN_XLATE_ACTION_TBL_NEW_CVIDf,12,0,12},
    {VLAN_XLATE_ACTION_TBL_SPRIO_CMDf,2,0,10},
    {VLAN_XLATE_ACTION_TBL_NEW_SPRIOf,3,0,7},
    {VLAN_XLATE_ACTION_TBL_NEW_SDEIf,1,0,6},
    {VLAN_XLATE_ACTION_TBL_CPRIO_CMDf,2,0,4},
    {VLAN_XLATE_ACTION_TBL_NEW_CPRIOf,3,0,1},
    {VLAN_XLATE_ACTION_TBL_NEW_CDEIf,1,0,0},
};

const field_id_t vlan_xlate_tblm_field[] = { 
    {VLAN_XLATE_TBL_VALIDf,1,1,11},
    {VLAN_XLATE_TBL_SVID_1f,11,1,0},
    {VLAN_XLATE_TBL_SVID_0f,1,0,31},
    {VLAN_XLATE_TBL_SVID_INCLf,1,0,30},
    {VLAN_XLATE_TBL_STAG_FMTf,2,0,28},
    {VLAN_XLATE_TBL_STAG_FMT_INCLf,1,0,27},
    {VLAN_XLATE_TBL_CVIDf,12,0,15},
    {VLAN_XLATE_TBL_CVID_INCLf,1,0,14},
    {VLAN_XLATE_TBL_CTAG_FMTf,2,0,12},
    {VLAN_XLATE_TBL_CTAG_FMT_INCLf,1,0,11},
    {VLAN_XLATE_TBL_SRC_PORT_MASKf,11,0,0},
};

const field_id_t acl_blk_keep_ctrlm_field[] = { 
    {ACL_BLK_KEEP_CTRL_GRPID7f,3,0,29},
    {ACL_BLK_KEEP_CTRL_KEEP7f,1,0,28},
    {ACL_BLK_KEEP_CTRL_GRPID6f,3,0,25},
    {ACL_BLK_KEEP_CTRL_KEEP6f,1,0,24},
    {ACL_BLK_KEEP_CTRL_GRPID5f,3,0,21},
    {ACL_BLK_KEEP_CTRL_KEEP5f,1,0,20},
    {ACL_BLK_KEEP_CTRL_GRPID4f,3,0,17},
    {ACL_BLK_KEEP_CTRL_KEEP4f,1,0,16},
    {ACL_BLK_KEEP_CTRL_GRPID3f,3,0,13},
    {ACL_BLK_KEEP_CTRL_KEEP3f,1,0,12},
    {ACL_BLK_KEEP_CTRL_GRPID2f,3,0,9},
    {ACL_BLK_KEEP_CTRL_KEEP2f,1,0,8},
    {ACL_BLK_KEEP_CTRL_GRPID1f,3,0,5},
    {ACL_BLK_KEEP_CTRL_KEEP1f,1,0,4},
    {ACL_BLK_KEEP_CTRL_GRPID0f,3,0,1},
    {ACL_BLK_KEEP_CTRL_KEEP0f,1,0,0},
};

const field_id_t acl_port_ctrlm_field[] = { 
    {ACL_PORT_CTRL_ENABLEf,11,0,0},
};

const field_id_t acl_blk_cmdm_field[] = { 
    {ACL_BLK_CMD_BLKIDf,6,0,1},
    {ACL_BLK_CMD_CMDf,1,0,0},
};

const field_id_t rule_ext_ctrlm_field[] = { 
    {RULE_EXT_CTRL_GRPID7f,3,0,29},
    {RULE_EXT_CTRL_VALID7f,1,0,28},
    {RULE_EXT_CTRL_GRPID6f,3,0,25},
    {RULE_EXT_CTRL_VALID6f,1,0,24},
    {RULE_EXT_CTRL_GRPID5f,3,0,21},
    {RULE_EXT_CTRL_VALID5f,1,0,20},
    {RULE_EXT_CTRL_GRPID4f,3,0,17},
    {RULE_EXT_CTRL_VALID4f,1,0,16},
    {RULE_EXT_CTRL_GRPID3f,3,0,13},
    {RULE_EXT_CTRL_VALID3f,1,0,12},
    {RULE_EXT_CTRL_GRPID2f,3,0,9},
    {RULE_EXT_CTRL_VALID2f,1,0,8},
    {RULE_EXT_CTRL_GRPID1f,3,0,5},
    {RULE_EXT_CTRL_VALID1f,1,0,4},
    {RULE_EXT_CTRL_GRPID0f,3,0,1},
    {RULE_EXT_CTRL_VALID0f,1,0,0},
};

const field_id_t acl_rule_bin0m_field[] = { 
};

const field_id_t acl_rule_bin1m_field[] = { 
};

const field_id_t acl_rule_bin2m_field[] = { 
};

const field_id_t acl_rule_bin3m_field[] = { 
};

const field_id_t acl_rule_bin4m_field[] = { 
};

const field_id_t acl_rule_bin5m_field[] = { 
};

const field_id_t acl_rule_bin6m_field[] = { 
};

const field_id_t acl_rule_bin7m_field[] = { 
};

const field_id_t acl_rule_mask_bin0m_field[] = { 
};

const field_id_t acl_rule_mask_bin1m_field[] = { 
};

const field_id_t acl_rule_mask_bin2m_field[] = { 
};

const field_id_t acl_rule_mask_bin3m_field[] = { 
};

const field_id_t acl_rule_mask_bin4m_field[] = { 
};

const field_id_t acl_rule_mask_bin5m_field[] = { 
};

const field_id_t acl_rule_mask_bin6m_field[] = { 
};

const field_id_t acl_rule_mask_bin7m_field[] = { 
};

const field_id_t mac_da0_rulem_field[] = { 
    {MAC_DA0_RULE_PRIOf,9,1,21},
    {MAC_DA0_RULE_SRC_PORT_MASKf,11,1,10},
    {MAC_DA0_RULE_LOGIC_NOTf,1,1,9},
    {MAC_DA0_RULE_RULE_TYPEf,5,1,4},
    {MAC_DA0_RULE_L3_TYPEf,4,1,0},
    {MAC_DA0_RULE_MAC_DA0f,32,0,0},
};

const field_id_t mac_da0_rule_maskm_field[] = { 
    {MAC_DA0_RULE_MASK_L3_TYPEf,4,1,0},
    {MAC_DA0_RULE_MASK_MAC_DA0f,32,0,0},
};

const field_id_t mac_da1_sa1_rulem_field[] = { 
    {MAC_DA1_SA1_RULE_PRIOf,9,1,21},
    {MAC_DA1_SA1_RULE_SRC_PORT_MASKf,11,1,10},
    {MAC_DA1_SA1_RULE_LOGIC_NOTf,1,1,9},
    {MAC_DA1_SA1_RULE_RULE_TYPEf,5,1,4},
    {MAC_DA1_SA1_RULE_RSVDf,1,1,3},
    {MAC_DA1_SA1_RULE_L2_TYPEf,3,1,0},
    {MAC_DA1_SA1_RULE_MAC_DA1f,16,0,16},
    {MAC_DA1_SA1_RULE_MAC_SA1f,16,0,0},
};

const field_id_t mac_da1_sa1_rule_maskm_field[] = { 
    {MAC_DA1_SA1_RULE_MASK_RSVDf,1,1,3},
    {MAC_DA1_SA1_RULE_MASK_L2_TYPEf,3,1,0},
    {MAC_DA1_SA1_RULE_MASK_MAC_DA1f,16,0,16},
    {MAC_DA1_SA1_RULE_MASK_MAC_SA1f,16,0,0},
};

const field_id_t mac_sa0_rulem_field[] = { 
    {MAC_SA0_RULE_PRIOf,9,1,21},
    {MAC_SA0_RULE_SRC_PORT_MASKf,11,1,10},
    {MAC_SA0_RULE_LOGIC_NOTf,1,1,9},
    {MAC_SA0_RULE_RULE_TYPEf,5,1,4},
    {MAC_SA0_RULE_L3_TYPEf,4,1,0},
    {MAC_SA0_RULE_MAC_SA0f,32,0,0},
};

const field_id_t mac_sa0_rule_maskm_field[] = { 
    {MAC_SA0_RULE_MASK_L3_TYPEf,4,1,0},
    {MAC_SA0_RULE_MASK_MAC_SA0f,32,0,0},
};

const field_id_t ipv4_da_rulem_field[] = { 
    {IPV4_DA_RULE_RANGE0_ENf,1,1,30},
    {IPV4_DA_RULE_PRIOf,9,1,21},
    {IPV4_DA_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV4_DA_RULE_LOGIC_NOTf,1,1,9},
    {IPV4_DA_RULE_RULE_TYPEf,5,1,4},
    {IPV4_DA_RULE_IP_FRAGMENTf,1,1,3},
    {IPV4_DA_RULE_L4_TYPEf,3,1,0},
    {IPV4_DA_RULE_IPV4_DAf,32,0,0},
};

const field_id_t ipv4_da_rule_maskm_field[] = { 
    {IPV4_DA_RULE_MASK_IP_FRAGMENTf,1,1,3},
    {IPV4_DA_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV4_DA_RULE_MASK_IPV4_DAf,32,0,0},
};

const field_id_t ipv4_sa_rulem_field[] = { 
    {IPV4_SA_RULE_RANGE0_ENf,1,1,30},
    {IPV4_SA_RULE_PRIOf,9,1,21},
    {IPV4_SA_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV4_SA_RULE_LOGIC_NOTf,1,1,9},
    {IPV4_SA_RULE_RULE_TYPEf,5,1,4},
    {IPV4_SA_RULE_IP_FRAGMENTf,1,1,3},
    {IPV4_SA_RULE_L4_TYPEf,3,1,0},
    {IPV4_SA_RULE_IPV4_SAf,32,0,0},
};

const field_id_t ipv4_sa_rule_maskm_field[] = { 
    {IPV4_SA_RULE_MASK_IP_FRAGMENTf,1,1,3},
    {IPV4_SA_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV4_SA_RULE_MASK_IPV4_SAf,32,0,0},
};

const field_id_t l4_port_rulem_field[] = { 
    {L4_PORT_RULE_RANGE1_ENf,1,1,31},
    {L4_PORT_RULE_RANGE0_ENf,1,1,30},
    {L4_PORT_RULE_PRIOf,9,1,21},
    {L4_PORT_RULE_SRC_PORT_MASKf,11,1,10},
    {L4_PORT_RULE_LOGIC_NOTf,1,1,9},
    {L4_PORT_RULE_RULE_TYPEf,5,1,4},
    {L4_PORT_RULE_IP_FRAGMENTf,1,1,3},
    {L4_PORT_RULE_L4_TYPEf,3,1,0},
    {L4_PORT_RULE_L4_DPORTf,16,0,16},
    {L4_PORT_RULE_L4_SPORTf,16,0,0},
};

const field_id_t l4_port_rule_maskm_field[] = { 
    {L4_PORT_RULE_MASK_IP_FRAGMENTf,1,1,3},
    {L4_PORT_RULE_MASK_L4_TYPEf,3,1,0},
    {L4_PORT_RULE_MASK_L4_DPORTf,16,0,16},
    {L4_PORT_RULE_MASK_L4_SPORTf,16,0,0},
};

const field_id_t vlan_rulem_field[] = { 
    {VLAN_RULE_RANGE1_ENf,1,1,31},
    {VLAN_RULE_RANGE0_ENf,1,1,30},
    {VLAN_RULE_PRIOf,9,1,21},
    {VLAN_RULE_SRC_PORT_MASKf,11,1,10},
    {VLAN_RULE_LOGIC_NOTf,1,1,9},
    {VLAN_RULE_RULE_TYPEf,5,1,4},
    {VLAN_RULE_CDEIf,1,1,3},
    {VLAN_RULE_CPRIf,3,1,0},
    {VLAN_RULE_CTAG_FMTf,2,0,30},
    {VLAN_RULE_SDEIf,1,0,29},
    {VLAN_RULE_SPRIf,3,0,26},
    {VLAN_RULE_STAG_FMTf,2,0,24},
    {VLAN_RULE_SVIDf,12,0,12},
    {VLAN_RULE_CVIDf,12,0,0},
};

const field_id_t vlan_rule_maskm_field[] = { 
    {VLAN_RULE_MASK_CDEIf,1,1,3},
    {VLAN_RULE_MASK_CPRIf,3,1,0},
    {VLAN_RULE_MASK_CTAG_FMTf,2,0,30},
    {VLAN_RULE_MASK_SDEIf,1,0,29},
    {VLAN_RULE_MASK_SPRIf,3,0,26},
    {VLAN_RULE_MASK_STAG_FMTf,2,0,24},
    {VLAN_RULE_MASK_SVIDf,12,0,12},
    {VLAN_RULE_MASK_CVIDf,12,0,0},
};

const field_id_t misc_rulem_field[] = { 
    {MISC_RULE_PRIOf,9,1,21},
    {MISC_RULE_SRC_PORT_MASKf,11,1,10},
    {MISC_RULE_LOGIC_NOTf,1,1,9},
    {MISC_RULE_RULE_TYPEf,5,1,4},
    {MISC_RULE_IP_FRAGMENTf,1,1,3},
    {MISC_RULE_L4_TYPEf,3,1,0},
    {MISC_RULE_RSVDf,1,0,31},
    {MISC_RULE_PPPOE_FLAGf,1,0,30},
    {MISC_RULE_IP_1ST_FRAGMENTf,1,0,29},
    {MISC_RULE_IP_OPTIONf,1,0,28},
    {MISC_RULE_TCP_FLAGSf,8,0,20},
    {MISC_RULE_IP_PROTOCOLf,8,0,12},
    {MISC_RULE_TOSf,8,0,4},
    {MISC_RULE_L3_TYPEf,4,0,0},
};

const field_id_t misc_rule_maskm_field[] = { 
    {MISC_RULE_MASK_IP_FRAGMENTf,1,1,3},
    {MISC_RULE_MASK_L4_TYPEf,3,1,0},
    {MISC_RULE_MASK_RSVDf,1,0,31},
    {MISC_RULE_MASK_PPPOE_FLAGf,1,0,30},
    {MISC_RULE_MASK_IP_1ST_FRAGMENTf,1,0,29},
    {MISC_RULE_MASK_IP_OPTIONf,1,0,28},
    {MISC_RULE_MASK_TCP_FLAGSf,8,0,20},
    {MISC_RULE_MASK_IP_PROTOCOLf,8,0,12},
    {MISC_RULE_MASK_TOSf,8,0,4},
    {MISC_RULE_MASK_L3_TYPEf,4,0,0},
};

const field_id_t udf_rulem_field[] = { 
    {UDF_RULE_PRIOf,9,1,21},
    {UDF_RULE_SRC_PORT_MASKf,11,1,10},
    {UDF_RULE_LOGIC_NOTf,1,1,9},
    {UDF_RULE_RULE_TYPEf,5,1,4},
    {UDF_RULE_RSVDf,3,1,1},
    {UDF_RULE_IS_IGMPf,1,1,0},
    {UDF_RULE_UDF0f,16,0,16},
    {UDF_RULE_UDF1f,16,0,0},
};

const field_id_t udf_rule_maskm_field[] = { 
    {UDF_RULE_MASK_RSVDf,3,1,1},
    {UDF_RULE_MASK_IS_IGMPf,1,1,0},
    {UDF_RULE_MASK_UDF0f,16,0,16},
    {UDF_RULE_MASK_UDF1f,16,0,0},
};

const field_id_t ipv6_da0_rulem_field[] = { 
    {IPV6_DA0_RULE_PRIOf,9,1,21},
    {IPV6_DA0_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_DA0_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_DA0_RULE_RULE_TYPEf,5,1,4},
    {IPV6_DA0_RULE_RSVDf,1,1,3},
    {IPV6_DA0_RULE_L4_TYPEf,3,1,0},
    {IPV6_DA0_RULE_IPV6_DA0f,32,0,0},
};

const field_id_t ipv6_da0_rule_maskm_field[] = { 
    {IPV6_DA0_RULE_MASK_RSVDf,1,1,3},
    {IPV6_DA0_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_DA0_RULE_MASK_IPV6_DA0f,32,0,0},
};

const field_id_t ipv6_da1_rulem_field[] = { 
    {IPV6_DA1_RULE_PRIOf,9,1,21},
    {IPV6_DA1_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_DA1_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_DA1_RULE_RULE_TYPEf,5,1,4},
    {IPV6_DA1_RULE_IP_OPTIONf,1,1,3},
    {IPV6_DA1_RULE_L4_TYPEf,3,1,0},
    {IPV6_DA1_RULE_IPV6_DA1f,32,0,0},
};

const field_id_t ipv6_da1_rule_maskm_field[] = { 
    {IPV6_DA1_RULE_MASK_IP_OPTIONf,1,1,3},
    {IPV6_DA1_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_DA1_RULE_MASK_IPV6_DA1f,32,0,0},
};

const field_id_t ipv6_da2_rulem_field[] = { 
    {IPV6_DA2_RULE_PRIOf,9,1,21},
    {IPV6_DA2_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_DA2_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_DA2_RULE_RULE_TYPEf,5,1,4},
    {IPV6_DA2_RULE_IP_FIRST_FRAGMENTf,1,1,3},
    {IPV6_DA2_RULE_L4_TYPEf,3,1,0},
    {IPV6_DA2_RULE_IPV6_DA2f,32,0,0},
};

const field_id_t ipv6_da2_rule_maskm_field[] = { 
    {IPV6_DA2_RULE_MASK_IP_FIRST_FRAGMENTf,1,1,3},
    {IPV6_DA2_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_DA2_RULE_MASK_IPV6_DA2f,32,0,0},
};

const field_id_t ipv6_da3_rulem_field[] = { 
    {IPV6_DA3_RULE_RANGE0_ENf,1,1,30},
    {IPV6_DA3_RULE_PRIOf,9,1,21},
    {IPV6_DA3_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_DA3_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_DA3_RULE_RULE_TYPEf,5,1,4},
    {IPV6_DA3_RULE_IP_FRAGMENTf,1,1,3},
    {IPV6_DA3_RULE_L4_TYPEf,3,1,0},
    {IPV6_DA3_RULE_IPV6_DA3f,32,0,0},
};

const field_id_t ipv6_da3_rule_maskm_field[] = { 
    {IPV6_DA3_RULE_MASK_IP_FRAGMENTf,1,1,3},
    {IPV6_DA3_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_DA3_RULE_MASK_IPV6_DA3f,32,0,0},
};

const field_id_t ipv6_sa0_rulem_field[] = { 
    {IPV6_SA0_RULE_PRIOf,9,1,21},
    {IPV6_SA0_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_SA0_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_SA0_RULE_RULE_TYPEf,5,1,4},
    {IPV6_SA0_RULE_RSVDf,1,1,3},
    {IPV6_SA0_RULE_L4_TYPEf,3,1,0},
    {IPV6_SA0_RULE_IPV6_SA0f,32,0,0},
};

const field_id_t ipv6_sa0_rule_maskm_field[] = { 
    {IPV6_SA0_RULE_MASK_RSVDf,1,1,3},
    {IPV6_SA0_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_SA0_RULE_MASK_IPV6_SA0f,32,0,0},
};

const field_id_t ipv6_sa1_rulem_field[] = { 
    {IPV6_SA1_RULE_PRIOf,9,1,21},
    {IPV6_SA1_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_SA1_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_SA1_RULE_RULE_TYPEf,5,1,4},
    {IPV6_SA1_RULE_IP_OPTIONf,1,1,3},
    {IPV6_SA1_RULE_L4_TYPEf,3,1,0},
    {IPV6_SA1_RULE_IPV6_SA1f,32,0,0},
};

const field_id_t ipv6_sa1_rule_maskm_field[] = { 
    {IPV6_SA1_RULE_MASK_IP_OPTIONf,1,1,3},
    {IPV6_SA1_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_SA1_RULE_MASK_IPV6_SA1f,32,0,0},
};

const field_id_t ipv6_sa2_rulem_field[] = { 
    {IPV6_SA2_RULE_PRIOf,9,1,21},
    {IPV6_SA2_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_SA2_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_SA2_RULE_RULE_TYPEf,5,1,4},
    {IPV6_SA2_RULE_IP_FIRST_FRAGMENTf,1,1,3},
    {IPV6_SA2_RULE_L4_TYPEf,3,1,0},
    {IPV6_SA2_RULE_IPV6_SA2f,32,0,0},
};

const field_id_t ipv6_sa2_rule_maskm_field[] = { 
    {IPV6_SA2_RULE_MASK_IP_FIRST_FRAGMENTf,1,1,3},
    {IPV6_SA2_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_SA2_RULE_MASK_IPV6_SA2f,32,0,0},
};

const field_id_t ipv6_sa3_rulem_field[] = { 
    {IPV6_SA3_RULE_RANGE0_ENf,1,1,30},
    {IPV6_SA3_RULE_PRIOf,9,1,21},
    {IPV6_SA3_RULE_SRC_PORT_MASKf,11,1,10},
    {IPV6_SA3_RULE_LOGIC_NOTf,1,1,9},
    {IPV6_SA3_RULE_RULE_TYPEf,5,1,4},
    {IPV6_SA3_RULE_IP_FRAGMENTf,1,1,3},
    {IPV6_SA3_RULE_L4_TYPEf,3,1,0},
    {IPV6_SA3_RULE_IPV6_SA3f,32,0,0},
};

const field_id_t ipv6_sa3_rule_maskm_field[] = { 
    {IPV6_SA3_RULE_MASK_IP_FRAGMENTf,1,1,3},
    {IPV6_SA3_RULE_MASK_L4_TYPEf,3,1,0},
    {IPV6_SA3_RULE_MASK_IPV6_SA3f,32,0,0},
};

const field_id_t vid_pri_dei_rulem_field[] = { 
    {VID_PRI_DEI_RULE_RANGE1_ENf,1,1,31},
    {VID_PRI_DEI_RULE_RANGE0_ENf,1,1,30},
    {VID_PRI_DEI_RULE_PRIOf,9,1,21},
    {VID_PRI_DEI_RULE_SRC_PORT_MASKf,11,1,10},
    {VID_PRI_DEI_RULE_LOGIC_NOTf,1,1,9},
    {VID_PRI_DEI_RULE_RULE_TYPEf,5,1,4},
    {VID_PRI_DEI_RULE_RSVf,4,1,0},
    {VID_PRI_DEI_RULE_CDEIf,1,0,31},
    {VID_PRI_DEI_RULE_CPRIf,3,0,28},
    {VID_PRI_DEI_RULE_SDEIf,1,0,27},
    {VID_PRI_DEI_RULE_SPRIf,3,0,24},
    {VID_PRI_DEI_RULE_SVIDf,12,0,12},
    {VID_PRI_DEI_RULE_CVIDf,12,0,0},
};

const field_id_t vid_pri_dei_rule_maskm_field[] = { 
    {VID_PRI_DEI_RULE_MASK_CDEIf,1,0,31},
    {VID_PRI_DEI_RULE_MASK_CPRIf,3,0,28},
    {VID_PRI_DEI_RULE_MASK_SDEIf,1,0,27},
    {VID_PRI_DEI_RULE_MASK_SPRIf,3,0,24},
    {VID_PRI_DEI_RULE_MASK_SVIDf,12,0,12},
    {VID_PRI_DEI_RULE_MASK_CVIDf,12,0,0},
};

const field_id_t ether_type_value_rulem_field[] = { 
    {ETHER_TYPE_VALUE_RULE_RANGE_ENf,1,1,30},
    {ETHER_TYPE_VALUE_RULE_PRIOf,9,1,21},
    {ETHER_TYPE_VALUE_RULE_SRC_PORT_MASKf,11,1,10},
    {ETHER_TYPE_VALUE_RULE_LOGIC_NOTf,1,1,9},
    {ETHER_TYPE_VALUE_RULE_RULE_TYPEf,5,1,4},
    {ETHER_TYPE_VALUE_RULE_RSV1f,1,1,3},
    {ETHER_TYPE_VALUE_RULE_L4_TYPEf,3,1,0},
    {ETHER_TYPE_VALUE_RULE_RSV0f,16,0,16},
    {ETHER_TYPE_VALUE_RULE_ETHER_TYPE_VALUEf,16,0,0},
};

const field_id_t ether_type_value_rule_maskm_field[] = { 
    {ETHER_TYPE_VALUE_RULE_MASK_RSV1f,1,1,3},
    {ETHER_TYPE_VALUE_RULE_MASK_L4_TYPEf,3,1,0},
    {ETHER_TYPE_VALUE_RULE_MASK_RSV0f,16,0,16},
    {ETHER_TYPE_VALUE_RULE_MASK_ETHER_TYPE_VALUEf,16,0,0},
};

const field_id_t dscp_to_int_prio_mapm_field[] = { 
    {DSCP_TO_INT_PRIO_MAP_INT_PRIOf,3,0,2},
    {DSCP_TO_INT_PRIO_MAP_INT_DPf,2,0,0},
};

const field_id_t pri_to_int_prio_mapm_field[] = { 
    {PRI_TO_INT_PRIO_MAP_INT_PRIOf,3,0,2},
    {PRI_TO_INT_PRIO_MAP_INT_DPf,2,0,0},
};

const field_id_t qos_port_ctrlnm_field[] = { 
    {QOS_PORT_CTRLN_CPRI_MAP_SELf,1,0,5},
    {QOS_PORT_CTRLN_SPRI_MAP_SELf,1,0,4},
    {QOS_PORT_CTRLN_PORT_INTPRIf,3,0,1},
    {QOS_PORT_CTRLN_PORT_INTPRI_ENf,1,0,0},
};

const field_id_t qos_merge_precedence_ctrlnm_field[] = { 
    {QOS_MERGE_PRECEDENCE_CTRLN_PORT_PRI_PRECEDENCEf,3,0,21},
    {QOS_MERGE_PRECEDENCE_CTRLN_SPRI2INT_PRI_PRECEDENCEf,3,0,18},
    {QOS_MERGE_PRECEDENCE_CTRLN_CPRI2INT_PRI_PRECEDENCEf,3,0,15},
    {QOS_MERGE_PRECEDENCE_CTRLN_DSCP2INT_PRI_PRECEDENCEf,3,0,12},
    {QOS_MERGE_PRECEDENCE_CTRLN_ACL_INT_PRI_PRECEDENCEf,3,0,9},
    {QOS_MERGE_PRECEDENCE_CTRLN_VLAN_INT_PRI_PRECEDENCEf,3,0,6},
    {QOS_MERGE_PRECEDENCE_CTRLN_MAC_DA_INT_PRI_PRECEDENCEf,3,0,3},
    {QOS_MERGE_PRECEDENCE_CTRLN_MAC_SA_INT_PRI_PRECEDENCEf,3,0,0},
};

const field_id_t hdr_err_actionm_field[] = { 
};

const field_id_t l2_vlan_ingress_filter_enm_field[] = { 
    {L2_VLAN_INGRESS_FILTER_EN_IGMP_BYPASS_ENf,11,0,11},
    {L2_VLAN_INGRESS_FILTER_EN_FILTER_ENf,11,0,0},
};

const field_id_t l2_arp_bcast_per_port_ctrlm_field[] = { 
    {L2_ARP_BCAST_PER_PORT_CTRL_DROPf,11,0,11},
    {L2_ARP_BCAST_PER_PORT_CTRL_COPY_TO_CPUf,11,0,0},
};

const field_id_t l2_nd_per_port_ctrlm_field[] = { 
    {L2_ND_PER_PORT_CTRL_DROPf,11,0,11},
    {L2_ND_PER_PORT_CTRL_COPY_TO_CPUf,11,0,0},
};

const field_id_t l2_lldp_eee_per_port_ctrlm_field[] = { 
    {L2_LLDP_EEE_PER_PORT_CTRL_DROPf,11,0,11},
    {L2_LLDP_EEE_PER_PORT_CTRL_COPY_TO_CPUf,11,0,0},
};

const field_id_t l2_lldp_per_port_ctrlm_field[] = { 
    {L2_LLDP_PER_PORT_CTRL_DROPf,11,0,11},
    {L2_LLDP_PER_PORT_CTRL_COPY_TO_CPUf,11,0,0},
};

const field_id_t l2_port_isolation_ctrlnm_field[] = { 
    {L2_PORT_ISOLATION_CTRLN_ISOLATED_PORT_MASKf,11,0,0},
};

const field_id_t l2_erp_per_port_ctrlm_field[] = { 
};

const field_id_t l2_stp_statenm_field[] = { 
    {L2_STP_STATEN_STATEf,22,0,0},
};

const field_id_t l2_src_match_ctrlm_field[] = { 
    {L2_SRC_MATCH_CTRL_SRC_MATCH_DISCARDf,11,0,0},
};

const field_id_t l2_learn_per_port_ctrlnm_field[] = { 
    {L2_LEARN_PER_PORT_CTRLN_VID_LEARN_MULTI_ENf,1,0,22},
    {L2_LEARN_PER_PORT_CTRLN_VID_LEARN_MODEf,1,0,21},
    {L2_LEARN_PER_PORT_CTRLN_VID_LEARN_ENf,1,0,20},
    {L2_LEARN_PER_PORT_CTRLN_SUSPEND_COPY_ENf,1,0,19},
    {L2_LEARN_PER_PORT_CTRLN_SUSPEND_DROP_ENf,1,0,18},
    {L2_LEARN_PER_PORT_CTRLN_LEARN_DISABLEf,1,0,17},
    {L2_LEARN_PER_PORT_CTRLN_LEARN_LIMIT_ENf,1,0,16},
    {L2_LEARN_PER_PORT_CTRLN_LEARN_LIMIT_NUMf,13,0,3},
    {L2_LEARN_PER_PORT_CTRLN_LEARN_LIMIT_DROPf,1,0,2},
    {L2_LEARN_PER_PORT_CTRLN_LEARN_MODEf,2,0,0},
};

const field_id_t l2_station_move_ctrl0m_field[] = { 
};

const field_id_t l2_station_move_ctrl1m_field[] = { 
};

const field_id_t l2_port_learn_mac_cntnm_field[] = { 
    {L2_PORT_LEARN_MAC_CNTN_MAC_CNTf,13,0,0},
};

const field_id_t l2_learn_global_ctrlm_field[] = { 
    {L2_LEARN_GLOBAL_CTRL_LEARN_MODEf,2,0,17},
    {L2_LEARN_GLOBAL_CTRL_GIP_LEARN_OVERWRITE_ALLOWf,1,0,16},
    {L2_LEARN_GLOBAL_CTRL_SA_LEARN_OVERWRITE_ALLOWf,1,0,15},
    {L2_LEARN_GLOBAL_CTRL_LEARN_LIMIT_ENf,1,0,14},
    {L2_LEARN_GLOBAL_CTRL_LEARN_LIMIT_NUMf,13,0,1},
    {L2_LEARN_GLOBAL_CTRL_LEARN_LIMIT_DROPf,1,0,0},
};

const field_id_t l2_learn_mac_cntm_field[] = { 
    {L2_LEARN_MAC_CNT_MAC_CNTf,13,0,0},
};

const field_id_t l2_aging_ctrlm_field[] = { 
    {L2_AGING_CTRL_AGING_INTERVALf,16,0,0},
};

const field_id_t l2_aging_per_port_ctrlm_field[] = { 
    {L2_AGING_PER_PORT_CTRL_AGING_ENf,11,0,0},
};

const field_id_t l2_fdb_tbl_op_data_0m_field[] = { 
    {L2_FDB_TBL_OP_DATA_0_MAC_DA_0f,32,0,0},
};

const field_id_t l2_fdb_tbl_op_data_1m_field[] = { 
    {L2_FDB_TBL_OP_DATA_1_DMAC_INT_PRI_ENf,1,0,31},
    {L2_FDB_TBL_OP_DATA_1_STATUSf,3,0,28},
    {L2_FDB_TBL_OP_DATA_1_FIDf,12,0,16},
    {L2_FDB_TBL_OP_DATA_1_MAC_DA_1f,16,0,0},
};

const field_id_t l2_fdb_tbl_op_data_2m_field[] = { 
    {L2_FDB_TBL_OP_DATA_2_MOVE_AGING_STATUSf,2,0,30},
    {L2_FDB_TBL_OP_DATA_2_SMAC_DROPf,1,0,29},
    {L2_FDB_TBL_OP_DATA_2_DST_PORT_MASKf,11,0,18},
    {L2_FDB_TBL_OP_DATA_2_DMAC_DROPf,1,0,17},
    {L2_FDB_TBL_OP_DATA_2_COPY_TO_CPUf,1,0,16},
    {L2_FDB_TBL_OP_DATA_2_SMAC_INT_PRI_ENf,1,0,15},
    {L2_FDB_TBL_OP_DATA_2_INT_PRIf,3,0,12},
    {L2_FDB_TBL_OP_DATA_2_NEW_VIDf,12,0,0},
};

const field_id_t l2_fdb_tbl_opm_field[] = { 
    {L2_FDB_TBL_OP_ENTRY_INDEXf,12,0,11},
    {L2_FDB_TBL_OP_OP_MODEf,1,0,10},
    {L2_FDB_TBL_OP_FLUSH_MODEf,3,0,7},
    {L2_FDB_TBL_OP_FLUSH_STATIC_ENf,1,0,6},
    {L2_FDB_TBL_OP_GET_NEXT_TYPEf,2,0,4},
    {L2_FDB_TBL_OP_OP_CMDf,3,0,1},
    {L2_FDB_TBL_OP_OP_STARTf,1,0,0},
};

const field_id_t l2_fdb_tbl_op_resultm_field[] = { 
    {L2_FDB_TBL_OP_RESULT_OP_DONEf,1,0,15},
    {L2_FDB_TBL_OP_RESULT_LOOKUP_FAILf,1,0,14},
    {L2_FDB_TBL_OP_RESULT_OVERWRITEf,1,0,13},
    {L2_FDB_TBL_OP_RESULT_OP_RESULTf,1,0,12},
    {L2_FDB_TBL_OP_RESULT_ENTRY_INDEXf,12,0,0},
};

const field_id_t l2_igmp_static_router_port_maskm_field[] = { 
    {L2_IGMP_STATIC_ROUTER_PORT_MASK_PORT_MASKf,11,0,0},
};

const field_id_t l2_igmp_dynamic_router_port_ctrlm_field[] = { 
    {L2_IGMP_DYNAMIC_ROUTER_PORT_CTRL_ALLOW_DYNAMIC_PORT_MASKf,11,0,4},
    {L2_IGMP_DYNAMIC_ROUTER_PORT_CTRL_TIMER_VALf,4,0,0},
};

const field_id_t l2_igmp_dynamic_router_portm_field[] = { 
};

const field_id_t l2_igmp_dynamic_router_port0_timerm_field[] = { 
};

const field_id_t l2_igmp_dynamic_router_port1_timerm_field[] = { 
};

const field_id_t l2_igmp_global_ctrlm_field[] = { 
    {L2_IGMP_GLOBAL_CTRL_REPORT_LEAVE_ROUTER_FWD_CTRLf,1,0,11},
    {L2_IGMP_GLOBAL_CTRL_REPORT_LEAVE_FWDf,1,0,10},
    {L2_IGMP_GLOBAL_CTRL_IGMP_FORCE_ROUTER_DSTf,1,0,9},
    {L2_IGMP_GLOBAL_CTRL_MLD_OPf,2,0,7},
    {L2_IGMP_GLOBAL_CTRL_IGMP_OPf,2,0,5},
    {L2_IGMP_GLOBAL_CTRL_FAST_LEAVE_ENf,1,0,4},
    {L2_IGMP_GLOBAL_CTRL_BYPASS_IPV6_00XXf,1,0,3},
    {L2_IGMP_GLOBAL_CTRL_BYPASS_224_0_0_Xf,1,0,2},
    {L2_IGMP_GLOBAL_CTRL_BYPASS_224_0_1_Xf,1,0,1},
    {L2_IGMP_GLOBAL_CTRL_BYPASS_239_255_255_Xf,1,0,0},
};

const field_id_t l2_igmp_per_port_ctrlm_field[] = { 
    {L2_IGMP_PER_PORT_CTRL_BYPASS_FLOW_METERf,1,0,7},
    {L2_IGMP_PER_PORT_CTRL_BYPASS_PORT_METERf,1,0,6},
    {L2_IGMP_PER_PORT_CTRL_BYPASS_STORMf,1,0,5},
    {L2_IGMP_PER_PORT_CTRL_ALLOW_LEAVE_PKTf,1,0,4},
    {L2_IGMP_PER_PORT_CTRL_ALLOW_REPORT_PKTf,1,0,3},
    {L2_IGMP_PER_PORT_CTRL_ALLOW_QUERY_PKTf,1,0,2},
    {L2_IGMP_PER_PORT_CTRL_VLAN_LEAKYf,1,0,1},
    {L2_IGMP_PER_PORT_CTRL_PORT_ISOLATE_LEAKYf,1,0,0},
};

const field_id_t l2_fdb_tbl_op_data_0_dummym_field[] = { 
    {L2_FDB_TBL_OP_DATA_0_DUMMY_MAC_DA_0f,32,0,0},
};

const field_id_t l2_fdb_tbl_op_data_1_dummym_field[] = { 
    {L2_FDB_TBL_OP_DATA_1_DUMMY_DMAC_INT_PRI_ENf,1,0,31},
    {L2_FDB_TBL_OP_DATA_1_DUMMY_STATUSf,3,0,28},
    {L2_FDB_TBL_OP_DATA_1_DUMMY_FIDf,12,0,16},
    {L2_FDB_TBL_OP_DATA_1_DUMMY_MAC_DA_1f,16,0,0},
};

const field_id_t l2_fdb_tbl_op_data_2_dummym_field[] = { 
    {L2_FDB_TBL_OP_DATA_2_DUMMY_MOVE_AGING_STATUSf,2,0,30},
    {L2_FDB_TBL_OP_DATA_2_DUMMY_SMAC_DROPf,1,0,29},
    {L2_FDB_TBL_OP_DATA_2_DUMMY_DST_PORT_MASKf,11,0,18},
    {L2_FDB_TBL_OP_DATA_2_DUMMY_DMAC_DROPf,1,0,17},
    {L2_FDB_TBL_OP_DATA_2_DUMMY_COPY_TO_CPUf,1,0,16},
    {L2_FDB_TBL_OP_DATA_2_DUMMY_SMAC_INT_PRI_ENf,1,0,15},
    {L2_FDB_TBL_OP_DATA_2_DUMMY_INT_PRIf,3,0,12},
    {L2_FDB_TBL_OP_DATA_2_DUMMY_NEW_VIDf,12,0,0},
};

const field_id_t l2_igmp_dynamic_router_port_dummym_field[] = { 
    {L2_IGMP_DYNAMIC_ROUTER_PORT_DUMMY_PORT1f,4,0,4},
    {L2_IGMP_DYNAMIC_ROUTER_PORT_DUMMY_PORT0f,4,0,0},
};

const field_id_t l2_igmp_dynamic_router_port0_timer_dummym_field[] = { 
};

const field_id_t l2_igmp_dynamic_router_port1_timer_dummym_field[] = { 
};

const field_id_t l2_igmp_learn_ctrlm_field[] = { 
    {L2_IGMP_LEARN_CTRL_LIMIT_ENf,1,0,13},
    {L2_IGMP_LEARN_CTRL_MAX_GROUP_NUMf,13,0,0},
};

const field_id_t l2_igmp_learn_group_cntm_field[] = { 
    {L2_IGMP_LEARN_GROUP_CNT_CNTf,13,0,0},
};

const field_id_t l2_unknown_ucast_filter_maskm_field[] = { 
    {L2_UNKNOWN_UCAST_FILTER_MASK_UNKNOWN_UCAST_FILTER_MASKf,11,0,0},
};

const field_id_t l2_unknown_mcast_filter_maskm_field[] = { 
    {L2_UNKNOWN_MCAST_FILTER_MASK_UNKNOWN_MCAST_FILTER_MASKf,11,0,0},
};

const field_id_t l2_mcast_filter_maskm_field[] = { 
    {L2_MCAST_FILTER_MASK_MCAST_FILTER_MASKf,11,0,0},
};

const field_id_t l2_bcast_filter_maskm_field[] = { 
    {L2_BCAST_FILTER_MASK_BCAST_FILTER_MASKf,11,0,0},
};

const field_id_t l2_port_vlan_transparent_ctrlm_field[] = { 
    {L2_PORT_VLAN_TRANSPARENT_CTRL_PORTMASKf,11,0,0},
};

const field_id_t l2_egr_vlan_filter_enm_field[] = { 
    {L2_EGR_VLAN_FILTER_EN_FILTER_ENf,11,0,0},
};

const field_id_t l2_dot1x_ctrl1m_field[] = { 
    {L2_DOT1X_CTRL1_DOT1X_ENf,11,0,0},
};

const field_id_t l2_dot1x_ctrl2m_field[] = { 
    {L2_DOT1X_CTRL2_MC_RX_BYPASSf,1,0,25},
    {L2_DOT1X_CTRL2_BC_RX_BYPASSf,1,0,24},
    {L2_DOT1X_CTRL2_MC_TX_BYPASSf,1,0,23},
    {L2_DOT1X_CTRL2_BC_TX_BYPASSf,1,0,22},
    {L2_DOT1X_CTRL2_RX_PERMIT_PORT_MASKf,11,0,11},
    {L2_DOT1X_CTRL2_TX_PERMIT_PORT_MASKf,11,0,0},
};

const field_id_t ipmc_leaky_ctrlm_field[] = { 
    {IPMC_LEAKY_CTRL_IPMC_VLAN_LEAKYf,1,0,1},
    {IPMC_LEAKY_CTRL_IPMC_PORT_ISOLATION_LEAKYf,1,0,0},
};

const field_id_t link_agg_groupnm_field[] = { 
    {LINK_AGG_GROUPN_PORT_MASKf,11,0,3},
    {LINK_AGG_GROUPN_MEMBER_NUMf,3,0,0},
};

const field_id_t link_agg_membernm_field[] = { 
    {LINK_AGG_MEMBERN_PORTf,4,0,0},
};

const field_id_t rma_ctrlnm_field[] = { 
    {RMA_CTRLN_BYPASS_STORMf,1,0,12},
    {RMA_CTRLN_BYPASS_FLOW_METERf,1,0,11},
    {RMA_CTRLN_BYPASS_PORT_METERf,1,0,10},
    {RMA_CTRLN_DROPf,1,0,9},
    {RMA_CTRLN_COPY_TO_CPUf,1,0,8},
    {RMA_CTRLN_VLAN_LEAKYf,1,0,7},
    {RMA_CTRLN_PORT_ISOLATE_LEAKYf,1,0,6},
    {RMA_CTRLN_CPU_CODEf,6,0,0},
};

const field_id_t cpu_copy_dst_ctrlm_field[] = { 
    {CPU_COPY_DST_CTRL_FORCE_INT_PORTf,1,0,2},
    {CPU_COPY_DST_CTRL_TO_INT_CPUf,1,0,1},
    {CPU_COPY_DST_CTRL_TO_EXT_CPUf,1,0,0},
};

const field_id_t acl_unmatch_permit_enable_ctrlm_field[] = { 
    {ACL_UNMATCH_PERMIT_ENABLE_CTRL_ENABLEf,11,0,0},
};

const field_id_t oam_mux_actm_field[] = { 
    {OAM_MUX_ACT_MUX_ACTf,22,0,0},
};

const field_id_t oam_par_actm_field[] = { 
    {OAM_PAR_ACT_PAR_ACTf,22,0,1},
    {OAM_PAR_ACT_BYPASS_IM_AC_ENf,1,0,0},
};

const field_id_t cascade_ctrlm_field[] = { 
    {CASCADE_CTRL_PORT1f,4,0,5},
    {CASCADE_CTRL_PORT0f,4,0,1},
    {CASCADE_CTRL_ENf,1,0,0},
};

const field_id_t loop_detect_act_ctrlm_field[] = { 
};

const field_id_t igmp_router_port_aging_ctrlm_field[] = { 
    {IGMP_ROUTER_PORT_AGING_CTRL_AGING_INTERVALf,8,0,0},
};

const field_id_t multi_vlan_tblm_field[] = { 
    {MULTI_VLAN_TBL_FID1f,12,0,14},
    {MULTI_VLAN_TBL_MULTI_EN1f,1,0,13},
    {MULTI_VLAN_TBL_FID0f,12,0,1},
    {MULTI_VLAN_TBL_MULTI_EN0f,1,0,0},
};

const field_id_t l2_learn_clear_opm_field[] = { 
};

const field_id_t l2_uc_unknown_act_ctrlm_field[] = { 
    {L2_UC_UNKNOWN_ACT_CTRL_L2_UC_UNKNOWN_ACTf,22,0,0},
};

const field_id_t l2_mc_unknown_act_ctrlm_field[] = { 
    {L2_MC_UNKNOWN_ACT_CTRL_L2_MC_UNKNOWN_DROP_RMABYPASSf,1,0,23},
    {L2_MC_UNKNOWN_ACT_CTRL_L2_MC_UNKNOWN_DROP_IGMPBYPASSf,1,0,22},
    {L2_MC_UNKNOWN_ACT_CTRL_L2_MC_UNKNOWN_ACTf,22,0,0},
};

const field_id_t l2_lag_learn_limit_ctrlnm_field[] = { 
    {L2_LAG_LEARN_LIMIT_CTRLN_LEARN_LIMIT_ENf,1,0,14},
    {L2_LAG_LEARN_LIMIT_CTRLN_LEARN_LIMIT_NUMf,13,0,1},
    {L2_LAG_LEARN_LIMIT_CTRLN_LEARN_LIMIT_DROPf,1,0,0},
};

const field_id_t l2_loop_detect_flagm_field[] = { 
};

const field_id_t l2_loop_detect_flag_dummym_field[] = { 
};

const field_id_t l2_loop_detect_timerm_field[] = { 
};

const field_id_t l2_arp_bcast_per_port_ctrl1m_field[] = { 
};

const field_id_t l2_nd_per_port_ctrl1m_field[] = { 
};

const field_id_t l2_lldp_eee_per_port_ctrl1m_field[] = { 
};

const field_id_t l2_lldp_per_port_ctrl1m_field[] = { 
};

const field_id_t l2_arp_bcast_nd_per_port_ctrl2m_field[] = { 
};

const field_id_t l2_lldp_eee_per_port_ctrl2m_field[] = { 
};

const field_id_t l2_fdb_hw_flush_ctrlm_field[] = { 
    {L2_FDB_HW_FLUSH_CTRL_GLOBAL_ENf,1,0,0},
};

const field_id_t l2_uni_que_ctrlm_field[] = { 
};

const field_id_t l2_vlan_tblm_field[] = { 
    {L2_VLAN_TBL_UNTAG_MEMBER_BITMAPf,11,1,8},
    {L2_VLAN_TBL_STP_IDf,4,1,4},
    {L2_VLAN_TBL_SVL_ENf,1,1,3},
    {L2_VLAN_TBL_FID_1f,3,1,0},
    {L2_VLAN_TBL_FID_0f,9,0,23},
    {L2_VLAN_TBL_LEARN_DISABLEf,1,0,22},
    {L2_VLAN_TBL_INT_PRI_VALIDf,1,0,21},
    {L2_VLAN_TBL_INT_PRIf,3,0,18},
    {L2_VLAN_TBL_PORT_MEMBER_BITMAPf,11,0,7},
    {L2_VLAN_TBL_BYPASS_1X_ACCESS_CONTROLf,1,0,6},
    {L2_VLAN_TBL_METER_ENf,1,0,5},
    {L2_VLAN_TBL_METER_IDf,5,0,0},
};

const field_id_t l2_fdb_tbl_bin0m_field[] = { 
    {L2_FDB_TBL_BIN0_MOVE_AGING_STATUSf,2,2,30},
    {L2_FDB_TBL_BIN0_SMAC_DROPf,1,2,29},
    {L2_FDB_TBL_BIN0_DST_PORT_MASKf,11,2,18},
    {L2_FDB_TBL_BIN0_DMAC_DROPf,1,2,17},
    {L2_FDB_TBL_BIN0_COPY_TO_CPUf,1,2,16},
    {L2_FDB_TBL_BIN0_SMAC_INT_PRI_ENf,1,2,15},
    {L2_FDB_TBL_BIN0_INT_PRIf,3,2,12},
    {L2_FDB_TBL_BIN0_NEW_VIDf,12,2,0},
    {L2_FDB_TBL_BIN0_DMAC_INT_PRI_ENf,1,1,31},
    {L2_FDB_TBL_BIN0_STATUSf,3,1,28},
    {L2_FDB_TBL_BIN0_FIDf,12,1,16},
    {L2_FDB_TBL_BIN0_MAC_DA_1f,16,1,0},
    {L2_FDB_TBL_BIN0_MAC_DA_0f,32,0,0},
};

const field_id_t l2_fdb_tbl_bin1m_field[] = { 
};

const field_id_t l2_fdb_tbl_bin2m_field[] = { 
};

const field_id_t l2_fdb_tbl_bin3m_field[] = { 
};

const field_id_t l2_fdb_tbl_bin4m_field[] = { 
};

const field_id_t l2_fdb_tbl_bin5m_field[] = { 
};

const field_id_t l2_fdb_tbl_bin6m_field[] = { 
};

const field_id_t l2_fdb_tbl_bin7m_field[] = { 
};

const field_id_t acl_action_tblm_field[] = { 
    {ACL_ACTION_TBL_STAG_ASSIGNf,2,2,25},
    {ACL_ACTION_TBL_CTAG_ASSIGNf,2,2,23},
    {ACL_ACTION_TBL_FWD_DECISION_TYPEf,2,2,21},
    {ACL_ACTION_TBL_DEST_PORT_MASKf,11,2,10},
    {ACL_ACTION_TBL_FWD_DECISION_ENf,1,2,9},
    {ACL_ACTION_TBL_SDEIf,1,2,8},
    {ACL_ACTION_TBL_SDEI_REPLACE_ENf,1,2,7},
    {ACL_ACTION_TBL_SPRIf,3,2,4},
    {ACL_ACTION_TBL_SPRI_REPLACE_ENf,1,2,3},
    {ACL_ACTION_TBL_SVID_1f,3,2,0},
    {ACL_ACTION_TBL_SVID_0f,9,1,23},
    {ACL_ACTION_TBL_SVID_REPLACE_ENf,1,1,22},
    {ACL_ACTION_TBL_CDEIf,1,1,21},
    {ACL_ACTION_TBL_CDEI_REPLACE_ENf,1,1,20},
    {ACL_ACTION_TBL_CPRIf,3,1,17},
    {ACL_ACTION_TBL_CPRI_REPLACE_ENf,1,1,16},
    {ACL_ACTION_TBL_CVIDf,12,1,4},
    {ACL_ACTION_TBL_CVID_REPLACE_ENf,1,1,3},
    {ACL_ACTION_TBL_INT_PRI_1f,2,1,1},
    {ACL_ACTION_TBL_INT_PRI_0f,1,1,0},
    {ACL_ACTION_TBL_INT_PRI_VALIDf,1,0,31},
    {ACL_ACTION_TBL_INT_DPf,2,0,29},
    {ACL_ACTION_TBL_INT_DP_VALIDf,1,0,28},
    {ACL_ACTION_TBL_DSCPf,6,0,22},
    {ACL_ACTION_TBL_DSCP_REPLACE_ENf,1,0,21},
    {ACL_ACTION_TBL_METER_IDf,6,0,15},
    {ACL_ACTION_TBL_METER_ENf,1,0,14},
    {ACL_ACTION_TBL_MIRROR_ENf,1,0,13},
    {ACL_ACTION_TBL_FLOW_STATS_ENf,1,0,12},
    {ACL_ACTION_TBL_FLOW_STATS_PTRf,6,0,6},
    {ACL_ACTION_TBL_GPIO_ENf,1,0,5},
    {ACL_ACTION_TBL_GPIO_PINf,4,0,1},
    {ACL_ACTION_TBL_INTR_ENf,1,0,0},
};

const field_id_t port_rate_ctrlnm_field[] = { 
    {PORT_RATE_CTRLN_GAP_VALUEf,5,0,0},
};

const field_id_t storm_ctrl_timeslotm_field[] = { 
    {STORM_CTRL_TIMESLOT_TIMESLOTf,12,0,0},
};

const field_id_t meter_timeslotm_field[] = { 
    {METER_TIMESLOT_TIMESLOTf,12,0,0},
};

const field_id_t port_meter_ctrlnm_field[] = { 
    {PORT_METER_CTRLN_METER_ENf,1,0,4},
    {PORT_METER_CTRLN_METER_IDf,4,0,0},
};

const field_id_t storm_ctrl_mc_type_ctrlm_field[] = { 
    {STORM_CTRL_MC_TYPE_CTRL_STORM_CTRL_MC_TYPEf,11,0,0},
};

const field_id_t drop_event_logm_field[] = { 
};

const field_id_t stats_offsetm_field[] = { 
};

const field_id_t storm_ctrl_config_tblm_field[] = { 
    {STORM_CTRL_CONFIG_TBL_CIRf,19,0,13},
    {STORM_CTRL_CONFIG_TBL_CBSf,10,0,3},
    {STORM_CTRL_CONFIG_TBL_GAP_INCf,1,0,2},
    {STORM_CTRL_CONFIG_TBL_RATE_MODEf,1,0,1},
    {STORM_CTRL_CONFIG_TBL_STORM_ENf,1,0,0},
};

const field_id_t storm_ctrl_cnt_tblm_field[] = { 
};

const field_id_t meter_config_tblm_field[] = { 
    {METER_CONFIG_TBL_METER_ENf,1,2,14},
    {METER_CONFIG_TBL_CFf,1,2,13},
    {METER_CONFIG_TBL_DROP_COLORf,2,2,11},
    {METER_CONFIG_TBL_COLOR_MODEf,1,2,10},
    {METER_CONFIG_TBL_TOKEN_UNITf,3,2,7},
    {METER_CONFIG_TBL_BYTE_RATE_MODEf,1,2,6},
    {METER_CONFIG_TBL_RATE_MODEf,1,2,5},
    {METER_CONFIG_TBL_METER_MODEf,1,2,4},
    {METER_CONFIG_TBL_CBS_1f,4,2,0},
    {METER_CONFIG_TBL_CBS_0f,12,1,20},
    {METER_CONFIG_TBL_CIRf,18,1,2},
    {METER_CONFIG_TBL_EBS_1f,2,1,0},
    {METER_CONFIG_TBL_EBS_0f,14,0,18},
    {METER_CONFIG_TBL_EIRf,18,0,0},
};

const field_id_t meter_token_tblm_field[] = { 
};

const field_id_t flow_stats_tblm_field[] = { 
    {FLOW_STATS_TBL_CNT1f,12,1,0},
    {FLOW_STATS_TBL_CNT0f,32,0,0},
};

const field_id_t flow_stats_cfg_tblm_field[] = { 
    {FLOW_STATS_CFG_TBL_ENf,1,0,3},
    {FLOW_STATS_CFG_TBL_MODEf,1,0,2},
    {FLOW_STATS_CFG_TBL_SELf,2,0,0},
};

const field_id_t cpu_code_to_cpu_prio_mapnm_field[] = { 
};

const field_id_t int_prio_to_ucast_qid_mapnm_field[] = { 
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_7_TO_QIDf,3,0,28},
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_6_TO_QIDf,3,0,24},
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_5_TO_QIDf,3,0,20},
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_4_TO_QIDf,3,0,16},
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_3_TO_QIDf,3,0,12},
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_2_TO_QIDf,3,0,8},
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_1_TO_QIDf,3,0,4},
    {INT_PRIO_TO_UCAST_QID_MAPN_PRIO_0_TO_QIDf,3,0,0},
};

const field_id_t int_prio_to_mcast_qid_mapnm_field[] = { 
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_7_TO_QIDf,2,0,14},
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_6_TO_QIDf,2,0,12},
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_5_TO_QIDf,2,0,10},
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_4_TO_QIDf,2,0,8},
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_3_TO_QIDf,2,0,6},
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_2_TO_QIDf,2,0,4},
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_1_TO_QIDf,2,0,2},
    {INT_PRIO_TO_MCAST_QID_MAPN_PRIO_0_TO_QIDf,2,0,0},
};

const field_id_t mirror_ctrlm_field[] = { 
    {MIRROR_CTRL_INGR_MIRROR_ENf,11,0,16},
    {MIRROR_CTRL_EGR_MIRROR_ENf,11,0,4},
    {MIRROR_CTRL_MIRROR_PORTf,4,0,0},
};

const field_id_t mirror_qos_ctrlm_field[] = { 
    {MIRROR_QOS_CTRL_INGR_MIRROR_INT_PRIO_VALIDf,1,0,7},
    {MIRROR_QOS_CTRL_INGR_MIRROR_INT_PRIOf,3,0,4},
    {MIRROR_QOS_CTRL_EGR_MIRROR_INT_PRIO_VALIDf,1,0,3},
    {MIRROR_QOS_CTRL_EGR_MIRROR_INT_PRIOf,3,0,0},
};

const field_id_t flush_cfgm_field[] = { 
    {FLUSH_CFG_FLUSH_REQf,1,0,31},
    {FLUSH_CFG_FLUSH_DONEf,1,0,30},
    {FLUSH_CFG_FLUSH_QIDf,8,0,0},
};

const field_id_t oq_enq_dis_tblm_field[] = { 
    {OQ_ENQ_DIS_TBL_ENQ_DISf,1,0,0},
};

const field_id_t egr_port_ctrlnm_field[] = { 
    {EGR_PORT_CTRLN_CFI_REMARK_ENf,1,0,10},
    {EGR_PORT_CTRLN_DEI_REMARK_ENf,1,0,9},
    {EGR_PORT_CTRLN_DSCP_REMARK_ENf,1,0,8},
    {EGR_PORT_CTRLN_CPRIO_REMARK_ENf,1,0,7},
    {EGR_PORT_CTRLN_SPRIO_REMARK_ENf,1,0,6},
    {EGR_PORT_CTRLN_CTAG_TPID_SELf,2,0,4},
    {EGR_PORT_CTRLN_STAG_TPID_SELf,2,0,2},
    {EGR_PORT_CTRLN_CPRIO_REMARK_SELf,1,0,1},
    {EGR_PORT_CTRLN_SPRIO_REMARK_SELf,1,0,0},
};

const field_id_t egr_port_vlan_ctrlnm_field[] = { 
    {EGR_PORT_VLAN_CTRLN_STAG_KEEP_MODEf,1,0,31},
    {EGR_PORT_VLAN_CTRLN_CTAG_KEEP_MODEf,1,0,30},
    {EGR_PORT_VLAN_CTRLN_STAG_MODEf,3,0,27},
    {EGR_PORT_VLAN_CTRLN_DEFAULT_SVIDf,12,0,15},
    {EGR_PORT_VLAN_CTRLN_CTAG_MODEf,3,0,12},
    {EGR_PORT_VLAN_CTRLN_DEFAULT_CVIDf,12,0,0},
};

const field_id_t egr_dscp_remarknm_field[] = { 
    {EGR_DSCP_REMARKN_INT_PRIO_TO_DSCPf,6,0,0},
};

const field_id_t egr_prio_remarknm_field[] = { 
    {EGR_PRIO_REMARKN_INT_PRIO_TO_PRIOf,3,0,1},
    {EGR_PRIO_REMARKN_INT_PRIO_TO_DEIf,1,0,0},
};

const field_id_t egr_tpid_profilem_field[] = { 
    {EGR_TPID_PROFILE_TPIDf,16,0,0},
};

const field_id_t egr_vlan_trans_rule_ctrlnm_field[] = { 
    {EGR_VLAN_TRANS_RULE_CTRLN_PKT_STAG_INCLf,1,0,28},
    {EGR_VLAN_TRANS_RULE_CTRLN_PKT_CTAG_INCLf,1,0,27},
    {EGR_VLAN_TRANS_RULE_CTRLN_VID0f,12,0,15},
    {EGR_VLAN_TRANS_RULE_CTRLN_PORT_MASKf,11,0,4},
    {EGR_VLAN_TRANS_RULE_CTRLN_MVR_INCLf,1,0,3},
    {EGR_VLAN_TRANS_RULE_CTRLN_SVID_INCLf,1,0,2},
    {EGR_VLAN_TRANS_RULE_CTRLN_CVID_INCLf,1,0,1},
    {EGR_VLAN_TRANS_RULE_CTRLN_VALIDf,1,0,0},
};

const field_id_t egr_vlan_trans_rule_ctrl1nm_field[] = { 
    {EGR_VLAN_TRANS_RULE_CTRL1N_VID2f,12,0,13},
    {EGR_VLAN_TRANS_RULE_CTRL1N_VID1f,12,0,1},
    {EGR_VLAN_TRANS_RULE_CTRL1N_VID_RANGE_TYPEf,1,0,0},
};

const field_id_t egr_vlan_trans_data_ctrlnm_field[] = { 
    {EGR_VLAN_TRANS_DATA_CTRLN_CVIDf,12,0,14},
    {EGR_VLAN_TRANS_DATA_CTRLN_SVIDf,12,0,2},
    {EGR_VLAN_TRANS_DATA_CTRLN_CVID_ENf,1,0,1},
    {EGR_VLAN_TRANS_DATA_CTRLN_SVID_ENf,1,0,0},
};

const field_id_t egr_vlan_tag_transparent_ctrlm_field[] = { 
    {EGR_VLAN_TAG_TRANSPARENT_CTRL_STAG_KEEP_SRCPORT_MASKf,11,0,13},
    {EGR_VLAN_TAG_TRANSPARENT_CTRL_CTAG_KEEP_SRCPORT_MASKf,11,0,2},
    {EGR_VLAN_TAG_TRANSPARENT_CTRL_STAG_TRANSPARENT_ENf,1,0,1},
    {EGR_VLAN_TAG_TRANSPARENT_CTRL_CTAG_TRANSPARENT_ENf,1,0,0},
};

const field_id_t cpu_pkt_bypassedit_ctrlm_field[] = { 
};

const field_id_t ipg_pre_len_cfgm_field[] = { 
};

const field_id_t qsch_shp_slot_time_cfgm_field[] = { 
    {QSCH_SHP_SLOT_TIME_CFG_QSCH_SHP_SLOT_TIMEf,12,0,0},
};

const field_id_t psch_shp_slot_time_cfgm_field[] = { 
    {PSCH_SHP_SLOT_TIME_CFG_PSCH_SHP_SLOT_TIMEf,12,0,0},
};

const field_id_t qsch_flow_map_tblm_field[] = { 
    {QSCH_FLOW_MAP_TBL_E_DWRR_WEIGHTf,10,0,18},
    {QSCH_FLOW_MAP_TBL_C_DWRR_WEIGHTf,10,0,8},
    {QSCH_FLOW_MAP_TBL_E_PRIf,4,0,4},
    {QSCH_FLOW_MAP_TBL_C_PRIf,4,0,0},
};

const field_id_t qsch_c_dwrr_cfg_tblm_field[] = { 
    {QSCH_C_DWRR_CFG_TBL_DWRR_MODEf,1,0,0},
};

const field_id_t qsch_e_dwrr_cfg_tblm_field[] = { 
    {QSCH_E_DWRR_CFG_TBL_DWRR_MODEf,1,0,0},
};

const field_id_t qsch_shp_cfg_tblm_field[] = { 
    {QSCH_SHP_CFG_TBL_CFf,1,2,6},
    {QSCH_SHP_CFG_TBL_E_SHAPER_ENf,1,2,5},
    {QSCH_SHP_CFG_TBL_C_SHAPER_ENf,1,2,4},
    {QSCH_SHP_CFG_TBL_SHAPER_MODEf,1,2,3},
    {QSCH_SHP_CFG_TBL_TOKEN_LEVELf,3,2,0},
    {QSCH_SHP_CFG_TBL_EBSf,14,1,18},
    {QSCH_SHP_CFG_TBL_EIRf,18,1,0},
    {QSCH_SHP_CFG_TBL_CBSf,14,0,18},
    {QSCH_SHP_CFG_TBL_CIRf,18,0,0},
};

const field_id_t qsch_meter_cfg_tblm_field[] = { 
    {QSCH_METER_CFG_TBL_METER_LENGTHf,2,0,0},
};

const field_id_t psch_shp_cfg_tblm_field[] = { 
    {PSCH_SHP_CFG_TBL_C_SHAPER_ENf,1,1,4},
    {PSCH_SHP_CFG_TBL_SHAPER_MODEf,1,1,3},
    {PSCH_SHP_CFG_TBL_TOKEN_LEVELf,3,1,0},
    {PSCH_SHP_CFG_TBL_CBSf,14,0,18},
    {PSCH_SHP_CFG_TBL_CIRf,18,0,0},
};

const field_id_t psch_meter_cfg_tblm_field[] = { 
    {PSCH_METER_CFG_TBL_METER_LENGTHf,2,0,0},
};
