/*This file is auto generated by Python script. 2022-08-09 09:54:24.*/



 #ifndef _ALL_TIGER_STRUCT_H_
 #define _ALL_TIGER_STRUCT_H_
 #include "hal_mem.h"



 #define GLOBAL_CTRL0_CHIP_SW_RSTf 0
 #define GLOBAL_CTRL1_METER_ENf 0
 #define GLOBAL_CTRL1_AC_ENf 1
 #define GLOBAL_CTRL1_ACL_ENf 2
 #define GLOBAL_CTRL1_MIB_ENf 3
 #define GLOBAL_CTRL1_INTERRUP_POLARITYf 4
 #define EXT_CPU_PORT_CTRL_EXT_CPU_TAG_ENf 0
 #define EXT_CPU_PORT_CTRL_EXT_CPU_PORT_ENf 1
 #define EXT_CPU_PORT_CTRL_EXT_CPU_PORT_NUMf 2
 #define CPU_TAG_TPID_TPIDf 0
 #define LOOK_UP_VLAN_SEL_LOOK_UP_VLAN_SELf 0
 #define INTR_MASK_OVER_TEMP_INRPT_STATUSf 0
 #define INTR_MASK_MDIO_TRANS_DONE_INTf 1
 #define INTR_MASK_ACL_HITf 2
 #define INTR_MASK_DYING_GASP_INT_Pf 3
 #define INTR_MASK_PKT_WOL_MAGIC_INT_Pf 4
 #define INTR_MASK_QM_FLUSH_DONE_Pf 5
 #define INTR_MASK_HW_INI_DONEf 6
 #define INTR_MASK_IGMP_LEARN_FULLf 7
 #define INTR_MASK_IGMP_DELETEf 8
 #define INTR_MASK_FDB_LEARN_CREATEf 9
 #define INTR_MASK_FDB_LEARN_MOVEf 10
 #define INTR_MASK_FDB_DELETEf 11
 #define INTR_MASK_FDB_LEARN_FULLf 12
 #define INTR_MASK_CPU_OP_DONEf 13
 #define INTR_MASK_ACL_ACTf 14
 #define INTR_MASK_BRIDGE_CONGESTIONf 15
 #define INTR_MASK_LOOP_DETECTf 16
 #define INTR_MASK_EEPROM_LOAD_DONEf 17
 #define INTR_MASK_SG_INT1f 18
 #define INTR_MASK_SG_INT0f 19
 #define INTR_MASK_PHY_INT7f 20
 #define INTR_MASK_PHY_INT6f 21
 #define INTR_MASK_PHY_INT5f 22
 #define INTR_MASK_PHY_INT4f 23
 #define INTR_MASK_PHY_INT3f 24
 #define INTR_MASK_PHY_INT2f 25
 #define INTR_MASK_PHY_INT1f 26
 #define INTR_MASK_PHY_INT0f 27
 #define INTR_MASK_HW_EXCEPTIONf 28
 #define GLOBAL_MAC_ADDR0_MAC_ADDR_BYTE4f 0
 #define GLOBAL_MAC_ADDR0_MAC_ADDR_BYTE5f 1
 #define GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE0f 0
 #define GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE1f 1
 #define GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE2f 2
 #define GLOBAL_MAC_ADDR1_MAC_ADDR_BYTE3f 3
 #define SG_PHY_APPLICATION_MODEf 0
 #define SG_PHY_PAUSEf 1
 #define SG_PHY_LINKf 2
 #define SG_PHY_DUPLEX_MODEf 3
 #define SG_PHY_SPEED_MODEf 4
 #define PORT_CTRL_FLOW_LINK_ANf 0
 #define PORT_CTRL_AN_LINK_ENf 1
 #define PORT_CTRL_HALF_FC_ENf 2
 #define PORT_CTRL_DUPLEX_MODEf 3
 #define PORT_CTRL_RX_FC_ENf 4
 #define PORT_CTRL_TX_FC_ENf 5
 #define PORT_CTRL_RXMAC_ENf 6
 #define PORT_CTRL_TXMAC_ENf 7
 #define PORT_CTRL_SPEED_MODEf 8
 #define PORT_STATUS_LINKf 0
 #define PORT_STATUS_DUPLEX_MODEf 1
 #define PORT_STATUS_RX_FC_ENf 2
 #define PORT_STATUS_TX_FC_ENf 3
 #define PORT_STATUS_RXMAC_ENf 4
 #define PORT_STATUS_TXMAC_ENf 5
 #define PORT_STATUS_SPEED_MODEf 6
 #define LOOP_DETECT_TOP_CTRL_BUZZER_MODEf 0
 #define LOOP_DETECT_TOP_CTRL_BUZZER_ENf 1
 #define LOOP_DETECT_TOP_CTRL_UNIT_ID_REMOTE1f 2
 #define LOOP_DETECT_TOP_CTRL_UNIT_ID_REMOTE0f 3
 #define LOOP_DETECT_TOP_CTRL_UNIT_ID_LOCALf 4
 #define LOOP_DETECT_TOP_CTRL_ENf 5
 #define LOOP_DETECT_TOP_CTRL_LOOP_DETECT_TPIDf 6
 #define LOOP_DETECT_TOP_CTRL_GENERATE_MODEf 7
 #define LOOP_DETECT_TOP_CTRL_GENERATE_WAYf 8
 #define MDIO_POLLING_DUPLEXf 0
 #define MDIO_POLLING_LINKf 1
 #define MDIO_POLLING_SPEEDf 2
 #define EXTIF0_MODE_XMII_MODEf 0
 #define EXTIF0_MODE_RGMII_DELAY_TYPE_SELf 1
 #define EXTIF0_MODE_EN_MACMODE_LNKDN_SWHf 2
 #define EXTIF0_MODE_RGMII_TXC_DLY100_10_ENf 3
 #define EXTIF0_MODE_XMII_LINK_UPf 4
 #define EXTIF0_MODE_XMII_PORT_ENf 5
 #define EXTIF0_MODE_XMII_SOFT_RSTf 6
 #define EXTIF0_MODE_RGMII_TXC_DELAY_SELf 7
 #define EXTIF0_MODE_REMII_RX_XMII_SELf 8
 #define EXTIF0_MODE_XMII_TXC_IN_SELf 9
 #define EXTIF0_MODE_XMII_RXC_IN_SELf 10
 #define EXTIF0_MODE_REVERT_TXDf 11
 #define EXTIF0_MODE_RGMII_TXC_DELAY_ENf 12
 #define EXTIF0_MODE_RGMII_TXC_OUT_SELf 13
 #define EXTIF0_MODE_RGMII_RXC_DELAY_SELf 14
 #define EXTIF0_MODE_RMII_PHY_TXC_OUT_SELf 15
 #define EXTIF0_MODE_REMII_TXC_OUT_SELf 16
 #define EXTIF0_MODE_REMII_RXC_OUT_SELf 17
 #define EXTIF1_MODE_XMII_MODEf 0
 #define EXTIF1_MODE_RGMII_DELAY_TYPE_SELf 1
 #define EXTIF1_MODE_EN_MACMODE_LNKDN_SWHf 2
 #define EXTIF1_MODE_RGMII_TXC_DLY100_10_ENf 3
 #define EXTIF1_MODE_XMII_LINK_UPf 4
 #define EXTIF1_MODE_XMII_PORT_ENf 5
 #define EXTIF1_MODE_XMII_SOFT_RSTf 6
 #define EXTIF1_MODE_RGMII_TXC_DELAY_SELf 7
 #define EXTIF1_MODE_REMII_RX_XMII_SELf 8
 #define EXTIF1_MODE_XMII_TXC_IN_SELf 9
 #define EXTIF1_MODE_XMII_RXC_IN_SELf 10
 #define EXTIF1_MODE_REVERT_TXDf 11
 #define EXTIF1_MODE_RGMII_TXC_DELAY_ENf 12
 #define EXTIF1_MODE_RGMII_TXC_OUT_SELf 13
 #define EXTIF1_MODE_RGMII_RXC_DELAY_SELf 14
 #define EXTIF1_MODE_RMII_PHY_TXC_OUT_SELf 15
 #define EXTIF1_MODE_REMII_TXC_OUT_SELf 16
 #define EXTIF1_MODE_REMII_RXC_OUT_SELf 17

 #define TPID_PROFILE0_TPIDf 0
 #define TPID_PROFILE1_TPIDf 0
 #define PARSER_PORT_CTRLN_STAG_TPID_MASKf 0
 #define PARSER_PORT_CTRLN_CTAG_TPID_MASKf 1
 #define LINK_AGG_HASH_CTRL_HASH_FIELD_SELf 0
 #define UDF_CTRLN_UDF_TYPEf 0
 #define UDF_CTRLN_UDF_OFFSETf 1
 #define DOS_TCP_FLAGS0_DROP_EN 0
 #define DOS_TCP_FLAGS0_COPY_TO_CPUf 1
 #define DOS_TCP_FLAGS0_TCP_FLAGS_MASKf 2
 #define DOS_TCP_FLAGS0_SEQ_NUM0_MASKf 3
 #define DOS_TCP_FLAGS0_PUBLIC_TCP_SPORT_MASKf 4
 #define DOS_TCP_FLAGS0_TCP_FLAGSf 5
 #define DOS_TCP_FLAGS0_SEQ_NUM0f 6
 #define DOS_TCP_FLAGS0_PUBLIC_TCP_SPORTf 7
 #define DOS_CTRL_VLAN_CFI1DROP_ENf 0
 #define DOS_CTRL_PORT_EN_MASKf 1
 #define DOS_CTRL_TCP_HEADER_PARTIAL_COPY_TO_CPUf 2
 #define DOS_CTRL_LARGE_IPV6_ICMP_COPY_TO_CPUf 3
 #define DOS_CTRL_LARGE_IPV4_ICMP_COPY_TO_CPUf 4
 #define DOS_CTRL_TCP_FRAG_OFFSET1_COPY_TO_CPUf 5
 #define DOS_CTRL_TCP_SPORT_EQ_DPORT_COPY_TO_CPUf 6
 #define DOS_CTRL_UDP_SPORT_EQ_DPORT_COPY_TO_CPUf 7
 #define DOS_CTRL_ICMP_PRAG_COPY_TO_CPUf 8
 #define DOS_CTRL_SIP_EQ_DIP_COPY_TO_CPUf 9
 #define DOS_CTRL_MACSA_EQ_MACDA_COPY_TO_CPUf 10
 #define DOS_CTRL_TCP_HEADER_PARTIAL_DROPf 11
 #define DOS_CTRL_LARGE_IPV6_ICMP_DROPf 12
 #define DOS_CTRL_LARGE_IPV4_ICMP_DROPf 13
 #define DOS_CTRL_TCP_FRAG_OFFSET1_DROPf 14
 #define DOS_CTRL_TCP_SPORT_EQ_DPORT_DROPf 15
 #define DOS_CTRL_UDP_SPORT_EQ_DPORT_DROPf 16
 #define DOS_CTRL_ICMP_PRAG_DROPf 17
 #define DOS_CTRL_SIP_EQ_DIP_DROPf 18
 #define DOS_CTRL_MACSA_EQ_MACDA_DROPf 19
 #define DOS_LARGE_ICMP_CTRL_IPV6_ICMP_MAX_SIZEf 0
 #define DOS_LARGE_ICMP_CTRL_IPV4_ICMP_MAX_SIZEf 1
 #define OAM_EN_CTRL_ENf 0
 #define WOL_CTRL_WOL_ETH_TYPEf 0
 #define WOL_CTRL_WOL_ENf 1
 #define DOS_CTRL1_DA_ZERO_DROP_ENf 0
 #define DOS_CTRL1_SA_ZERO_DROP_ENf 1
 #define DOS_CTRL1_SA_BC_DROP_ENf 2
 #define DOS_CTRL1_SA_MC_DROP_ENf 3
 #define PROTOCOL_BASED_VLANN_VALIDf 0
 #define PROTOCOL_BASED_VLANN_L2_TYPE_BITMAPf 1
 #define PROTOCOL_BASED_VLANN_ETH_TYPEf 2
 #define PORT_VLAN_CTRLN_PRIORITY_TAG_SVID_ENf 0
 #define PORT_VLAN_CTRLN_PRIORITY_TAG_CVID_ENf 1
 #define PORT_VLAN_CTRLN_DEFAULT_SVIDf 2
 #define PORT_VLAN_CTRLN_DEFAULT_CVIDf 3
 #define PORT_VLAN_CTRLN_DEFAULT_SPRIOf 4
 #define PORT_VLAN_CTRLN_DEFAULT_CPRIOf 5
 #define PORT_VLAN_CTRL1N_VLAN_RANGE_MODEf 0
 #define PORT_VLAN_CTRL1N_VLAN_RANGE_PROFILE_IDf 1
 #define PORT_VLAN_CTRL1N_STAG_AFTf 2
 #define PORT_VLAN_CTRL1N_CTAG_AFTf 3
 #define VLAN_TRANS_UNTAG_VID_MODE_CTRL_MODEf 0
 #define VLAN_RANGE_PROFILEN_MAX_VID3f 0
 #define VLAN_RANGE_PROFILEN_MIN_VID3f 1
 #define VLAN_RANGE_PROFILEN_MAX_VID2_1f 2
 #define VLAN_RANGE_PROFILEN_MAX_VID2_0f 3
 #define VLAN_RANGE_PROFILEN_MIN_VID2f 4
 #define VLAN_RANGE_PROFILEN_MAX_VID1f 5
 #define VLAN_RANGE_PROFILEN_MIN_VID1_1f 6
 #define VLAN_RANGE_PROFILEN_MIN_VID1_0f 7
 #define VLAN_RANGE_PROFILEN_MAX_VID0f 8
 #define VLAN_RANGE_PROFILEN_MIN_VID0f 9
 #define PROTOCOL_BASED_VLAN_DATA_TBL_SVID_CMDf 0
 #define PROTOCOL_BASED_VLAN_DATA_TBL_SVIDf 1
 #define PROTOCOL_BASED_VLAN_DATA_TBL_CVID_CMDf 2
 #define PROTOCOL_BASED_VLAN_DATA_TBL_CVIDf 3
 #define VLAN_XLATE_ACTION_TBL_SVID_CMDf 0
 #define VLAN_XLATE_ACTION_TBL_NEW_SVID_1f 1
 #define VLAN_XLATE_ACTION_TBL_NEW_SVID_0f 2
 #define VLAN_XLATE_ACTION_TBL_CVID_CMDf 3
 #define VLAN_XLATE_ACTION_TBL_NEW_CVIDf 4
 #define VLAN_XLATE_ACTION_TBL_SPRIO_CMDf 5
 #define VLAN_XLATE_ACTION_TBL_NEW_SPRIOf 6
 #define VLAN_XLATE_ACTION_TBL_NEW_SDEIf 7
 #define VLAN_XLATE_ACTION_TBL_CPRIO_CMDf 8
 #define VLAN_XLATE_ACTION_TBL_NEW_CPRIOf 9
 #define VLAN_XLATE_ACTION_TBL_NEW_CDEIf 10
 #define VLAN_XLATE_TBL_VALIDf 0
 #define VLAN_XLATE_TBL_SVID_1f 1
 #define VLAN_XLATE_TBL_SVID_0f 2
 #define VLAN_XLATE_TBL_SVID_INCLf 3
 #define VLAN_XLATE_TBL_STAG_FMTf 4
 #define VLAN_XLATE_TBL_STAG_FMT_INCLf 5
 #define VLAN_XLATE_TBL_CVIDf 6
 #define VLAN_XLATE_TBL_CVID_INCLf 7
 #define VLAN_XLATE_TBL_CTAG_FMTf 8
 #define VLAN_XLATE_TBL_CTAG_FMT_INCLf 9
 #define VLAN_XLATE_TBL_SRC_PORT_MASKf 10
 #define ACL_BLK_KEEP_CTRL_GRPID7f 0
 #define ACL_BLK_KEEP_CTRL_KEEP7f 1
 #define ACL_BLK_KEEP_CTRL_GRPID6f 2
 #define ACL_BLK_KEEP_CTRL_KEEP6f 3
 #define ACL_BLK_KEEP_CTRL_GRPID5f 4
 #define ACL_BLK_KEEP_CTRL_KEEP5f 5
 #define ACL_BLK_KEEP_CTRL_GRPID4f 6
 #define ACL_BLK_KEEP_CTRL_KEEP4f 7
 #define ACL_BLK_KEEP_CTRL_GRPID3f 8
 #define ACL_BLK_KEEP_CTRL_KEEP3f 9
 #define ACL_BLK_KEEP_CTRL_GRPID2f 10
 #define ACL_BLK_KEEP_CTRL_KEEP2f 11
 #define ACL_BLK_KEEP_CTRL_GRPID1f 12
 #define ACL_BLK_KEEP_CTRL_KEEP1f 13
 #define ACL_BLK_KEEP_CTRL_GRPID0f 14
 #define ACL_BLK_KEEP_CTRL_KEEP0f 15
 #define ACL_PORT_CTRL_ENABLEf 0
 #define ACL_BLK_CMD_BLKIDf 0
 #define ACL_BLK_CMD_CMDf 1
 #define RULE_EXT_CTRL_GRPID7f 0
 #define RULE_EXT_CTRL_VALID7f 1
 #define RULE_EXT_CTRL_GRPID6f 2
 #define RULE_EXT_CTRL_VALID6f 3
 #define RULE_EXT_CTRL_GRPID5f 4
 #define RULE_EXT_CTRL_VALID5f 5
 #define RULE_EXT_CTRL_GRPID4f 6
 #define RULE_EXT_CTRL_VALID4f 7
 #define RULE_EXT_CTRL_GRPID3f 8
 #define RULE_EXT_CTRL_VALID3f 9
 #define RULE_EXT_CTRL_GRPID2f 10
 #define RULE_EXT_CTRL_VALID2f 11
 #define RULE_EXT_CTRL_GRPID1f 12
 #define RULE_EXT_CTRL_VALID1f 13
 #define RULE_EXT_CTRL_GRPID0f 14
 #define RULE_EXT_CTRL_VALID0f 15
 #define MAC_DA0_RULE_PRIOf 0
 #define MAC_DA0_RULE_SRC_PORT_MASKf 1
 #define MAC_DA0_RULE_LOGIC_NOTf 2
 #define MAC_DA0_RULE_RULE_TYPEf 3
 #define MAC_DA0_RULE_L3_TYPEf 4
 #define MAC_DA0_RULE_MAC_DA0f 5
 #define MAC_DA0_RULE_MASK_L3_TYPEf 0
 #define MAC_DA0_RULE_MASK_MAC_DA0f 1
 #define MAC_DA1_SA1_RULE_PRIOf 0
 #define MAC_DA1_SA1_RULE_SRC_PORT_MASKf 1
 #define MAC_DA1_SA1_RULE_LOGIC_NOTf 2
 #define MAC_DA1_SA1_RULE_RULE_TYPEf 3
 #define MAC_DA1_SA1_RULE_RSVDf 4
 #define MAC_DA1_SA1_RULE_L2_TYPEf 5
 #define MAC_DA1_SA1_RULE_MAC_DA1f 6
 #define MAC_DA1_SA1_RULE_MAC_SA1f 7
 #define MAC_DA1_SA1_RULE_MASK_RSVDf 0
 #define MAC_DA1_SA1_RULE_MASK_L2_TYPEf 1
 #define MAC_DA1_SA1_RULE_MASK_MAC_DA1f 2
 #define MAC_DA1_SA1_RULE_MASK_MAC_SA1f 3
 #define MAC_SA0_RULE_PRIOf 0
 #define MAC_SA0_RULE_SRC_PORT_MASKf 1
 #define MAC_SA0_RULE_LOGIC_NOTf 2
 #define MAC_SA0_RULE_RULE_TYPEf 3
 #define MAC_SA0_RULE_L3_TYPEf 4
 #define MAC_SA0_RULE_MAC_SA0f 5
 #define MAC_SA0_RULE_MASK_L3_TYPEf 0
 #define MAC_SA0_RULE_MASK_MAC_SA0f 1
 #define IPV4_DA_RULE_RANGE0_ENf 0
 #define IPV4_DA_RULE_PRIOf 1
 #define IPV4_DA_RULE_SRC_PORT_MASKf 2
 #define IPV4_DA_RULE_LOGIC_NOTf 3
 #define IPV4_DA_RULE_RULE_TYPEf 4
 #define IPV4_DA_RULE_IP_FRAGMENTf 5
 #define IPV4_DA_RULE_L4_TYPEf 6
 #define IPV4_DA_RULE_IPV4_DAf 7
 #define IPV4_DA_RULE_MASK_IP_FRAGMENTf 0
 #define IPV4_DA_RULE_MASK_L4_TYPEf 1
 #define IPV4_DA_RULE_MASK_IPV4_DAf 2
 #define IPV4_SA_RULE_RANGE0_ENf 0
 #define IPV4_SA_RULE_PRIOf 1
 #define IPV4_SA_RULE_SRC_PORT_MASKf 2
 #define IPV4_SA_RULE_LOGIC_NOTf 3
 #define IPV4_SA_RULE_RULE_TYPEf 4
 #define IPV4_SA_RULE_IP_FRAGMENTf 5
 #define IPV4_SA_RULE_L4_TYPEf 6
 #define IPV4_SA_RULE_IPV4_SAf 7
 #define IPV4_SA_RULE_MASK_IP_FRAGMENTf 0
 #define IPV4_SA_RULE_MASK_L4_TYPEf 1
 #define IPV4_SA_RULE_MASK_IPV4_SAf 2
 #define L4_PORT_RULE_RANGE1_ENf 0
 #define L4_PORT_RULE_RANGE0_ENf 1
 #define L4_PORT_RULE_PRIOf 2
 #define L4_PORT_RULE_SRC_PORT_MASKf 3
 #define L4_PORT_RULE_LOGIC_NOTf 4
 #define L4_PORT_RULE_RULE_TYPEf 5
 #define L4_PORT_RULE_IP_FRAGMENTf 6
 #define L4_PORT_RULE_L4_TYPEf 7
 #define L4_PORT_RULE_L4_DPORTf 8
 #define L4_PORT_RULE_L4_SPORTf 9
 #define L4_PORT_RULE_MASK_IP_FRAGMENTf 0
 #define L4_PORT_RULE_MASK_L4_TYPEf 1
 #define L4_PORT_RULE_MASK_L4_DPORTf 2
 #define L4_PORT_RULE_MASK_L4_SPORTf 3
 #define VLAN_RULE_RANGE1_ENf 0
 #define VLAN_RULE_RANGE0_ENf 1
 #define VLAN_RULE_PRIOf 2
 #define VLAN_RULE_SRC_PORT_MASKf 3
 #define VLAN_RULE_LOGIC_NOTf 4
 #define VLAN_RULE_RULE_TYPEf 5
 #define VLAN_RULE_CDEIf 6
 #define VLAN_RULE_CPRIf 7
 #define VLAN_RULE_CTAG_FMTf 8
 #define VLAN_RULE_SDEIf 9
 #define VLAN_RULE_SPRIf 10
 #define VLAN_RULE_STAG_FMTf 11
 #define VLAN_RULE_SVIDf 12
 #define VLAN_RULE_CVIDf 13
 #define VLAN_RULE_MASK_CDEIf 0
 #define VLAN_RULE_MASK_CPRIf 1
 #define VLAN_RULE_MASK_CTAG_FMTf 2
 #define VLAN_RULE_MASK_SDEIf 3
 #define VLAN_RULE_MASK_SPRIf 4
 #define VLAN_RULE_MASK_STAG_FMTf 5
 #define VLAN_RULE_MASK_SVIDf 6
 #define VLAN_RULE_MASK_CVIDf 7
 #define MISC_RULE_PRIOf 0
 #define MISC_RULE_SRC_PORT_MASKf 1
 #define MISC_RULE_LOGIC_NOTf 2
 #define MISC_RULE_RULE_TYPEf 3
 #define MISC_RULE_IP_FRAGMENTf 4
 #define MISC_RULE_L4_TYPEf 5
 #define MISC_RULE_RSVDf 6
 #define MISC_RULE_PPPOE_FLAGf 7
 #define MISC_RULE_IP_1ST_FRAGMENTf 8
 #define MISC_RULE_IP_OPTIONf 9
 #define MISC_RULE_TCP_FLAGSf 10
 #define MISC_RULE_IP_PROTOCOLf 11
 #define MISC_RULE_TOSf 12
 #define MISC_RULE_L3_TYPEf 13
 #define MISC_RULE_MASK_IP_FRAGMENTf 0
 #define MISC_RULE_MASK_L4_TYPEf 1
 #define MISC_RULE_MASK_RSVDf 2
 #define MISC_RULE_MASK_PPPOE_FLAGf 3
 #define MISC_RULE_MASK_IP_1ST_FRAGMENTf 4
 #define MISC_RULE_MASK_IP_OPTIONf 5
 #define MISC_RULE_MASK_TCP_FLAGSf 6
 #define MISC_RULE_MASK_IP_PROTOCOLf 7
 #define MISC_RULE_MASK_TOSf 8
 #define MISC_RULE_MASK_L3_TYPEf 9
 #define UDF_RULE_PRIOf 0
 #define UDF_RULE_SRC_PORT_MASKf 1
 #define UDF_RULE_LOGIC_NOTf 2
 #define UDF_RULE_RULE_TYPEf 3
 #define UDF_RULE_RSVDf 4
 #define UDF_RULE_IS_IGMPf 5
 #define UDF_RULE_UDF0f 6
 #define UDF_RULE_UDF1f 7
 #define UDF_RULE_MASK_RSVDf 0
 #define UDF_RULE_MASK_IS_IGMPf 1
 #define UDF_RULE_MASK_UDF0f 2
 #define UDF_RULE_MASK_UDF1f 3
 #define IPV6_DA0_RULE_PRIOf 0
 #define IPV6_DA0_RULE_SRC_PORT_MASKf 1
 #define IPV6_DA0_RULE_LOGIC_NOTf 2
 #define IPV6_DA0_RULE_RULE_TYPEf 3
 #define IPV6_DA0_RULE_RSVDf 4
 #define IPV6_DA0_RULE_L4_TYPEf 5
 #define IPV6_DA0_RULE_IPV6_DA0f 6
 #define IPV6_DA0_RULE_MASK_RSVDf 0
 #define IPV6_DA0_RULE_MASK_L4_TYPEf 1
 #define IPV6_DA0_RULE_MASK_IPV6_DA0f 2
 #define IPV6_DA1_RULE_PRIOf 0
 #define IPV6_DA1_RULE_SRC_PORT_MASKf 1
 #define IPV6_DA1_RULE_LOGIC_NOTf 2
 #define IPV6_DA1_RULE_RULE_TYPEf 3
 #define IPV6_DA1_RULE_IP_OPTIONf 4
 #define IPV6_DA1_RULE_L4_TYPEf 5
 #define IPV6_DA1_RULE_IPV6_DA1f 6
 #define IPV6_DA1_RULE_MASK_IP_OPTIONf 0
 #define IPV6_DA1_RULE_MASK_L4_TYPEf 1
 #define IPV6_DA1_RULE_MASK_IPV6_DA1f 2
 #define IPV6_DA2_RULE_PRIOf 0
 #define IPV6_DA2_RULE_SRC_PORT_MASKf 1
 #define IPV6_DA2_RULE_LOGIC_NOTf 2
 #define IPV6_DA2_RULE_RULE_TYPEf 3
 #define IPV6_DA2_RULE_IP_FIRST_FRAGMENTf 4
 #define IPV6_DA2_RULE_L4_TYPEf 5
 #define IPV6_DA2_RULE_IPV6_DA2f 6
 #define IPV6_DA2_RULE_MASK_IP_FIRST_FRAGMENTf 0
 #define IPV6_DA2_RULE_MASK_L4_TYPEf 1
 #define IPV6_DA2_RULE_MASK_IPV6_DA2f 2
 #define IPV6_DA3_RULE_RANGE0_ENf 0
 #define IPV6_DA3_RULE_PRIOf 1
 #define IPV6_DA3_RULE_SRC_PORT_MASKf 2
 #define IPV6_DA3_RULE_LOGIC_NOTf 3
 #define IPV6_DA3_RULE_RULE_TYPEf 4
 #define IPV6_DA3_RULE_IP_FRAGMENTf 5
 #define IPV6_DA3_RULE_L4_TYPEf 6
 #define IPV6_DA3_RULE_IPV6_DA3f 7
 #define IPV6_DA3_RULE_MASK_IP_FRAGMENTf 0
 #define IPV6_DA3_RULE_MASK_L4_TYPEf 1
 #define IPV6_DA3_RULE_MASK_IPV6_DA3f 2
 #define IPV6_SA0_RULE_PRIOf 0
 #define IPV6_SA0_RULE_SRC_PORT_MASKf 1
 #define IPV6_SA0_RULE_LOGIC_NOTf 2
 #define IPV6_SA0_RULE_RULE_TYPEf 3
 #define IPV6_SA0_RULE_RSVDf 4
 #define IPV6_SA0_RULE_L4_TYPEf 5
 #define IPV6_SA0_RULE_IPV6_SA0f 6
 #define IPV6_SA0_RULE_MASK_RSVDf 0
 #define IPV6_SA0_RULE_MASK_L4_TYPEf 1
 #define IPV6_SA0_RULE_MASK_IPV6_SA0f 2
 #define IPV6_SA1_RULE_PRIOf 0
 #define IPV6_SA1_RULE_SRC_PORT_MASKf 1
 #define IPV6_SA1_RULE_LOGIC_NOTf 2
 #define IPV6_SA1_RULE_RULE_TYPEf 3
 #define IPV6_SA1_RULE_IP_OPTIONf 4
 #define IPV6_SA1_RULE_L4_TYPEf 5
 #define IPV6_SA1_RULE_IPV6_SA1f 6
 #define IPV6_SA1_RULE_MASK_IP_OPTIONf 0
 #define IPV6_SA1_RULE_MASK_L4_TYPEf 1
 #define IPV6_SA1_RULE_MASK_IPV6_SA1f 2
 #define IPV6_SA2_RULE_PRIOf 0
 #define IPV6_SA2_RULE_SRC_PORT_MASKf 1
 #define IPV6_SA2_RULE_LOGIC_NOTf 2
 #define IPV6_SA2_RULE_RULE_TYPEf 3
 #define IPV6_SA2_RULE_IP_FIRST_FRAGMENTf 4
 #define IPV6_SA2_RULE_L4_TYPEf 5
 #define IPV6_SA2_RULE_IPV6_SA2f 6
 #define IPV6_SA2_RULE_MASK_IP_FIRST_FRAGMENTf 0
 #define IPV6_SA2_RULE_MASK_L4_TYPEf 1
 #define IPV6_SA2_RULE_MASK_IPV6_SA2f 2
 #define IPV6_SA3_RULE_RANGE0_ENf 0
 #define IPV6_SA3_RULE_PRIOf 1
 #define IPV6_SA3_RULE_SRC_PORT_MASKf 2
 #define IPV6_SA3_RULE_LOGIC_NOTf 3
 #define IPV6_SA3_RULE_RULE_TYPEf 4
 #define IPV6_SA3_RULE_IP_FRAGMENTf 5
 #define IPV6_SA3_RULE_L4_TYPEf 6
 #define IPV6_SA3_RULE_IPV6_SA3f 7
 #define IPV6_SA3_RULE_MASK_IP_FRAGMENTf 0
 #define IPV6_SA3_RULE_MASK_L4_TYPEf 1
 #define IPV6_SA3_RULE_MASK_IPV6_SA3f 2
 #define VID_PRI_DEI_RULE_RANGE1_ENf 0
 #define VID_PRI_DEI_RULE_RANGE0_ENf 1
 #define VID_PRI_DEI_RULE_PRIOf 2
 #define VID_PRI_DEI_RULE_SRC_PORT_MASKf 3
 #define VID_PRI_DEI_RULE_LOGIC_NOTf 4
 #define VID_PRI_DEI_RULE_RULE_TYPEf 5
 #define VID_PRI_DEI_RULE_RSVf 6
 #define VID_PRI_DEI_RULE_CDEIf 7
 #define VID_PRI_DEI_RULE_CPRIf 8
 #define VID_PRI_DEI_RULE_SDEIf 9
 #define VID_PRI_DEI_RULE_SPRIf 10
 #define VID_PRI_DEI_RULE_SVIDf 11
 #define VID_PRI_DEI_RULE_CVIDf 12
 #define VID_PRI_DEI_RULE_MASK_CDEIf 0
 #define VID_PRI_DEI_RULE_MASK_CPRIf 1
 #define VID_PRI_DEI_RULE_MASK_SDEIf 2
 #define VID_PRI_DEI_RULE_MASK_SPRIf 3
 #define VID_PRI_DEI_RULE_MASK_SVIDf 4
 #define VID_PRI_DEI_RULE_MASK_CVIDf 5
 #define ETHER_TYPE_VALUE_RULE_RANGE_ENf 0
 #define ETHER_TYPE_VALUE_RULE_PRIOf 1
 #define ETHER_TYPE_VALUE_RULE_SRC_PORT_MASKf 2
 #define ETHER_TYPE_VALUE_RULE_LOGIC_NOTf 3
 #define ETHER_TYPE_VALUE_RULE_RULE_TYPEf 4
 #define ETHER_TYPE_VALUE_RULE_RSV1f 5
 #define ETHER_TYPE_VALUE_RULE_L4_TYPEf 6
 #define ETHER_TYPE_VALUE_RULE_RSV0f 7
 #define ETHER_TYPE_VALUE_RULE_ETHER_TYPE_VALUEf 8
 #define ETHER_TYPE_VALUE_RULE_MASK_RSV1f 0
 #define ETHER_TYPE_VALUE_RULE_MASK_L4_TYPEf 1
 #define ETHER_TYPE_VALUE_RULE_MASK_RSV0f 2
 #define ETHER_TYPE_VALUE_RULE_MASK_ETHER_TYPE_VALUEf 3
 #define DSCP_TO_INT_PRIO_MAP_INT_PRIOf 0
 #define DSCP_TO_INT_PRIO_MAP_INT_DPf 1
 #define PRI_TO_INT_PRIO_MAP_INT_PRIOf 0
 #define PRI_TO_INT_PRIO_MAP_INT_DPf 1
 #define QOS_PORT_CTRLN_CPRI_MAP_SELf 0
 #define QOS_PORT_CTRLN_SPRI_MAP_SELf 1
 #define QOS_PORT_CTRLN_PORT_INTPRIf 2
 #define QOS_PORT_CTRLN_PORT_INTPRI_ENf 3
 #define QOS_MERGE_PRECEDENCE_CTRLN_PORT_PRI_PRECEDENCEf 0
 #define QOS_MERGE_PRECEDENCE_CTRLN_SPRI2INT_PRI_PRECEDENCEf 1
 #define QOS_MERGE_PRECEDENCE_CTRLN_CPRI2INT_PRI_PRECEDENCEf 2
 #define QOS_MERGE_PRECEDENCE_CTRLN_DSCP2INT_PRI_PRECEDENCEf 3
 #define QOS_MERGE_PRECEDENCE_CTRLN_ACL_INT_PRI_PRECEDENCEf 4
 #define QOS_MERGE_PRECEDENCE_CTRLN_VLAN_INT_PRI_PRECEDENCEf 5
 #define QOS_MERGE_PRECEDENCE_CTRLN_MAC_DA_INT_PRI_PRECEDENCEf 6
 #define QOS_MERGE_PRECEDENCE_CTRLN_MAC_SA_INT_PRI_PRECEDENCEf 7
 #define L2_VLAN_INGRESS_FILTER_EN_IGMP_BYPASS_ENf 0
 #define L2_VLAN_INGRESS_FILTER_EN_FILTER_ENf 1
 #define L2_ARP_BCAST_PER_PORT_CTRL_DROPf 0
 #define L2_ARP_BCAST_PER_PORT_CTRL_COPY_TO_CPUf 1
 #define L2_ND_PER_PORT_CTRL_DROPf 0
 #define L2_ND_PER_PORT_CTRL_COPY_TO_CPUf 1
 #define L2_LLDP_EEE_PER_PORT_CTRL_DROPf 0
 #define L2_LLDP_EEE_PER_PORT_CTRL_COPY_TO_CPUf 1
 #define L2_LLDP_PER_PORT_CTRL_DROPf 0
 #define L2_LLDP_PER_PORT_CTRL_COPY_TO_CPUf 1
 #define L2_PORT_ISOLATION_CTRLN_ISOLATED_PORT_MASKf 0
 #define L2_STP_STATEN_STATEf 0
 #define L2_SRC_MATCH_CTRL_SRC_MATCH_DISCARDf 0
 #define L2_LEARN_PER_PORT_CTRLN_VID_LEARN_MULTI_ENf 0
 #define L2_LEARN_PER_PORT_CTRLN_VID_LEARN_MODEf 1
 #define L2_LEARN_PER_PORT_CTRLN_VID_LEARN_ENf 2
 #define L2_LEARN_PER_PORT_CTRLN_SUSPEND_COPY_ENf 3
 #define L2_LEARN_PER_PORT_CTRLN_SUSPEND_DROP_ENf 4
 #define L2_LEARN_PER_PORT_CTRLN_LEARN_DISABLEf 5
 #define L2_LEARN_PER_PORT_CTRLN_LEARN_LIMIT_ENf 6
 #define L2_LEARN_PER_PORT_CTRLN_LEARN_LIMIT_NUMf 7
 #define L2_LEARN_PER_PORT_CTRLN_LEARN_LIMIT_DROPf 8
 #define L2_LEARN_PER_PORT_CTRLN_LEARN_MODEf 9
 #define L2_PORT_LEARN_MAC_CNTN_MAC_CNTf 0
 #define L2_LEARN_GLOBAL_CTRL_LEARN_MODEf 0
 #define L2_LEARN_GLOBAL_CTRL_GIP_LEARN_OVERWRITE_ALLOWf 1
 #define L2_LEARN_GLOBAL_CTRL_SA_LEARN_OVERWRITE_ALLOWf 2
 #define L2_LEARN_GLOBAL_CTRL_LEARN_LIMIT_ENf 3
 #define L2_LEARN_GLOBAL_CTRL_LEARN_LIMIT_NUMf 4
 #define L2_LEARN_GLOBAL_CTRL_LEARN_LIMIT_DROPf 5
 #define L2_LEARN_MAC_CNT_MAC_CNTf 0
 #define L2_AGING_CTRL_AGING_INTERVALf 0
 #define L2_AGING_PER_PORT_CTRL_AGING_ENf 0
 #define L2_FDB_TBL_OP_DATA_0_MAC_DA_0f 0
 #define L2_FDB_TBL_OP_DATA_1_DMAC_INT_PRI_ENf 0
 #define L2_FDB_TBL_OP_DATA_1_STATUSf 1
 #define L2_FDB_TBL_OP_DATA_1_FIDf 2
 #define L2_FDB_TBL_OP_DATA_1_MAC_DA_1f 3
 #define L2_FDB_TBL_OP_DATA_2_MOVE_AGING_STATUSf 0
 #define L2_FDB_TBL_OP_DATA_2_SMAC_DROPf 1
 #define L2_FDB_TBL_OP_DATA_2_DST_PORT_MASKf 2
 #define L2_FDB_TBL_OP_DATA_2_DMAC_DROPf 3
 #define L2_FDB_TBL_OP_DATA_2_COPY_TO_CPUf 4
 #define L2_FDB_TBL_OP_DATA_2_SMAC_INT_PRI_ENf 5
 #define L2_FDB_TBL_OP_DATA_2_INT_PRIf 6
 #define L2_FDB_TBL_OP_DATA_2_NEW_VIDf 7
 #define L2_FDB_TBL_OP_ENTRY_INDEXf 0
 #define L2_FDB_TBL_OP_OP_MODEf 1
 #define L2_FDB_TBL_OP_FLUSH_MODEf 2
 #define L2_FDB_TBL_OP_FLUSH_STATIC_ENf 3
 #define L2_FDB_TBL_OP_GET_NEXT_TYPEf 4
 #define L2_FDB_TBL_OP_OP_CMDf 5
 #define L2_FDB_TBL_OP_OP_STARTf 6
 #define L2_FDB_TBL_OP_RESULT_OP_DONEf 0
 #define L2_FDB_TBL_OP_RESULT_LOOKUP_FAILf 1
 #define L2_FDB_TBL_OP_RESULT_OVERWRITEf 2
 #define L2_FDB_TBL_OP_RESULT_OP_RESULTf 3
 #define L2_FDB_TBL_OP_RESULT_ENTRY_INDEXf 4
 #define L2_IGMP_STATIC_ROUTER_PORT_MASK_PORT_MASKf 0
 #define L2_IGMP_DYNAMIC_ROUTER_PORT_CTRL_ALLOW_DYNAMIC_PORT_MASKf 0
 #define L2_IGMP_DYNAMIC_ROUTER_PORT_CTRL_TIMER_VALf 1
 #define L2_IGMP_GLOBAL_CTRL_REPORT_LEAVE_ROUTER_FWD_CTRLf 0
 #define L2_IGMP_GLOBAL_CTRL_REPORT_LEAVE_FWDf 1
 #define L2_IGMP_GLOBAL_CTRL_IGMP_FORCE_ROUTER_DSTf 2
 #define L2_IGMP_GLOBAL_CTRL_MLD_OPf 3
 #define L2_IGMP_GLOBAL_CTRL_IGMP_OPf 4
 #define L2_IGMP_GLOBAL_CTRL_FAST_LEAVE_ENf 5
 #define L2_IGMP_GLOBAL_CTRL_BYPASS_IPV6_00XXf 6
 #define L2_IGMP_GLOBAL_CTRL_BYPASS_224_0_0_Xf 7
 #define L2_IGMP_GLOBAL_CTRL_BYPASS_224_0_1_Xf 8
 #define L2_IGMP_GLOBAL_CTRL_BYPASS_239_255_255_Xf 9
 #define L2_IGMP_PER_PORT_CTRL_BYPASS_FLOW_METERf 0
 #define L2_IGMP_PER_PORT_CTRL_BYPASS_PORT_METERf 1
 #define L2_IGMP_PER_PORT_CTRL_BYPASS_STORMf 2
 #define L2_IGMP_PER_PORT_CTRL_ALLOW_LEAVE_PKTf 3
 #define L2_IGMP_PER_PORT_CTRL_ALLOW_REPORT_PKTf 4
 #define L2_IGMP_PER_PORT_CTRL_ALLOW_QUERY_PKTf 5
 #define L2_IGMP_PER_PORT_CTRL_VLAN_LEAKYf 6
 #define L2_IGMP_PER_PORT_CTRL_PORT_ISOLATE_LEAKYf 7
 #define L2_FDB_TBL_OP_DATA_0_DUMMY_MAC_DA_0f 0
 #define L2_FDB_TBL_OP_DATA_1_DUMMY_DMAC_INT_PRI_ENf 0
 #define L2_FDB_TBL_OP_DATA_1_DUMMY_STATUSf 1
 #define L2_FDB_TBL_OP_DATA_1_DUMMY_FIDf 2
 #define L2_FDB_TBL_OP_DATA_1_DUMMY_MAC_DA_1f 3
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_MOVE_AGING_STATUSf 0
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_SMAC_DROPf 1
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_DST_PORT_MASKf 2
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_DMAC_DROPf 3
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_COPY_TO_CPUf 4
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_SMAC_INT_PRI_ENf 5
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_INT_PRIf 6
 #define L2_FDB_TBL_OP_DATA_2_DUMMY_NEW_VIDf 7
 #define L2_IGMP_DYNAMIC_ROUTER_PORT_DUMMY_PORT1f 0
 #define L2_IGMP_DYNAMIC_ROUTER_PORT_DUMMY_PORT0f 1
 #define L2_IGMP_LEARN_CTRL_LIMIT_ENf 0
 #define L2_IGMP_LEARN_CTRL_MAX_GROUP_NUMf 1
 #define L2_IGMP_LEARN_GROUP_CNT_CNTf 0
 #define L2_UNKNOWN_UCAST_FILTER_MASK_UNKNOWN_UCAST_FILTER_MASKf 0
 #define L2_UNKNOWN_MCAST_FILTER_MASK_UNKNOWN_MCAST_FILTER_MASKf 0
 #define L2_MCAST_FILTER_MASK_MCAST_FILTER_MASKf 0
 #define L2_BCAST_FILTER_MASK_BCAST_FILTER_MASKf 0
 #define L2_PORT_VLAN_TRANSPARENT_CTRL_PORTMASKf 0
 #define L2_EGR_VLAN_FILTER_EN_FILTER_ENf 0
 #define L2_DOT1X_CTRL1_DOT1X_ENf 0
 #define L2_DOT1X_CTRL2_MC_RX_BYPASSf 0
 #define L2_DOT1X_CTRL2_BC_RX_BYPASSf 1
 #define L2_DOT1X_CTRL2_MC_TX_BYPASSf 2
 #define L2_DOT1X_CTRL2_BC_TX_BYPASSf 3
 #define L2_DOT1X_CTRL2_RX_PERMIT_PORT_MASKf 4
 #define L2_DOT1X_CTRL2_TX_PERMIT_PORT_MASKf 5
 #define IPMC_LEAKY_CTRL_IPMC_VLAN_LEAKYf 0
 #define IPMC_LEAKY_CTRL_IPMC_PORT_ISOLATION_LEAKYf 1
 #define LINK_AGG_GROUPN_PORT_MASKf 0
 #define LINK_AGG_GROUPN_MEMBER_NUMf 1
 #define LINK_AGG_MEMBERN_PORTf 0
 #define RMA_CTRLN_BYPASS_STORMf 0
 #define RMA_CTRLN_BYPASS_FLOW_METERf 1
 #define RMA_CTRLN_BYPASS_PORT_METERf 2
 #define RMA_CTRLN_DROPf 3
 #define RMA_CTRLN_COPY_TO_CPUf 4
 #define RMA_CTRLN_VLAN_LEAKYf 5
 #define RMA_CTRLN_PORT_ISOLATE_LEAKYf 6
 #define RMA_CTRLN_CPU_CODEf 7
 #define CPU_COPY_DST_CTRL_FORCE_INT_PORTf 0
 #define CPU_COPY_DST_CTRL_TO_INT_CPUf 1
 #define CPU_COPY_DST_CTRL_TO_EXT_CPUf 2
 #define ACL_UNMATCH_PERMIT_ENABLE_CTRL_ENABLEf 0
 #define OAM_MUX_ACT_MUX_ACTf 0
 #define OAM_PAR_ACT_PAR_ACTf 0
 #define OAM_PAR_ACT_BYPASS_IM_AC_ENf 1
 #define CASCADE_CTRL_PORT1f 0
 #define CASCADE_CTRL_PORT0f 1
 #define CASCADE_CTRL_ENf 2
 #define IGMP_ROUTER_PORT_AGING_CTRL_AGING_INTERVALf 0
 #define MULTI_VLAN_TBL_FID1f 0
 #define MULTI_VLAN_TBL_MULTI_EN1f 1
 #define MULTI_VLAN_TBL_FID0f 2
 #define MULTI_VLAN_TBL_MULTI_EN0f 3
 #define L2_UC_UNKNOWN_ACT_CTRL_L2_UC_UNKNOWN_ACTf 0
 #define L2_MC_UNKNOWN_ACT_CTRL_L2_MC_UNKNOWN_DROP_RMABYPASSf 0
 #define L2_MC_UNKNOWN_ACT_CTRL_L2_MC_UNKNOWN_DROP_IGMPBYPASSf 1
 #define L2_MC_UNKNOWN_ACT_CTRL_L2_MC_UNKNOWN_ACTf 2
 #define L2_LAG_LEARN_LIMIT_CTRLN_LEARN_LIMIT_ENf 0
 #define L2_LAG_LEARN_LIMIT_CTRLN_LEARN_LIMIT_NUMf 1
 #define L2_LAG_LEARN_LIMIT_CTRLN_LEARN_LIMIT_DROPf 2
 #define L2_FDB_HW_FLUSH_CTRL_GLOBAL_ENf 0
 #define L2_FDB_HW_FLUSH_CTRL_LAG_CTRL_ENf 1

 #define L2_VLAN_TBL_UNTAG_MEMBER_BITMAPf 0
 #define L2_VLAN_TBL_STP_IDf 1
 #define L2_VLAN_TBL_SVL_ENf 2
 #define L2_VLAN_TBL_FID_1f 3
 #define L2_VLAN_TBL_FID_0f 4
 #define L2_VLAN_TBL_LEARN_DISABLEf 5
 #define L2_VLAN_TBL_INT_PRI_VALIDf 6
 #define L2_VLAN_TBL_INT_PRIf 7
 #define L2_VLAN_TBL_PORT_MEMBER_BITMAPf 8
 #define L2_VLAN_TBL_BYPASS_1X_ACCESS_CONTROLf 9
 #define L2_VLAN_TBL_METER_ENf 10
 #define L2_VLAN_TBL_METER_IDf 11
 #define L2_FDB_TBL_BIN0_MOVE_AGING_STATUSf 0
 #define L2_FDB_TBL_BIN0_SMAC_DROPf 1
 #define L2_FDB_TBL_BIN0_DST_PORT_MASKf 2
 #define L2_FDB_TBL_BIN0_DMAC_DROPf 3
 #define L2_FDB_TBL_BIN0_COPY_TO_CPUf 4
 #define L2_FDB_TBL_BIN0_SMAC_INT_PRI_ENf 5
 #define L2_FDB_TBL_BIN0_INT_PRIf 6
 #define L2_FDB_TBL_BIN0_NEW_VIDf 7
 #define L2_FDB_TBL_BIN0_DMAC_INT_PRI_ENf 8
 #define L2_FDB_TBL_BIN0_STATUSf 9
 #define L2_FDB_TBL_BIN0_FIDf 10
 #define L2_FDB_TBL_BIN0_MAC_DA_1f 11
 #define L2_FDB_TBL_BIN0_MAC_DA_0f 12
 #define ACL_ACTION_TBL_STAG_ASSIGNf 0
 #define ACL_ACTION_TBL_CTAG_ASSIGNf 1
 #define ACL_ACTION_TBL_FWD_DECISION_TYPEf 2
 #define ACL_ACTION_TBL_DEST_PORT_MASKf 3
 #define ACL_ACTION_TBL_FWD_DECISION_ENf 4
 #define ACL_ACTION_TBL_SDEIf 5
 #define ACL_ACTION_TBL_SDEI_REPLACE_ENf 6
 #define ACL_ACTION_TBL_SPRIf 7
 #define ACL_ACTION_TBL_SPRI_REPLACE_ENf 8
 #define ACL_ACTION_TBL_SVID_1f 9
 #define ACL_ACTION_TBL_SVID_0f 10
 #define ACL_ACTION_TBL_SVID_REPLACE_ENf 11
 #define ACL_ACTION_TBL_CDEIf 12
 #define ACL_ACTION_TBL_CDEI_REPLACE_ENf 13
 #define ACL_ACTION_TBL_CPRIf 14
 #define ACL_ACTION_TBL_CPRI_REPLACE_ENf 15
 #define ACL_ACTION_TBL_CVIDf 16
 #define ACL_ACTION_TBL_CVID_REPLACE_ENf 17
 #define ACL_ACTION_TBL_INT_PRI_1f 18
 #define ACL_ACTION_TBL_INT_PRI_0f 19
 #define ACL_ACTION_TBL_INT_PRI_VALIDf 20
 #define ACL_ACTION_TBL_INT_DPf 21
 #define ACL_ACTION_TBL_INT_DP_VALIDf 22
 #define ACL_ACTION_TBL_DSCPf 23
 #define ACL_ACTION_TBL_DSCP_REPLACE_ENf 24
 #define ACL_ACTION_TBL_METER_IDf 25
 #define ACL_ACTION_TBL_METER_ENf 26
 #define ACL_ACTION_TBL_MIRROR_ENf 27
 #define ACL_ACTION_TBL_FLOW_STATS_ENf 28
 #define ACL_ACTION_TBL_FLOW_STATS_PTRf 29
 #define ACL_ACTION_TBL_GPIO_ENf 30
 #define ACL_ACTION_TBL_GPIO_PINf 31
 #define ACL_ACTION_TBL_INTR_ENf 32
 #define PORT_RATE_CTRLN_GAP_VALUEf 0
 #define STORM_CTRL_TIMESLOT_TIMESLOTf 0
 #define METER_TIMESLOT_TIMESLOTf 0
 #define PORT_METER_CTRLN_METER_ENf 0
 #define PORT_METER_CTRLN_METER_IDf 1
 #define STORM_CTRL_MC_TYPE_CTRL_STORM_CTRL_MC_TYPEf 0
 #define STORM_CTRL_CONFIG_TBL_CIRf 0
 #define STORM_CTRL_CONFIG_TBL_CBSf 1
 #define STORM_CTRL_CONFIG_TBL_GAP_INCf 2
 #define STORM_CTRL_CONFIG_TBL_RATE_MODEf 3
 #define STORM_CTRL_CONFIG_TBL_STORM_ENf 4
 #define METER_CONFIG_TBL_METER_ENf 0
 #define METER_CONFIG_TBL_CFf 1
 #define METER_CONFIG_TBL_DROP_COLORf 2
 #define METER_CONFIG_TBL_COLOR_MODEf 3
 #define METER_CONFIG_TBL_TOKEN_UNITf 4
 #define METER_CONFIG_TBL_BYTE_RATE_MODEf 5
 #define METER_CONFIG_TBL_RATE_MODEf 6
 #define METER_CONFIG_TBL_METER_MODEf 7
 #define METER_CONFIG_TBL_CBS_1f 8
 #define METER_CONFIG_TBL_CBS_0f 9
 #define METER_CONFIG_TBL_CIRf 10
 #define METER_CONFIG_TBL_EBS_1f 11
 #define METER_CONFIG_TBL_EBS_0f 12
 #define METER_CONFIG_TBL_EIRf 13
 #define FLOW_STATS_TBL_CNT1f 0
 #define FLOW_STATS_TBL_CNT0f 1
 #define FLOW_STATS_CFG_TBL_ENf 0
 #define FLOW_STATS_CFG_TBL_MODEf 1
 #define FLOW_STATS_CFG_TBL_SELf 2
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_7_TO_QIDf 0
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_6_TO_QIDf 1
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_5_TO_QIDf 2
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_4_TO_QIDf 3
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_3_TO_QIDf 4
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_2_TO_QIDf 5
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_1_TO_QIDf 6
 #define INT_PRIO_TO_UCAST_QID_MAPN_PRIO_0_TO_QIDf 7
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_7_TO_QIDf 0
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_6_TO_QIDf 1
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_5_TO_QIDf 2
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_4_TO_QIDf 3
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_3_TO_QIDf 4
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_2_TO_QIDf 5
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_1_TO_QIDf 6
 #define INT_PRIO_TO_MCAST_QID_MAPN_PRIO_0_TO_QIDf 7
 #define MIRROR_CTRL_INGR_MIRROR_ENf 0
 #define MIRROR_CTRL_EGR_MIRROR_ENf 1
 #define MIRROR_CTRL_MIRROR_PORTf 2
 #define MIRROR_QOS_CTRL_INGR_MIRROR_INT_PRIO_VALIDf 0
 #define MIRROR_QOS_CTRL_INGR_MIRROR_INT_PRIOf 1
 #define MIRROR_QOS_CTRL_EGR_MIRROR_INT_PRIO_VALIDf 2
 #define MIRROR_QOS_CTRL_EGR_MIRROR_INT_PRIOf 3
 #define FLUSH_CFG_FLUSH_REQf 0
 #define FLUSH_CFG_FLUSH_DONEf 1
 #define FLUSH_CFG_FLUSH_QIDf 2
 #define OQ_ENQ_DIS_TBL_ENQ_DISf 0
 #define EGR_PORT_CTRLN_CFI_REMARK_ENf 0
 #define EGR_PORT_CTRLN_DEI_REMARK_ENf 1
 #define EGR_PORT_CTRLN_DSCP_REMARK_ENf 2
 #define EGR_PORT_CTRLN_CPRIO_REMARK_ENf 3
 #define EGR_PORT_CTRLN_SPRIO_REMARK_ENf 4
 #define EGR_PORT_CTRLN_CTAG_TPID_SELf 5
 #define EGR_PORT_CTRLN_STAG_TPID_SELf 6
 #define EGR_PORT_CTRLN_CPRIO_REMARK_SELf 7
 #define EGR_PORT_CTRLN_SPRIO_REMARK_SELf 8
 #define EGR_PORT_VLAN_CTRLN_STAG_KEEP_MODEf 0
 #define EGR_PORT_VLAN_CTRLN_CTAG_KEEP_MODEf 1
 #define EGR_PORT_VLAN_CTRLN_STAG_MODEf 2
 #define EGR_PORT_VLAN_CTRLN_DEFAULT_SVIDf 3
 #define EGR_PORT_VLAN_CTRLN_CTAG_MODEf 4
 #define EGR_PORT_VLAN_CTRLN_DEFAULT_CVIDf 5
 #define EGR_DSCP_REMARKN_INT_PRIO_TO_DSCPf 0
 #define EGR_PRIO_REMARKN_INT_PRIO_TO_PRIOf 0
 #define EGR_PRIO_REMARKN_INT_PRIO_TO_DEIf 1
 #define EGR_TPID_PROFILE_TPIDf 0
 #define EGR_VLAN_TRANS_RULE_CTRLN_PKT_STAG_INCLf 0
 #define EGR_VLAN_TRANS_RULE_CTRLN_PKT_CTAG_INCLf 1
 #define EGR_VLAN_TRANS_RULE_CTRLN_VID0f 2
 #define EGR_VLAN_TRANS_RULE_CTRLN_PORT_MASKf 3
 #define EGR_VLAN_TRANS_RULE_CTRLN_MVR_INCLf 4
 #define EGR_VLAN_TRANS_RULE_CTRLN_SVID_INCLf 5
 #define EGR_VLAN_TRANS_RULE_CTRLN_CVID_INCLf 6
 #define EGR_VLAN_TRANS_RULE_CTRLN_VALIDf 7
 #define EGR_VLAN_TRANS_RULE_CTRL1N_VID2f 0
 #define EGR_VLAN_TRANS_RULE_CTRL1N_VID1f 1
 #define EGR_VLAN_TRANS_RULE_CTRL1N_VID_RANGE_TYPEf 2
 #define EGR_VLAN_TRANS_DATA_CTRLN_CVIDf 0
 #define EGR_VLAN_TRANS_DATA_CTRLN_SVIDf 1
 #define EGR_VLAN_TRANS_DATA_CTRLN_CVID_ENf 2
 #define EGR_VLAN_TRANS_DATA_CTRLN_SVID_ENf 3
 #define EGR_VLAN_TAG_TRANSPARENT_CTRL_STAG_KEEP_SRCPORT_MASKf 0
 #define EGR_VLAN_TAG_TRANSPARENT_CTRL_CTAG_KEEP_SRCPORT_MASKf 1
 #define EGR_VLAN_TAG_TRANSPARENT_CTRL_STAG_TRANSPARENT_ENf 2
 #define EGR_VLAN_TAG_TRANSPARENT_CTRL_CTAG_TRANSPARENT_ENf 3
 #define QSCH_SHP_SLOT_TIME_CFG_QSCH_SHP_SLOT_TIMEf 0
 #define PSCH_SHP_SLOT_TIME_CFG_PSCH_SHP_SLOT_TIMEf 0
 #define QSCH_FLOW_MAP_TBL_E_DWRR_WEIGHTf 0
 #define QSCH_FLOW_MAP_TBL_C_DWRR_WEIGHTf 1
 #define QSCH_FLOW_MAP_TBL_E_PRIf 2
 #define QSCH_FLOW_MAP_TBL_C_PRIf 3
 #define QSCH_C_DWRR_CFG_TBL_DWRR_MODEf 0
 #define QSCH_E_DWRR_CFG_TBL_DWRR_MODEf 0
 #define QSCH_SHP_CFG_TBL_CFf 0
 #define QSCH_SHP_CFG_TBL_E_SHAPER_ENf 1
 #define QSCH_SHP_CFG_TBL_C_SHAPER_ENf 2
 #define QSCH_SHP_CFG_TBL_SHAPER_MODEf 3
 #define QSCH_SHP_CFG_TBL_TOKEN_LEVELf 4
 #define QSCH_SHP_CFG_TBL_EBSf 5
 #define QSCH_SHP_CFG_TBL_EIRf 6
 #define QSCH_SHP_CFG_TBL_CBSf 7
 #define QSCH_SHP_CFG_TBL_CIRf 8
 #define QSCH_METER_CFG_TBL_METER_LENGTHf 0
 #define PSCH_SHP_CFG_TBL_C_SHAPER_ENf 0
 #define PSCH_SHP_CFG_TBL_SHAPER_MODEf 1
 #define PSCH_SHP_CFG_TBL_TOKEN_LEVELf 2
 #define PSCH_SHP_CFG_TBL_CBSf 3
 #define PSCH_SHP_CFG_TBL_CIRf 4
 #define PSCH_METER_CFG_TBL_METER_LENGTHf 0

 extern const field_id_t global_ctrl0m_field[] ;
 extern const field_id_t global_ctrl1m_field[] ;
 extern const field_id_t ext_cpu_port_ctrlm_field[] ;
 extern const field_id_t cpu_tag_tpidm_field[] ;
 extern const field_id_t look_up_vlan_selm_field[] ;
 extern const field_id_t intr_maskm_field[] ;
 extern const field_id_t intr_statusm_field[] ;
 extern const field_id_t global_mac_addr0m_field[] ;
 extern const field_id_t global_mac_addr1m_field[] ;
 extern const field_id_t eee_ctrlm_field[] ;
 extern const field_id_t sg_phym_field[] ;
 extern const field_id_t port_ctrlm_field[] ;
 extern const field_id_t port_statusm_field[] ;
 extern const field_id_t loop_detect_top_ctrlm_field[] ;
 extern const field_id_t pon_strap_enm_field[] ;
 extern const field_id_t pon_strap_valm_field[] ;
 extern const field_id_t pon_strapm_field[] ;
 extern const field_id_t mdio_pollingm_field[] ;
 extern const field_id_t oam_dying_gaspm_field[] ;
 extern const field_id_t acl2gpiom_field[] ;
 extern const field_id_t extif0_modem_field[] ;
 extern const field_id_t extif0_mode2m_field[] ;
 extern const field_id_t extif1_modem_field[] ;
 extern const field_id_t extif1_mode2m_field[] ;
 extern const field_id_t tpid_profile0m_field[] ;
 extern const field_id_t tpid_profile1m_field[] ;
 extern const field_id_t parser_port_ctrlnm_field[] ;
 extern const field_id_t link_agg_hash_ctrlm_field[] ;
 extern const field_id_t udf_ctrlnm_field[] ;
 extern const field_id_t parser_erp_ouim_field[] ;
 extern const field_id_t parser_erp_ethtypem_field[] ;
 extern const field_id_t parser_erp_udf_ctrlm_field[] ;
 extern const field_id_t parser_erp_udfnm_field[] ;
 extern const field_id_t dos_tcp_flags0m_field[] ;
 extern const field_id_t dos_tcp_flags1m_field[] ;
 extern const field_id_t dos_tcp_flags2m_field[] ;
 extern const field_id_t dos_tcp_flags3m_field[] ;
 extern const field_id_t dos_tcp_flags4m_field[] ;
 extern const field_id_t dos_tcp_flags5m_field[] ;
 extern const field_id_t dos_ctrlm_field[] ;
 extern const field_id_t dos_large_icmp_ctrlm_field[] ;
 extern const field_id_t oam_en_ctrlm_field[] ;
 extern const field_id_t wol_ctrlm_field[] ;
 extern const field_id_t dos_ctrl1m_field[] ;
 extern const field_id_t protocol_based_vlannm_field[] ;
 extern const field_id_t port_vlan_ctrlnm_field[] ;
 extern const field_id_t port_vlan_ctrl1nm_field[] ;
 extern const field_id_t vlan_trans_untag_vid_mode_ctrlm_field[] ;
 extern const field_id_t vlan_range_profilenm_field[] ;
 extern const field_id_t protocol_based_vlan_data_tblm_field[] ;
 extern const field_id_t vlan_xlate_action_tblm_field[] ;
 extern const field_id_t vlan_xlate_tblm_field[] ;
 extern const field_id_t acl_blk_keep_ctrlm_field[] ;
 extern const field_id_t acl_port_ctrlm_field[] ;
 extern const field_id_t acl_blk_cmdm_field[] ;
 extern const field_id_t rule_ext_ctrlm_field[] ;
 extern const field_id_t acl_rule_bin0m_field[] ;
 extern const field_id_t acl_rule_bin1m_field[] ;
 extern const field_id_t acl_rule_bin2m_field[] ;
 extern const field_id_t acl_rule_bin3m_field[] ;
 extern const field_id_t acl_rule_bin4m_field[] ;
 extern const field_id_t acl_rule_bin5m_field[] ;
 extern const field_id_t acl_rule_bin6m_field[] ;
 extern const field_id_t acl_rule_bin7m_field[] ;
 extern const field_id_t acl_rule_mask_bin0m_field[] ;
 extern const field_id_t acl_rule_mask_bin1m_field[] ;
 extern const field_id_t acl_rule_mask_bin2m_field[] ;
 extern const field_id_t acl_rule_mask_bin3m_field[] ;
 extern const field_id_t acl_rule_mask_bin4m_field[] ;
 extern const field_id_t acl_rule_mask_bin5m_field[] ;
 extern const field_id_t acl_rule_mask_bin6m_field[] ;
 extern const field_id_t acl_rule_mask_bin7m_field[] ;
 extern const field_id_t mac_da0_rulem_field[] ;
 extern const field_id_t mac_da0_rule_maskm_field[] ;
 extern const field_id_t mac_da1_sa1_rulem_field[] ;
 extern const field_id_t mac_da1_sa1_rule_maskm_field[] ;
 extern const field_id_t mac_sa0_rulem_field[] ;
 extern const field_id_t mac_sa0_rule_maskm_field[] ;
 extern const field_id_t ipv4_da_rulem_field[] ;
 extern const field_id_t ipv4_da_rule_maskm_field[] ;
 extern const field_id_t ipv4_sa_rulem_field[] ;
 extern const field_id_t ipv4_sa_rule_maskm_field[] ;
 extern const field_id_t l4_port_rulem_field[] ;
 extern const field_id_t l4_port_rule_maskm_field[] ;
 extern const field_id_t vlan_rulem_field[] ;
 extern const field_id_t vlan_rule_maskm_field[] ;
 extern const field_id_t misc_rulem_field[] ;
 extern const field_id_t misc_rule_maskm_field[] ;
 extern const field_id_t udf_rulem_field[] ;
 extern const field_id_t udf_rule_maskm_field[] ;
 extern const field_id_t ipv6_da0_rulem_field[] ;
 extern const field_id_t ipv6_da0_rule_maskm_field[] ;
 extern const field_id_t ipv6_da1_rulem_field[] ;
 extern const field_id_t ipv6_da1_rule_maskm_field[] ;
 extern const field_id_t ipv6_da2_rulem_field[] ;
 extern const field_id_t ipv6_da2_rule_maskm_field[] ;
 extern const field_id_t ipv6_da3_rulem_field[] ;
 extern const field_id_t ipv6_da3_rule_maskm_field[] ;
 extern const field_id_t ipv6_sa0_rulem_field[] ;
 extern const field_id_t ipv6_sa0_rule_maskm_field[] ;
 extern const field_id_t ipv6_sa1_rulem_field[] ;
 extern const field_id_t ipv6_sa1_rule_maskm_field[] ;
 extern const field_id_t ipv6_sa2_rulem_field[] ;
 extern const field_id_t ipv6_sa2_rule_maskm_field[] ;
 extern const field_id_t ipv6_sa3_rulem_field[] ;
 extern const field_id_t ipv6_sa3_rule_maskm_field[] ;
 extern const field_id_t vid_pri_dei_rulem_field[] ;
 extern const field_id_t vid_pri_dei_rule_maskm_field[] ;
 extern const field_id_t ether_type_value_rulem_field[] ;
 extern const field_id_t ether_type_value_rule_maskm_field[] ;
 extern const field_id_t dscp_to_int_prio_mapm_field[] ;
 extern const field_id_t pri_to_int_prio_mapm_field[] ;
 extern const field_id_t qos_port_ctrlnm_field[] ;
 extern const field_id_t qos_merge_precedence_ctrlnm_field[] ;
 extern const field_id_t hdr_err_actionm_field[] ;
 extern const field_id_t l2_vlan_ingress_filter_enm_field[] ;
 extern const field_id_t l2_arp_bcast_per_port_ctrlm_field[] ;
 extern const field_id_t l2_nd_per_port_ctrlm_field[] ;
 extern const field_id_t l2_lldp_eee_per_port_ctrlm_field[] ;
 extern const field_id_t l2_lldp_per_port_ctrlm_field[] ;
 extern const field_id_t l2_port_isolation_ctrlnm_field[] ;
 extern const field_id_t l2_erp_per_port_ctrlm_field[] ;
 extern const field_id_t l2_stp_statenm_field[] ;
 extern const field_id_t l2_src_match_ctrlm_field[] ;
 extern const field_id_t l2_learn_per_port_ctrlnm_field[] ;
 extern const field_id_t l2_station_move_ctrl0m_field[] ;
 extern const field_id_t l2_station_move_ctrl1m_field[] ;
 extern const field_id_t l2_port_learn_mac_cntnm_field[] ;
 extern const field_id_t l2_learn_global_ctrlm_field[] ;
 extern const field_id_t l2_learn_mac_cntm_field[] ;
 extern const field_id_t l2_aging_ctrlm_field[] ;
 extern const field_id_t l2_aging_per_port_ctrlm_field[] ;
 extern const field_id_t l2_fdb_tbl_op_data_0m_field[] ;
 extern const field_id_t l2_fdb_tbl_op_data_1m_field[] ;
 extern const field_id_t l2_fdb_tbl_op_data_2m_field[] ;
 extern const field_id_t l2_fdb_tbl_opm_field[] ;
 extern const field_id_t l2_fdb_tbl_op_resultm_field[] ;
 extern const field_id_t l2_igmp_static_router_port_maskm_field[] ;
 extern const field_id_t l2_igmp_dynamic_router_port_ctrlm_field[] ;
 extern const field_id_t l2_igmp_dynamic_router_portm_field[] ;
 extern const field_id_t l2_igmp_dynamic_router_port0_timerm_field[] ;
 extern const field_id_t l2_igmp_dynamic_router_port1_timerm_field[] ;
 extern const field_id_t l2_igmp_global_ctrlm_field[] ;
 extern const field_id_t l2_igmp_per_port_ctrlm_field[] ;
 extern const field_id_t l2_fdb_tbl_op_data_0_dummym_field[] ;
 extern const field_id_t l2_fdb_tbl_op_data_1_dummym_field[] ;
 extern const field_id_t l2_fdb_tbl_op_data_2_dummym_field[] ;
 extern const field_id_t l2_igmp_dynamic_router_port_dummym_field[] ;
 extern const field_id_t l2_igmp_dynamic_router_port0_timer_dummym_field[] ;
 extern const field_id_t l2_igmp_dynamic_router_port1_timer_dummym_field[] ;
 extern const field_id_t l2_igmp_learn_ctrlm_field[] ;
 extern const field_id_t l2_igmp_learn_group_cntm_field[] ;
 extern const field_id_t l2_unknown_ucast_filter_maskm_field[] ;
 extern const field_id_t l2_unknown_mcast_filter_maskm_field[] ;
 extern const field_id_t l2_mcast_filter_maskm_field[] ;
 extern const field_id_t l2_bcast_filter_maskm_field[] ;
 extern const field_id_t l2_port_vlan_transparent_ctrlm_field[] ;
 extern const field_id_t l2_egr_vlan_filter_enm_field[] ;
 extern const field_id_t l2_dot1x_ctrl1m_field[] ;
 extern const field_id_t l2_dot1x_ctrl2m_field[] ;
 extern const field_id_t ipmc_leaky_ctrlm_field[] ;
 extern const field_id_t link_agg_groupnm_field[] ;
 extern const field_id_t link_agg_membernm_field[] ;
 extern const field_id_t rma_ctrlnm_field[] ;
 extern const field_id_t cpu_copy_dst_ctrlm_field[] ;
 extern const field_id_t acl_unmatch_permit_enable_ctrlm_field[] ;
 extern const field_id_t oam_mux_actm_field[] ;
 extern const field_id_t oam_par_actm_field[] ;
 extern const field_id_t cascade_ctrlm_field[] ;
 extern const field_id_t loop_detect_act_ctrlm_field[] ;
 extern const field_id_t igmp_router_port_aging_ctrlm_field[] ;
 extern const field_id_t multi_vlan_tblm_field[] ;
 extern const field_id_t l2_learn_clear_opm_field[] ;
 extern const field_id_t l2_uc_unknown_act_ctrlm_field[] ;
 extern const field_id_t l2_mc_unknown_act_ctrlm_field[] ;
 extern const field_id_t l2_lag_learn_limit_ctrlnm_field[] ;
 extern const field_id_t l2_loop_detect_flagm_field[] ;
 extern const field_id_t l2_loop_detect_flag_dummym_field[] ;
 extern const field_id_t l2_loop_detect_timerm_field[] ;
 extern const field_id_t l2_arp_bcast_per_port_ctrl1m_field[] ;
 extern const field_id_t l2_nd_per_port_ctrl1m_field[] ;
 extern const field_id_t l2_lldp_eee_per_port_ctrl1m_field[] ;
 extern const field_id_t l2_lldp_per_port_ctrl1m_field[] ;
 extern const field_id_t l2_arp_bcast_nd_per_port_ctrl2m_field[] ;
 extern const field_id_t l2_lldp_eee_per_port_ctrl2m_field[] ;
 extern const field_id_t l2_fdb_hw_flush_ctrlm_field[] ;
 extern const field_id_t l2_uni_que_ctrlm_field[] ;
 extern const field_id_t l2_vlan_tblm_field[] ;
 extern const field_id_t l2_fdb_tbl_bin0m_field[] ;
 extern const field_id_t l2_fdb_tbl_bin1m_field[] ;
 extern const field_id_t l2_fdb_tbl_bin2m_field[] ;
 extern const field_id_t l2_fdb_tbl_bin3m_field[] ;
 extern const field_id_t l2_fdb_tbl_bin4m_field[] ;
 extern const field_id_t l2_fdb_tbl_bin5m_field[] ;
 extern const field_id_t l2_fdb_tbl_bin6m_field[] ;
 extern const field_id_t l2_fdb_tbl_bin7m_field[] ;
 extern const field_id_t acl_action_tblm_field[] ;
 extern const field_id_t port_rate_ctrlnm_field[] ;
 extern const field_id_t storm_ctrl_timeslotm_field[] ;
 extern const field_id_t meter_timeslotm_field[] ;
 extern const field_id_t port_meter_ctrlnm_field[] ;
 extern const field_id_t storm_ctrl_mc_type_ctrlm_field[] ;
 extern const field_id_t drop_event_logm_field[] ;
 extern const field_id_t stats_offsetm_field[] ;
 extern const field_id_t storm_ctrl_config_tblm_field[] ;
 extern const field_id_t storm_ctrl_cnt_tblm_field[] ;
 extern const field_id_t meter_config_tblm_field[] ;
 extern const field_id_t meter_token_tblm_field[] ;
 extern const field_id_t flow_stats_tblm_field[] ;
 extern const field_id_t flow_stats_cfg_tblm_field[] ;
 extern const field_id_t cpu_code_to_cpu_prio_mapnm_field[] ;
 extern const field_id_t int_prio_to_ucast_qid_mapnm_field[] ;
 extern const field_id_t int_prio_to_mcast_qid_mapnm_field[] ;
 extern const field_id_t mirror_ctrlm_field[] ;
 extern const field_id_t mirror_qos_ctrlm_field[] ;
 extern const field_id_t flush_cfgm_field[] ;
 extern const field_id_t oq_enq_dis_tblm_field[] ;
 extern const field_id_t egr_port_ctrlnm_field[] ;
 extern const field_id_t egr_port_vlan_ctrlnm_field[] ;
 extern const field_id_t egr_dscp_remarknm_field[] ;
 extern const field_id_t egr_prio_remarknm_field[] ;
 extern const field_id_t egr_tpid_profilem_field[] ;
 extern const field_id_t egr_vlan_trans_rule_ctrlnm_field[] ;
 extern const field_id_t egr_vlan_trans_rule_ctrl1nm_field[] ;
 extern const field_id_t egr_vlan_trans_data_ctrlnm_field[] ;
 extern const field_id_t egr_vlan_tag_transparent_ctrlm_field[] ;
 extern const field_id_t cpu_pkt_bypassedit_ctrlm_field[] ;
 extern const field_id_t ipg_pre_len_cfgm_field[] ;
 extern const field_id_t qsch_shp_slot_time_cfgm_field[] ;
 extern const field_id_t psch_shp_slot_time_cfgm_field[] ;
 extern const field_id_t qsch_flow_map_tblm_field[] ;
 extern const field_id_t qsch_c_dwrr_cfg_tblm_field[] ;
 extern const field_id_t qsch_e_dwrr_cfg_tblm_field[] ;
 extern const field_id_t qsch_shp_cfg_tblm_field[] ;
 extern const field_id_t qsch_meter_cfg_tblm_field[] ;
 extern const field_id_t psch_shp_cfg_tblm_field[] ;
 extern const field_id_t psch_meter_cfg_tblm_field[] ;
#endif
