//reg_pinmux.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_PINMUX_H__
#define __JL_REG_PINMUX_H__

#include <jl_types.h>

#define PINMUX_BASE                                                                  ((jl_uint32)0x01200000U)
#define PINMUX_BLOCK_SIZE                                                            ((jl_uint32)0x00000100U)

#define PIN_MUX_0_OFFSET                                                             ((jl_uint32)0x00000000U)
#define PIN_MUX_0_NUM                                                                ((jl_uint32)0x00000001U)
typedef union PIN_MUX_0_u {
    struct {
        jl_uint32 p8_mii_mode:1;                                            //[ 0: 0]
        jl_uint32 p8_mii_phy_mode:1;                                        //[ 1: 1]
        jl_uint32 p9_rmii_refclk_local:1;                                   //[ 2: 2]
        jl_uint32 p8_rmii_refclk_local:1;                                   //[ 3: 3]
        jl_uint32 sel_sleep_wake:1;                                         //[ 4: 4]
        jl_uint32 sel_sleep_wake_mode1:1;                                   //[ 5: 5]
        jl_uint32 sel_loop_ind:1;                                           //[ 6: 6]
        jl_uint32 p0_led0_sel:1;                                            //[ 7: 7]
        jl_uint32 p1_led0_sel:1;                                            //[ 8: 8]
        jl_uint32 p2_led0_sel:1;                                            //[ 9: 9]
        jl_uint32 p3_led0_sel:1;                                            //[10:10]
        jl_uint32 p4_led0_sel:1;                                            //[11:11]
        jl_uint32 p5_led0_sel:1;                                            //[12:12]
        jl_uint32 p6_led0_sel:1;                                            //[13:13]
        jl_uint32 p7_led0_sel:1;                                            //[14:14]
        jl_uint32 p0_led1_sel:1;                                            //[15:15]
    } bf;
    jl_uint32 val[1];
} PIN_MUX_0_t;

#define PIN_MUX_1_OFFSET                                                             ((jl_uint32)0x00000001U)
#define PIN_MUX_1_NUM                                                                ((jl_uint32)0x00000001U)
typedef union PIN_MUX_1_u {
    struct {
        jl_uint32 p1_led1_sel:1;                                            //[ 0: 0]
        jl_uint32 p2_led1_sel:1;                                            //[ 1: 1]
        jl_uint32 p3_led1_sel:1;                                            //[ 2: 2]
        jl_uint32 p4_led1_sel:1;                                            //[ 3: 3]
        jl_uint32 p5_led1_sel:1;                                            //[ 4: 4]
        jl_uint32 p6_led1_sel:1;                                            //[ 5: 5]
        jl_uint32 p9_rmii_mode:1;                                           //[ 6: 6]
        jl_uint32 p8_rmii_mode:1;                                           //[ 7: 7]
        jl_uint32 sel_swc_debug:1;                                          //[ 8: 8]
        jl_uint32 sel_phy_dbg_out_local_clk:1;                              //[ 9: 9]
        jl_uint32 sel_phy_dbg_out:1;                                        //[10:10]
        jl_uint32 sel_intn:1;                                               //[11:11]
        jl_uint32 sel_i2c_mode:1;                                           //[12:12]
        jl_uint32 sel_smi_mode:1;                                           //[13:13]
        jl_uint32 p8_mii_mac_mode:1;                                        //[14:14]
        jl_uint32 p8_rmii_refclk_extenal:1;                                 //[15:15]
    } bf;
    jl_uint32 val[1];
} PIN_MUX_1_t;

#define PIN_MUX_2_OFFSET                                                             ((jl_uint32)0x00000002U)
#define PIN_MUX_2_NUM                                                                ((jl_uint32)0x00000001U)
typedef union PIN_MUX_2_u {
    struct {
        jl_uint32 p9_rmii_refclk_extenal:1;                                 //[ 0: 0]
        jl_uint32 sel_p8_link_stat:1;                                       //[ 1: 1]
        jl_uint32 sel_p9_link_stat:1;                                       //[ 2: 2]
        jl_uint32 sel_phy_dbg_out_ext_clk:1;                                //[ 3: 3]
        jl_uint32 sel_p8_dup_sta:1;                                         //[ 4: 4]
        jl_uint32 sel_p8_spd_sta:1;                                         //[ 5: 5]
        jl_uint32 sel_p8_if_mode:1;                                         //[ 6: 6]
        jl_uint32 sel_p8_if_sel:1;                                          //[ 7: 7]
        jl_uint32 sel_en_led1:1;                                            //[ 8: 8]
        jl_uint32 sel_dis_loop_ind:1;                                       //[ 9: 9]
        jl_uint32 sel_dis_eee:1;                                            //[10:10]
        jl_uint32 sel_led_mode:1;                                           //[11:11]
        jl_uint32 sel_rma_mode:1;                                           //[12:12]
        jl_uint32 sel_unknow_multi:1;                                       //[13:13]
        jl_uint32 sel_dis_rst_blnk:1;                                       //[14:14]
        jl_uint32 sel_p8_fctrl_sta:1;                                       //[15:15]
    } bf;
    jl_uint32 val[1];
} PIN_MUX_2_t;

#define PIN_MUX_3_OFFSET                                                             ((jl_uint32)0x00000003U)
#define PIN_MUX_3_NUM                                                                ((jl_uint32)0x00000001U)
typedef union PIN_MUX_3_u {
    struct {
        jl_uint32 sel_p9_dup_sta:1;                                         //[ 0: 0]
        jl_uint32 sel_p9_spd_sta:1;                                         //[ 1: 1]
        jl_uint32 sel_p9_if_sel:1;                                          //[ 2: 2]
        jl_uint32 sel_p9_fctrl_sta:1;                                       //[ 3: 3]
        jl_uint32 sel_p9_if_mode:1;                                         //[ 4: 4]
        jl_uint32 sel_gpio19_rsv:1;                                         //[ 5: 5]
        jl_uint32 sel_gpio20_rsv:1;                                         //[ 6: 6]
        jl_uint32 sel_gpio21_rsv:1;                                         //[ 7: 7]
        jl_uint32 sel_gpio22_rsv:1;                                         //[ 8: 8]
        jl_uint32 sel_gpio23_rsv:1;                                         //[ 9: 9]
        jl_uint32 sel_gpio24_rsv:1;                                         //[10:10]
        jl_uint32 sel_gpio25_rsv:1;                                         //[11:11]
        jl_uint32 pin_dbg_mode:1;                                           //[12:12]
    } bf;
    jl_uint32 val[1];
} PIN_MUX_3_t;

#endif /* __JL_REG_PINMUX_H__ */

