//reg_fephy.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_FEPHY_H__
#define __JL_REG_FEPHY_H__

#include <jl_types.h>
#include "jl51xx/jl51xx_drv_switch.h"

#define FEPHY7_BASE                                                                  ((jl_uint32)0x02100000U)
#define FEPHY7_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)
#define FEPHY6_BASE                                                                  ((jl_uint32)0x01F00000U)
#define FEPHY6_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)
#define FEPHY5_BASE                                                                  ((jl_uint32)0x01D00000U)
#define FEPHY5_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)
#define FEPHY4_BASE                                                                  ((jl_uint32)0x01B00000U)
#define FEPHY4_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)
#define FEPHY3_BASE                                                                  ((jl_uint32)0x01900000U)
#define FEPHY3_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)
#define FEPHY2_BASE                                                                  ((jl_uint32)0x01700000U)
#define FEPHY2_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)
#define FEPHY1_BASE                                                                  ((jl_uint32)0x01500000U)
#define FEPHY1_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)
#define FEPHY0_BASE                                                                  ((jl_uint32)0x01300000U)
#define FEPHY0_BLOCK_SIZE                                                            ((jl_uint32)0x00200000U)

#define FEPHY0_TXISOEL_OFFSET                                                        ((jl_uint32)0x000000F4U)
#define FEPHY0_TXISOEL_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_TXISOEL_u {
    struct {
        jl_uint32 link_status_realtime:1;                                   //[ 0: 0]
        jl_uint32 ethercat_mode:1;                                          //[ 1: 1]
        jl_uint32 rsvd:13;                                                  //[14: 2]
        jl_uint32 tx_isolate_en:1;                                          //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_TXISOEL_t;

#define FEPHY0_LSI_OFFSET                                                            ((jl_uint32)0x000000F9U)
#define FEPHY0_LSI_NUM                                                               ((jl_uint32)0x00000001U)
typedef union FEPHY0_LSI_u {
    struct {
        jl_uint32 link_status_ll:1;                                         //[ 0: 0]
        jl_uint32 speed_internal:1;                                         //[ 1: 1]
        jl_uint32 duplex_internal:1;                                        //[ 2: 2]
    } bf;
    jl_uint32 val[1];
} FEPHY0_LSI_t;

#define FEPHY0_RSVD0_OFFSET                                                          ((jl_uint32)0x000000FAU)
#define FEPHY0_RSVD0_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_RSVD0_u {
    struct {
        jl_uint32 top_rsvd:16;                                              //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_RSVD0_t;

#define FEPHY0_TX1_OFFSET                                                            ((jl_uint32)0x00000310U)
#define FEPHY0_TX1_NUM                                                               ((jl_uint32)0x00000001U)
typedef union FEPHY0_TX1_u {
    struct {
        jl_uint32 tx_cbuf_gc:3;                                             //[ 2: 0]
        jl_uint32 tx_cbuf_ccen:1;                                           //[ 3: 3]
        jl_uint32 tx_cbuf_cal:4;                                            //[ 7: 4]
        jl_uint32 tx_cbuf_bm:2;                                             //[ 9: 8]
        jl_uint32 tx_amp_mode:2;                                            //[11:10]
        jl_uint32 tx_amp_cfen:1;                                            //[12:12]
        jl_uint32 tx_amp_bm:2;                                              //[14:13]
    } bf;
    jl_uint32 val[1];
} FEPHY0_TX1_t;

#define FEPHY0_PITX2_OFFSET                                                          ((jl_uint32)0x00000313U)
#define FEPHY0_PITX2_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_PITX2_u {
    struct {
        jl_uint32 tx_rsvd:3;                                                //[ 2: 0]
        jl_uint32 tx_echo_en:1;                                             //[ 3: 3]
        jl_uint32 tx_dac_srn:1;                                             //[ 4: 4]
        jl_uint32 tx_dac_currx2:1;                                          //[ 5: 5]
        jl_uint32 tx_dac_bm:4;                                              //[ 9: 6]
        jl_uint32 tx_cmfb_en:2;                                             //[11:10]
        jl_uint32 tx_cbuf_gcaux:3;                                          //[14:12]
        jl_uint32 cktree_selb_10base:1;                                     //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PITX2_t;

#define FEPHY0_PU_OFFSET                                                             ((jl_uint32)0x00000314U)
#define FEPHY0_PU_NUM                                                                ((jl_uint32)0x00000001U)
typedef union FEPHY0_PU_u {
    struct {
        jl_uint32 pu_amp:1;                                                 //[ 0: 0]
        jl_uint32 pu_sar:1;                                                 //[ 1: 1]
        jl_uint32 pu_rx:1;                                                  //[ 2: 2]
        jl_uint32 rsvd:1;                                                   //[ 3: 3]
        jl_uint32 pu_pi:1;                                                  //[ 4: 4]
        jl_uint32 pu_dac_dly:1;                                             //[ 5: 5]
        jl_uint32 pu_dac:1;                                                 //[ 6: 6]
        jl_uint32 pu_10m_clktree:1;                                         //[ 7: 7]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PU_t;

#define FEPHY0_RX_OFFSET                                                             ((jl_uint32)0x00000315U)
#define FEPHY0_RX_NUM                                                                ((jl_uint32)0x00000001U)
typedef union FEPHY0_RX_u {
    struct {
        jl_uint32 rx_vcm_sel:1;                                             //[ 0: 0]
        jl_uint32 rx_s2d_rdeg:2;                                            //[ 2: 1]
        jl_uint32 rx_rterm:1;                                               //[ 3: 3]
        jl_uint32 rx_mode_sel:1;                                            //[ 4: 4]
        jl_uint32 rx_lp_en:1;                                               //[ 5: 5]
        jl_uint32 rx_echo_en:1;                                             //[ 6: 6]
        jl_uint32 rx_csel:4;                                                //[10: 7]
        jl_uint32 rx_cp_start:1;                                            //[11:11]
        jl_uint32 rx_boost_en:1;                                            //[12:12]
        jl_uint32 rx_bm_cp:1;                                               //[13:13]
    } bf;
    jl_uint32 val[1];
} FEPHY0_RX_t;

#define FEPHY0_SAR_OFFSET                                                            ((jl_uint32)0x00000316U)
#define FEPHY0_SAR_NUM                                                               ((jl_uint32)0x00000001U)
typedef union FEPHY0_SAR_u {
    struct {
        jl_uint32 sar_rstn:1;                                               //[ 0: 0]
        jl_uint32 sar_reverse:1;                                            //[ 1: 1]
        jl_uint32 sar_isel:2;                                               //[ 3: 2]
        jl_uint32 sar_delay:1;                                              //[ 4: 4]
        jl_uint32 sar_cksel_mode:1;                                         //[ 5: 5]
    } bf;
    jl_uint32 val[1];
} FEPHY0_SAR_t;

#define FEPHY0_RX2_OFFSET                                                            ((jl_uint32)0x00000317U)
#define FEPHY0_RX2_NUM                                                               ((jl_uint32)0x00000001U)
typedef union FEPHY0_RX2_u {
    struct {
        jl_uint32 rx_rsel:8;                                                //[ 7: 0]
        jl_uint32 rx_rsvd:3;                                                //[10: 8]
    } bf;
    jl_uint32 val[1];
} FEPHY0_RX2_t;

#define FEPHY0_ANAMISC_OFFSET                                                        ((jl_uint32)0x00000318U)
#define FEPHY0_ANAMISC_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_ANAMISC_u {
    struct {
        jl_uint32 tx_enb_1p8v_ldo_slave:1;                                  //[ 0: 0]
        jl_uint32 rsvd:2;                                                   //[ 2: 1]
        jl_uint32 sar_reg_prech_hv:1;                                       //[ 3: 3]
        jl_uint32 sar_reg_1v_en:1;                                          //[ 4: 4]
        jl_uint32 sar_avdd18v_sel:1;                                        //[ 5: 5]
        jl_uint32 rsvd1:1;                                                   //[ 6: 6]
        jl_uint32 rx_reg18_sel:1;                                           //[ 7: 7]
        jl_uint32 rx_reg10_sel:1;                                           //[ 8: 8]
        jl_uint32 rx_reg_prech:1;                                           //[ 9: 9]
        jl_uint32 rx_ldo18_slave_en:1;                                      //[10:10]
        jl_uint32 rx_ldo10_slave_en:1;                                      //[11:11]
    } bf;
    jl_uint32 val[1];
} FEPHY0_ANAMISC_t;

#define FEPHY0_RXDSPACA_OFFSET                                                       ((jl_uint32)0x00001010U)
#define FEPHY0_RXDSPACA_NUM                                                          ((jl_uint32)0x00000001U)
typedef union FEPHY0_RXDSPACA_u {
    struct {
        jl_uint32 dsp100t_ctrl:16;                                          //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_RXDSPACA_t;

#define FEPHY0_RXDSPAR_OFFSET                                                        ((jl_uint32)0x00001011U)
#define FEPHY0_RXDSPAR_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_RXDSPAR_u {
    struct {
        jl_uint32 dsp100t_rd:16;                                            //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_RXDSPAR_t;

#define FEPHY0_RXDSPAW_OFFSET                                                        ((jl_uint32)0x00001012U)
#define FEPHY0_RXDSPAW_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_RXDSPAW_u {
    struct {
        jl_uint32 dsp100t_wd:16;                                            //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_RXDSPAW_t;

#define FEPHY0_ANRXLCW_OFFSET                                                        ((jl_uint32)0x00001014U)
#define FEPHY0_ANRXLCW_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_ANRXLCW_u {
    struct {
        jl_uint32 an_rx_lcw_0:16;                                           //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_ANRXLCW_t;

#define FEPHY0_ANTXLCW_OFFSET                                                        ((jl_uint32)0x00001015U)
#define FEPHY0_ANTXLCW_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_ANTXLCW_u {
    struct {
        jl_uint32 an_tx_lcw_0:16;                                           //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_ANTXLCW_t;

#define FEPHY0_ANS1_OFFSET                                                           ((jl_uint32)0x00001016U)
#define FEPHY0_ANS1_NUM                                                              ((jl_uint32)0x00000001U)
typedef union FEPHY0_ANS1_u {
    struct {
        jl_uint32 an_rx_bit_cnt:6;                                          //[ 5: 0]
        jl_uint32 an_rx_done:1;                                             //[ 6: 6]
        jl_uint32 an_flp_receive_idle:1;                                    //[ 7: 7]
        jl_uint32 an_nlp_link_status:2;                                     //[ 9: 8]
        jl_uint32 an_nlp_test_sigdet_src:1;                                 //[10:10]
        jl_uint32 an_nlp_t_pulse_done:1;                                    //[11:11]
        jl_uint32 an_nlp_t_pulse_pending:1;                                 //[12:12]
        jl_uint32 an_nlp_link_det_clr:1;                                    //[13:13]
        jl_uint32 an_nlp_link_det:1;                                        //[14:14]
        jl_uint32 an_ack_finished:1;                                        //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_ANS1_t;

#define FEPHY0_ANC0_OFFSET                                                           ((jl_uint32)0x00001017U)
#define FEPHY0_ANC0_NUM                                                              ((jl_uint32)0x00000001U)
typedef union FEPHY0_ANC0_u {
    struct {
        jl_uint32 an_rx_bit_cnt_chk:6;                                      //[ 5: 0]
        jl_uint32 rsvd:1;                                                   //[ 6: 6]
        jl_uint32 an_rx_en:1;                                               //[ 7: 7]
        jl_uint32 an_tx_ack_cnt_done:6;                                     //[13: 8]
        jl_uint32 rsvd1:1;                                                   //[14:14]
        jl_uint32 an_tx_en:1;                                               //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_ANC0_t;

#define FEPHY0_ANCANIRQC_OFFSET                                                      ((jl_uint32)0x00001018U)
#define FEPHY0_ANCANIRQC_NUM                                                         ((jl_uint32)0x00000001U)
typedef union FEPHY0_ANCANIRQC_u {
    struct {
        jl_uint32 an_tx_bit_cnt:6;                                          //[ 5: 0]
        jl_uint32 an_complete_ack:1;                                        //[ 6: 6]
        jl_uint32 an_transmit_ability:1;                                    //[ 7: 7]
        jl_uint32 rsvd:1;                                                   //[ 8: 8]
        jl_uint32 an_nlp_link_control:2;                                    //[10: 9]
        jl_uint32 rsvd1:2;                                                   //[12:11]
        jl_uint32 an_ack_finished_clr:1;                                    //[13:13]
        jl_uint32 an_rx_done_clr:1;                                         //[14:14]
        jl_uint32 an_flp_receive_idle_clr:1;                                //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_ANCANIRQC_t;

#define FEPHY0_TIMER_OFFSET                                                          ((jl_uint32)0x00001019U)
#define FEPHY0_TIMER_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_TIMER_u {
    struct {
        jl_uint32 an_timer0_match:4;                                        //[ 3: 0]
        jl_uint32 an_timer0_cnt:4;                                          //[ 7: 4]
        jl_uint32 an_timer0_clr:1;                                          //[ 8: 8]
        jl_uint32 an_timer0_en:1;                                           //[ 9: 9]
        jl_uint32 an_timer0_done:1;                                         //[10:10]
    } bf;
    jl_uint32 val[1];
} FEPHY0_TIMER_t;

#define FEPHY0_ANMISCCFG_OFFSET                                                      ((jl_uint32)0x0000101AU)
#define FEPHY0_ANMISCCFG_NUM                                                         ((jl_uint32)0x00000001U)
typedef union FEPHY0_ANMISCCFG_u {
    struct {
        jl_uint32 an_flp_cnt_done:6;                                        //[ 5: 0]
        jl_uint32 an_tx_pls_width:5;                                        //[10: 6]
    } bf;
    jl_uint32 val[1];
} FEPHY0_ANMISCCFG_t;

#define FEPHY0_LOADERGO_OFFSET                                                       ((jl_uint32)0x0000101BU)
#define FEPHY0_LOADERGO_NUM                                                          ((jl_uint32)0x00000001U)
typedef union FEPHY0_LOADERGO_u {
    struct {
        jl_uint32 loader_go:16;                                             //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_LOADERGO_t;

#define FEPHY0_LOADERDATA_OFFSET                                                     ((jl_uint32)0x0000101CU)
#define FEPHY0_LOADERDATA_NUM                                                        ((jl_uint32)0x00000001U)
typedef union FEPHY0_LOADERDATA_u {
    struct {
        jl_uint32 loader_data_0:16;                                         //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_LOADERDATA_t;

#define FEPHY0_PINMUXMODE_OFFSET                                                     ((jl_uint32)0x0000101DU)
#define FEPHY0_PINMUXMODE_NUM                                                        ((jl_uint32)0x00000001U)
typedef union FEPHY0_PINMUXMODE_u {
    struct {
        jl_uint32 rsvd:4;                                                   //[ 3: 0]
        jl_uint32 intn_mcu_val:1;                                           //[ 4: 4]
        jl_uint32 intn_mcu_force:1;                                         //[ 5: 5]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PINMUXMODE_t;

#define FEPHY0_DIGPU0_OFFSET                                                         ((jl_uint32)0x00001031U)
#define FEPHY0_DIGPU0_NUM                                                            ((jl_uint32)0x00000001U)
typedef union FEPHY0_DIGPU0_u {
    struct {
        jl_uint32 dac_out_sel:2;                                            //[ 1: 0]
        jl_uint32 rsvd:10;                                                  //[11: 2]
        jl_uint32 auto_polarity:1;                                          //[12:12]
        jl_uint32 rand:1;                                                   //[13:13]
        jl_uint32 nlp_disable:1;                                            //[14:14]
        jl_uint32 force_link:1;                                             //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DIGPU0_t;

#define FEPHY0_DIGPU1_OFFSET                                                         ((jl_uint32)0x00001032U)
#define FEPHY0_DIGPU1_NUM                                                            ((jl_uint32)0x00000001U)
typedef union FEPHY0_DIGPU1_u {
    struct {
        jl_uint32 clk_en_10t_rx_dsp:1;                                      //[ 0: 0]
        jl_uint32 clk_en_100x_pi:1;                                         //[ 1: 1]
        jl_uint32 clk_en_100x_rx:1;                                         //[ 2: 2]
        jl_uint32 clk_en_10t_tx_dsp:1;                                      //[ 3: 3]
        jl_uint32 clk_en_100x_tx:1;                                         //[ 4: 4]
        jl_uint32 clk_en_mcu:1;                                             //[ 5: 5]
        jl_uint32 clk_en_10t_rx_pcspma:1;                                   //[ 6: 6]
        jl_uint32 clk_en_10t_tx_pcspma:1;                                   //[ 7: 7]
        jl_uint32 rstn_ctrl_mcu:1;                                          //[ 8: 8]
        jl_uint32 rstn_ctrl_10t_rx_pcspma:1;                                //[ 9: 9]
        jl_uint32 rstn_ctrl_10t_rx_dsp:1;                                   //[10:10]
        jl_uint32 rstn_ctrl_100x_pi:1;                                      //[11:11]
        jl_uint32 rstn_ctrl_100x_rx:1;                                      //[12:12]
        jl_uint32 rstn_ctrl_10t_tx_pcspma:1;                                //[13:13]
        jl_uint32 rstn_ctrl_10t_tx_dsp:1;                                   //[14:14]
        jl_uint32 rstn_ctrl_100x_tx:1;                                      //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DIGPU1_t;

#define FEPHY0_PCSU0_OFFSET                                                          ((jl_uint32)0x00001033U)
#define FEPHY0_PCSU0_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_PCSU0_u {
    struct {
        jl_uint32 link_control_u:2;                                         //[ 1: 0]
        jl_uint32 sig_stat_src:1;                                           //[ 2: 2]
        jl_uint32 tx_pma_fiber_en:1;                                        //[ 3: 3]
        jl_uint32 rx_pma_fiber_en:1;                                        //[ 4: 4]
        jl_uint32 tx_pcs_eee_en:1;                                          //[ 5: 5]
        jl_uint32 rx_pcs_eee_en:1;                                          //[ 6: 6]
        jl_uint32 descrambler_locked:1;                                     //[ 7: 7]
        jl_uint32 descr_testmode:1;                                         //[ 8: 8]
        jl_uint32 descr_load_cfg:1;                                         //[ 9: 9]
        jl_uint32 descr_sdcd_ctrl:1;                                        //[10:10]
        jl_uint32 descr_sdcd_force:1;                                       //[11:11]
        jl_uint32 descr_rstn:1;                                             //[12:12]
        jl_uint32 descr_sdcd_rx_quiet:1;                                    //[13:13]
        jl_uint32 link_status_force:1;                                      //[14:14]
        jl_uint32 link_status_force_val:1;                                  //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PCSU0_t;

#define FEPHY0_PCSU1_OFFSET                                                          ((jl_uint32)0x00001034U)
#define FEPHY0_PCSU1_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_PCSU1_u {
    struct {
        jl_uint32 link_status_u:2;                                          //[ 1: 0]
        jl_uint32 pu_pi_force:1;                                            //[ 2: 2]
        jl_uint32 pu_pi_val:1;                                              //[ 3: 3]
        jl_uint32 link_monitor_period_sel:2;                                //[ 5: 4]
        jl_uint32 speed:1;                                                  //[ 6: 6]
        jl_uint32 duplex:1;                                                 //[ 7: 7]
        jl_uint32 rx_far_end_faulting:1;                                    //[ 8: 8]
        jl_uint32 rx_far_end_faulting_clr:1;                                //[ 9: 9]
        jl_uint32 rx_far_end_fault_detect_en:1;                             //[10:10]
        jl_uint32 tx_far_end_fault_gen_en:1;                                //[11:11]
        jl_uint32 link_mon_sig_stat_src:1;                                  //[12:12]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PCSU1_t;

#define FEPHY0_DSPI0_OFFSET                                                          ((jl_uint32)0x00001035U)
#define FEPHY0_DSPI0_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI0_u {
    struct {
        jl_uint32 dsp_rx_f1_sel:2;                                          //[ 1: 0]
        jl_uint32 dsp_tx_fir_sel:2;                                         //[ 3: 2]
        jl_uint32 dsp_rx_fg_polar:1;                                        //[ 4: 4]
        jl_uint32 dsp_rx_polar_sel:1;                                       //[ 5: 5]
        jl_uint32 dsp_rx_amp2:6;                                            //[11: 6]
        jl_uint32 dsp_rx_amp1:4;                                            //[15:12]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI0_t;

#define FEPHY0_PCS0_OFFSET                                                           ((jl_uint32)0x00001036U)
#define FEPHY0_PCS0_NUM                                                              ((jl_uint32)0x00000001U)
typedef union FEPHY0_PCS0_u {
    struct {
        jl_uint32 tpidl_width:4;                                            //[ 3: 0]
        jl_uint32 nlp_width:4;                                              //[ 7: 4]
        jl_uint32 sqe_test_enable:1;                                        //[ 8: 8]
        jl_uint32 jabber_enable:1;                                          //[ 9: 9]
        jl_uint32 crs_tx_enable:1;                                          //[10:10]
        jl_uint32 crs_rx_enable:1;                                          //[11:11]
        jl_uint32 lpbk_enable:1;                                            //[12:12]
        jl_uint32 force_loopback:1;                                         //[13:13]
        jl_uint32 tpidl_autowidth:1;                                        //[14:14]
        jl_uint32 link_mon_force_link_stat_ok:1;                            //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PCS0_t;

#define FEPHY0_PCS1_OFFSET                                                           ((jl_uint32)0x00001037U)
#define FEPHY0_PCS1_NUM                                                              ((jl_uint32)0x00000001U)
typedef union FEPHY0_PCS1_u {
    struct {
        jl_uint32 err_cnt_10m:6;                                            //[ 5: 0]
        jl_uint32 err_cnt_10m_clr:1;                                        //[ 6: 6]
        jl_uint32 rsvd:2;                                                   //[ 8: 7]
        jl_uint32 sig_det_thr_10m:4;                                        //[12: 9]
        jl_uint32 carrier_sense_rx_en:1;                                    //[13:13]
        jl_uint32 carrier_sense_tx_en:1;                                    //[14:14]
        jl_uint32 pmd_loopback_u:1;                                         //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PCS1_t;

#define FEPHY0_LED_OFFSET                                                            ((jl_uint32)0x00001038U)
#define FEPHY0_LED_NUM                                                               ((jl_uint32)0x00000001U)
typedef union FEPHY0_LED_u {
    struct {
        jl_uint32 pi_sync_mode:2;                                           //[ 1: 0]
        jl_uint32 pi_sync_init:8;                                           //[ 9: 2]
        jl_uint32 rsvd:1;                                                   //[10:10]
        jl_uint32 dsp_tx_u_amp:4;                                           //[14:11]
        jl_uint32 tx_fiber_scrambler_en:1;                                  //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_LED_t;

#define FEPHY0_DSPI1_OFFSET                                                          ((jl_uint32)0x0000103DU)
#define FEPHY0_DSPI1_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI1_u {
    struct {
        jl_uint32 dsp_rx_sig_cnt:6;                                         //[ 5: 0]
        jl_uint32 dsp_rx_prea_cnt:6;                                        //[11: 6]
        jl_uint32 dsp_rx_mu_sel:1;                                          //[12:12]
        jl_uint32 dsp_rx_f2_sel:2;                                          //[14:13]
        jl_uint32 dsp_rx_fir_en:1;                                          //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI1_t;

#define FEPHY0_DSPI2_OFFSET                                                          ((jl_uint32)0x0000103EU)
#define FEPHY0_DSPI2_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI2_u {
    struct {
        jl_uint32 dsp_rx_eye_err_cnt:4;                                     //[ 3: 0]
        jl_uint32 dsp_rx_thre_sel:2;                                        //[ 5: 4]
        jl_uint32 signal_status_u_latch_low:1;                              //[ 6: 6]
        jl_uint32 signal_status_u_latch_low_src:1;                          //[ 7: 7]
        jl_uint32 rx_pcs_idle_n_descr_lock:1;                               //[ 8: 8]
        jl_uint32 rsvd:5;                                                   //[13: 9]
        jl_uint32 rx_quiet:1;                                               //[14:14]
        jl_uint32 tx_quiet:1;                                               //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI2_t;

#define FEPHY0_EEE_OFFSET                                                            ((jl_uint32)0x00001050U)
#define FEPHY0_EEE_NUM                                                               ((jl_uint32)0x00000001U)
typedef union FEPHY0_EEE_u {
    struct {
        jl_uint32 dsp_u_rx_partial_freeze_force:1;                          //[ 0: 0]
        jl_uint32 dsp_u_rx_partial_freeze_force_val:1;                      //[ 1: 1]
        jl_uint32 dsp_u_rx_lpi_force:1;                                     //[ 2: 2]
        jl_uint32 dsp_u_rx_lpi_force_val:1;                                 //[ 3: 3]
        jl_uint32 dsp_u_rx_freeze:1;                                        //[ 4: 4]
        jl_uint32 tx_fef_sig_stat_force_val:1;                              //[ 5: 5]
        jl_uint32 tx_fef_sig_stat_force:1;                                  //[ 6: 6]
        jl_uint32 tx_clk_inv_100m:1;                                        //[ 7: 7]
        jl_uint32 tx_clk_phase_100m:3;                                      //[10: 8]
        jl_uint32 rx_clk_inv_100m:1;                                        //[11:11]
        jl_uint32 rx_clk_phase_100m:3;                                      //[14:12]
        jl_uint32 tx_fef_rx_rpi_en:1;                                       //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_EEE_t;

#define FEPHY0_PCS2_OFFSET                                                           ((jl_uint32)0x00001051U)
#define FEPHY0_PCS2_NUM                                                              ((jl_uint32)0x00000001U)
typedef union FEPHY0_PCS2_u {
    struct {
        jl_uint32 lc_max_10m:4;                                             //[ 3: 0]
        jl_uint32 fg_lp_cnt_thr_10m:4;                                      //[ 7: 4]
        jl_uint32 tx_clk_phase_10m:3;                                       //[10: 8]
        jl_uint32 dsp_rx_strategy_sel:1;                                    //[11:11]
        jl_uint32 rx_clk_phase_10m:3;                                       //[14:12]
        jl_uint32 col_enable:1;                                             //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_PCS2_t;

#define FEPHY0_MIIISOLATE_OFFSET                                                     ((jl_uint32)0x00001052U)
#define FEPHY0_MIIISOLATE_NUM                                                        ((jl_uint32)0x00000001U)
typedef union FEPHY0_MIIISOLATE_u {
    struct {
        jl_uint32 lpi_rx_tw_timer_cnt:6;                                    //[ 5: 0]
        jl_uint32 mii_crs_isolate:1;                                        //[ 6: 6]
        jl_uint32 mii_col_isolate:1;                                        //[ 7: 7]
        jl_uint32 mii_rx_isolate:1;                                         //[ 8: 8]
        jl_uint32 mii_tx_isolate:1;                                         //[ 9: 9]
        jl_uint32 mii_rx_clk_isolate:1;                                     //[10:10]
        jl_uint32 mii_tx_clk_isolate:1;                                     //[11:11]
        jl_uint32 dbg_out_sel:3;                                            //[14:12]
    } bf;
    jl_uint32 val[1];
} FEPHY0_MIIISOLATE_t;

#define FEPHY0_CPUPC_OFFSET                                                          ((jl_uint32)0x00001053U)
#define FEPHY0_CPUPC_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_CPUPC_u {
    struct {
        jl_uint32 cpu_enc_addr:16;                                          //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_CPUPC_t;

#define FEPHY0_DSPI3_OFFSET                                                          ((jl_uint32)0x00001054U)
#define FEPHY0_DSPI3_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI3_u {
    struct {
        jl_uint32 dsp_rx_adc_rd_init:6;                                     //[ 5: 0]
        jl_uint32 dsp_rx_fg_lp_cnt:5;                                       //[10: 6]
        jl_uint32 tx_clk_force_in:1;                                        //[11:11]
        jl_uint32 rsvd:1;                                                   //[12:12]
        jl_uint32 dsp_rx_overflow_flag:2;                                   //[14:13]
        jl_uint32 dsp_rx_overflow_clr:1;                                    //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI3_t;

#define FEPHY0_BCMRINT_OFFSET                                                        ((jl_uint32)0x00001055U)
#define FEPHY0_BCMRINT_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_BCMRINT_u {
    struct {
        jl_uint32 rsvd:9;                                                   //[ 8: 0]
        jl_uint32 linkstatuschg_set:1;                                      //[ 9: 9]
        jl_uint32 duplexchg_set:1;                                          //[10:10]
        jl_uint32 spdchg_set:1;                                             //[11:11]
        jl_uint32 anerr_set:1;                                              //[12:12]
        jl_uint32 autoneg_restart_clr:1;                                    //[13:13]
        jl_uint32 sw_rst_bmcr:1;                                            //[14:14]
        jl_uint32 sw_rst_clr:1;                                             //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_BCMRINT_t;

#define FEPHY0_RSVD1_OFFSET                                                          ((jl_uint32)0x00001056U)
#define FEPHY0_RSVD1_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_RSVD1_u {
    struct {
        jl_uint32 digital_rsvd0:16;                                         //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_RSVD1_t;

#define FEPHY0_BYPASS0_OFFSET                                                        ((jl_uint32)0x00001057U)
#define FEPHY0_BYPASS0_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_BYPASS0_u {
    struct {
        jl_uint32 sd_jabber_detect:1;                                       //[ 0: 0]
        jl_uint32 sd_link_status:1;                                         //[ 1: 1]
        jl_uint32 sd_an_ability:1;                                          //[ 2: 2]
        jl_uint32 sd_remote_fault:1;                                        //[ 3: 3]
        jl_uint32 sd_autoneg_complete:1;                                    //[ 4: 4]
        jl_uint32 sd_undir_en:1;                                            //[ 5: 5]
        jl_uint32 sd_speed_sel_lo:1;                                        //[ 6: 6]
        jl_uint32 sd_col_test:1;                                            //[ 7: 7]
        jl_uint32 sd_duplex_mode:1;                                         //[ 8: 8]
        jl_uint32 sd_autoneg_restart:1;                                     //[ 9: 9]
        jl_uint32 sd_isolate:1;                                             //[10:10]
        jl_uint32 sd_power_down:1;                                          //[11:11]
        jl_uint32 sd_autoneg_en:1;                                          //[12:12]
        jl_uint32 sd_speed_sel_hi:1;                                        //[13:13]
        jl_uint32 sd_loopback:1;                                            //[14:14]
        jl_uint32 sd_sw_reset:1;                                            //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_BYPASS0_t;

#define FEPHY0_BYPASS1_OFFSET                                                        ((jl_uint32)0x00001058U)
#define FEPHY0_BYPASS1_NUM                                                           ((jl_uint32)0x00000001U)
typedef union FEPHY0_BYPASS1_u {
    struct {
        jl_uint32 rsvd:2;                                                   //[ 1: 0]
        jl_uint32 sd_eee_100_cap:1;                                         //[ 2: 2]
        jl_uint32 sd_rx_quiet_en:1;                                         //[ 3: 3]
        jl_uint32 sd_tx_quiet_en:1;                                         //[ 4: 4]
        jl_uint32 sd_eee_nway_en:1;                                         //[ 5: 5]
        jl_uint32 rsvd1:1;                                                   //[ 6: 6]
        jl_uint32 sd_force_mdi:1;                                           //[ 7: 7]
        jl_uint32 sd_en_automdix:1;                                         //[ 8: 8]
        jl_uint32 sd_fxmode:1;                                              //[ 9: 9]
        jl_uint32 rsvd2:1;                                                   //[10:10]
        jl_uint32 sd_link_partner_auto_neg_ability:1;                       //[11:11]
        jl_uint32 sd_page_received:1;                                       //[12:12]
        jl_uint32 sd_local_next_page_ability:1;                             //[13:13]
        jl_uint32 sd_link_partner_next_page_ability:1;                      //[14:14]
        jl_uint32 sd_parallel_detection_fault:1;                            //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_BYPASS1_t;

#define FEPHY0_DSPI4_OFFSET                                                          ((jl_uint32)0x00001070U)
#define FEPHY0_DSPI4_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI4_u {
    struct {
        jl_uint32 dsp_rx_me_valid_thre:8;                                   //[ 7: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI4_t;

#define FEPHY0_DSPI5_OFFSET                                                          ((jl_uint32)0x00001071U)
#define FEPHY0_DSPI5_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI5_u {
    struct {
        jl_uint32 dsp_rx_adc_peak:7;                                        //[ 6: 0]
        jl_uint32 rsvd:2;                                                   //[ 8: 7]
        jl_uint32 dsp_rx_adc_sigdet_th:7;                                   //[15: 9]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI5_t;

#define FEPHY0_CFG0_OFFSET                                                           ((jl_uint32)0x00001072U)
#define FEPHY0_CFG0_NUM                                                              ((jl_uint32)0x00000001U)
typedef union FEPHY0_CFG0_u {
    struct {
        jl_uint32 energy_thre_lo:16;                                        //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_CFG0_t;

#define FEPHY0_CFG1_OFFSET                                                           ((jl_uint32)0x00001073U)
#define FEPHY0_CFG1_NUM                                                              ((jl_uint32)0x00000001U)
typedef union FEPHY0_CFG1_u {
    struct {
        jl_uint32 energy_thre_hi:4;                                         //[ 3: 0]
        jl_uint32 adc_in_offset:4;                                          //[ 7: 4]
        jl_uint32 rsvd:6;                                                   //[13: 8]
        jl_uint32 detect_tx:1;                                              //[14:14]
        jl_uint32 pd_detect_tx_en:1;                                        //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_CFG1_t;

#define FEPHY0_DSPU0_OFFSET                                                          ((jl_uint32)0x00001074U)
#define FEPHY0_DSPU0_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPU0_u {
    struct {
        jl_uint32 sigdet2_y_thre:7;                                         //[ 6: 0]
        jl_uint32 rsvd:1;                                                   //[ 7: 7]
        jl_uint32 sigdet2_c_thre:6;                                         //[13: 8]
        jl_uint32 sigdet_link_good_sel:2;                                   //[15:14]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPU0_t;

#define FEPHY0_DSPU1_OFFSET                                                          ((jl_uint32)0x00001075U)
#define FEPHY0_DSPU1_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPU1_u {
    struct {
        jl_uint32 dsp_tx_f1_sel:6;                                          //[ 5: 0]
        jl_uint32 dsp_tx_f2_sel:6;                                          //[11: 6]
        jl_uint32 dsp_rx_noise_thre:4;                                      //[15:12]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPU1_t;

#define FEPHY0_DSPI6_OFFSET                                                          ((jl_uint32)0x00001076U)
#define FEPHY0_DSPI6_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI6_u {
    struct {
        jl_uint32 dsp_tx_f3_sel:6;                                          //[ 5: 0]
        jl_uint32 dsp_rx_amp3:4;                                            //[ 9: 6]
        jl_uint32 dsp_rx_amp4:4;                                            //[13:10]
        jl_uint32 sigdet_sel:2;                                             //[15:14]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI6_t;

#define FEPHY0_DIGRSVD0_OFFSET                                                       ((jl_uint32)0x00001077U)
#define FEPHY0_DIGRSVD0_NUM                                                          ((jl_uint32)0x00000001U)
typedef union FEPHY0_DIGRSVD0_u {
    struct {
        jl_uint32 digital_rsvd1:16;                                         //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DIGRSVD0_t;

#define FEPHY0_DIGRSVD1_OFFSET                                                       ((jl_uint32)0x00001078U)
#define FEPHY0_DIGRSVD1_NUM                                                          ((jl_uint32)0x00000001U)
typedef union FEPHY0_DIGRSVD1_u {
    struct {
        jl_uint32 digital_rsvd2:16;                                         //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DIGRSVD1_t;

#define FEPHY0_DIGRSVD2_OFFSET                                                       ((jl_uint32)0x00001079U)
#define FEPHY0_DIGRSVD2_NUM                                                          ((jl_uint32)0x00000001U)
typedef union FEPHY0_DIGRSVD2_u {
    struct {
        jl_uint32 digital_rsvd3:16;                                         //[15: 0]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DIGRSVD2_t;

#define FEPHY0_DSPI7_OFFSET                                                          ((jl_uint32)0x0000107AU)
#define FEPHY0_DSPI7_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI7_u {
    struct {
        jl_uint32 dsp_rx_max_break:8;                                       //[ 7: 0]
        jl_uint32 dsp_rx_sig_thre:8;                                        //[15: 8]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI7_t;

#define FEPHY0_DSPI8_OFFSET                                                          ((jl_uint32)0x0000107BU)
#define FEPHY0_DSPI8_NUM                                                             ((jl_uint32)0x00000001U)
typedef union FEPHY0_DSPI8_u {
    struct {
        jl_uint32 dsp_rx_fifo_rd_val:5;                                     //[ 4: 0]
        jl_uint32 dsp_rx_is_diff_detect:1;                                  //[ 5: 5]
        jl_uint32 dsp_rx_amp_sig_thre:4;                                    //[ 9: 6]
        jl_uint32 rsvd:5;                                                   //[14:10]
        jl_uint32 dsp_rx_fifo_rd_en:1;                                      //[15:15]
    } bf;
    jl_uint32 val[1];
} FEPHY0_DSPI8_t;

#endif /* __JL_REG_FEPHY_H__ */

