//reg_mag.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_MAG_H__
#define __JL_REG_MAG_H__

#include <jl_types.h>
#include "jl51xx/jl51xx_drv_switch.h"

#define MAG_BASE                                                                     ((jl_uint32)0x00200A00U)
#define MAG_BLOCK_SIZE                                                               ((jl_uint32)0x00000100U)

#define MAG_INT_OFFSET                                                               ((jl_uint32)0x00000000U)
#define MAG_INT_NUM                                                                  ((jl_uint32)0x00000001U)
typedef union MAG_INT_u {
    struct {
        jl_uint32 mac_int:10;                                               //[ 9: 0]
    } bf;
    jl_uint32 val[1];
} MAG_INT_t;

#define VERSION_INFO_OFFSET                                                          ((jl_uint32)0x00000001U)
#define VERSION_INFO_NUM                                                             ((jl_uint32)0x00000001U)
typedef union VERSION_INFO_u {
    struct {
        jl_uint32 date:16;                                                  //[15: 0]
        jl_uint32 version:16;                                               //[31:16]
    } bf;
    jl_uint32 val[1];
} VERSION_INFO_t;

#define LOOP_DETECT_CONTROL_OFFSET                                                   ((jl_uint32)0x00000002U)
#define LOOP_DETECT_CONTROL_NUM                                                      ((jl_uint32)0x00000001U)
typedef union LOOP_DETECT_CONTROL_u {
    struct {
        jl_uint32 lp_detect_en:10;                                          //[ 9: 0]
        jl_uint32 rsvd:2;                                                   //[11:10]
        jl_uint32 lp_detect_chk:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} LOOP_DETECT_CONTROL_t;

#define LOOP_DETECT_STATUS_OFFSET                                                    ((jl_uint32)0x00000003U)
#define LOOP_DETECT_STATUS_NUM                                                       ((jl_uint32)0x00000001U)
typedef union LOOP_DETECT_STATUS_u {
    struct {
        jl_uint32 lp_detect:10;                                             //[ 9: 0]
    } bf;
    jl_uint32 val[1];
} LOOP_DETECT_STATUS_t;

#define LOOP_DETECT_HISTORY_OFFSET                                                   ((jl_uint32)0x00000004U)
#define LOOP_DETECT_HISTORY_NUM                                                      ((jl_uint32)0x00000001U)
typedef union LOOP_DETECT_HISTORY_u {
    struct {
        jl_uint32 lp_detect_0:1;                                            //[ 0: 0]
        jl_uint32 lp_detect_1:1;                                            //[ 1: 1]
        jl_uint32 lp_detect_2:1;                                            //[ 2: 2]
        jl_uint32 lp_detect_3:1;                                            //[ 3: 3]
        jl_uint32 lp_detect_4:1;                                            //[ 4: 4]
        jl_uint32 lp_detect_5:1;                                            //[ 5: 5]
        jl_uint32 lp_detect_6:1;                                            //[ 6: 6]
        jl_uint32 lp_detect_7:1;                                            //[ 7: 7]
        jl_uint32 lp_detect_8:1;                                            //[ 8: 8]
        jl_uint32 lp_detect_9:1;                                            //[ 9: 9]
    } bf;
    jl_uint32 val[1];
} LOOP_DETECT_HISTORY_t;

#endif /* __JL_REG_MAG_H__ */

