//reg_apb_top.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_APB_TOP_H__
#define __JL_REG_APB_TOP_H__

#include <jl_types.h>

#define APB_TOP_BASE                                                                 ((jl_uint32)0x00400000U)
#define APB_TOP_BLOCK_SIZE                                                           ((jl_uint32)0x00000100U)

#define LED_CFG_0_OFFSET                                                             ((jl_uint32)0x00000000U)
#define LED_CFG_0_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_0_u {
    struct {
        jl_uint32 cfg_led_disable:17;                                       //[16: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_0_t;

#define LED_CFG_1_OFFSET                                                             ((jl_uint32)0x00000001U)
#define LED_CFG_1_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_1_u {
    struct {
        jl_uint32 cfg_led_polarity:17;                                      //[16: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_1_t;

#define LED_CFG_2_OFFSET                                                             ((jl_uint32)0x00000002U)
#define LED_CFG_2_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_2_u {
    struct {
        jl_uint32 cfg_led_off_time:7;                                       //[ 6: 0]
        jl_uint32 cfg_led_on_time:7;                                        //[13: 7]
    } bf;
    jl_uint32 val[1];
} LED_CFG_2_t;

#define LED_CFG_3_OFFSET                                                             ((jl_uint32)0x00000003U)
#define LED_CFG_3_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_3_u {
    struct {
        jl_uint32 cfg_loop_off_time:7;                                      //[ 6: 0]
        jl_uint32 cfg_loop_on_time:7;                                       //[13: 7]
    } bf;
    jl_uint32 val[1];
} LED_CFG_3_t;

#define LED_CFG_4_OFFSET                                                             ((jl_uint32)0x00000004U)
#define LED_CFG_4_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_4_u {
    struct {
        jl_uint32 cfg_led0_src_mask0:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_4_t;

#define LED_CFG_5_OFFSET                                                             ((jl_uint32)0x00000005U)
#define LED_CFG_5_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_5_u {
    struct {
        jl_uint32 cfg_led0_src_mask1:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_5_t;

#define LED_CFG_6_OFFSET                                                             ((jl_uint32)0x00000006U)
#define LED_CFG_6_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_6_u {
    struct {
        jl_uint32 cfg_led0_src_mask2:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_6_t;

#define LED_CFG_7_OFFSET                                                             ((jl_uint32)0x00000007U)
#define LED_CFG_7_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_7_u {
    struct {
        jl_uint32 cfg_led0_src_mask3:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_7_t;

#define LED_CFG_8_OFFSET                                                             ((jl_uint32)0x00000008U)
#define LED_CFG_8_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_8_u {
    struct {
        jl_uint32 cfg_led0_src_mask4:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_8_t;

#define LED_CFG_9_OFFSET                                                             ((jl_uint32)0x00000009U)
#define LED_CFG_9_NUM                                                                ((jl_uint32)0x00000001U)
typedef union LED_CFG_9_u {
    struct {
        jl_uint32 cfg_led0_src_mask5:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_9_t;

#define LED_CFG_10_OFFSET                                                            ((jl_uint32)0x0000000AU)
#define LED_CFG_10_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_10_u {
    struct {
        jl_uint32 cfg_led0_src_mask6:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_10_t;

#define LED_CFG_11_OFFSET                                                            ((jl_uint32)0x0000000BU)
#define LED_CFG_11_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_11_u {
    struct {
        jl_uint32 cfg_led0_src_mask7:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_11_t;

#define LED_CFG_12_OFFSET                                                            ((jl_uint32)0x0000000CU)
#define LED_CFG_12_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_12_u {
    struct {
        jl_uint32 cfg_led1_src_mask0:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_12_t;

#define LED_CFG_13_OFFSET                                                            ((jl_uint32)0x0000000DU)
#define LED_CFG_13_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_13_u {
    struct {
        jl_uint32 cfg_led1_src_mask1:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_13_t;

#define LED_CFG_14_OFFSET                                                            ((jl_uint32)0x0000000EU)
#define LED_CFG_14_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_14_u {
    struct {
        jl_uint32 cfg_led1_src_mask2:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_14_t;

#define LED_CFG_15_OFFSET                                                            ((jl_uint32)0x0000000FU)
#define LED_CFG_15_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_15_u {
    struct {
        jl_uint32 cfg_led1_src_mask3:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_15_t;

#define LED_CFG_16_OFFSET                                                            ((jl_uint32)0x00000010U)
#define LED_CFG_16_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_16_u {
    struct {
        jl_uint32 cfg_led1_src_mask4:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_16_t;

#define LED_CFG_17_OFFSET                                                            ((jl_uint32)0x00000011U)
#define LED_CFG_17_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_17_u {
    struct {
        jl_uint32 cfg_led1_src_mask5:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_17_t;

#define LED_CFG_18_OFFSET                                                            ((jl_uint32)0x00000012U)
#define LED_CFG_18_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_18_u {
    struct {
        jl_uint32 cfg_led1_src_mask6:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_18_t;

#define LED_CFG_19_OFFSET                                                            ((jl_uint32)0x00000013U)
#define LED_CFG_19_NUM                                                               ((jl_uint32)0x00000001U)
typedef union LED_CFG_19_u {
    struct {
        jl_uint32 cfg_led1_src_mask7:9;                                     //[ 8: 0]
    } bf;
    jl_uint32 val[1];
} LED_CFG_19_t;

#define RF_TIMEOUT_OFFSET                                                            ((jl_uint32)0x00000014U)
#define RF_TIMEOUT_NUM                                                               ((jl_uint32)0x00000001U)
typedef union RF_TIMEOUT_u {
    struct {
        jl_uint32 rf_timeout:16;                                            //[15: 0]
    } bf;
    jl_uint32 val[1];
} RF_TIMEOUT_t;

#define SWC_DBG_OFFSET                                                               ((jl_uint32)0x00000015U)
#define SWC_DBG_NUM                                                                  ((jl_uint32)0x00000001U)
typedef union SWC_DBG_u {
    struct {
        jl_uint32 swc_debug:4;                                              //[ 3: 0]
    } bf;
    jl_uint32 val[1];
} SWC_DBG_t;

#define ADAPTER_EXPIRE_0_OFFSET                                                      ((jl_uint32)0x00000020U)
#define ADAPTER_EXPIRE_0_NUM                                                         ((jl_uint32)0x00000001U)
typedef union ADAPTER_EXPIRE_0_u {
    struct {
        jl_uint32 expire_p0:5;                                              //[ 4: 0]
        jl_uint32 trigger_p0:5;                                             //[ 9: 5]
        jl_uint32 clr_p0:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p0:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p0:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_EXPIRE_0_t;

#define ADAPTER_EXPIRE_1_OFFSET                                                      ((jl_uint32)0x00000021U)
#define ADAPTER_EXPIRE_1_NUM                                                         ((jl_uint32)0x00000001U)
typedef union ADAPTER_EXPIRE_1_u {
    struct {
        jl_uint32 expire_p1:5;                                              //[ 4: 0]
        jl_uint32 trigger_p1:5;                                             //[ 9: 5]
        jl_uint32 clr_p1:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p1:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p1:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_EXPIRE_1_t;

#define ADAPTER_EXPIRE_2_OFFSET                                                      ((jl_uint32)0x00000022U)
#define ADAPTER_EXPIRE_2_NUM                                                         ((jl_uint32)0x00000001U)
typedef union ADAPTER_EXPIRE_2_u {
    struct {
        jl_uint32 expire_p2:5;                                              //[ 4: 0]
        jl_uint32 trigger_p2:5;                                             //[ 9: 5]
        jl_uint32 clr_p2:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p2:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p2:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_EXPIRE_2_t;

#define ADAPTER_EXPIRE_3_OFFSET                                                      ((jl_uint32)0x00000023U)
#define ADAPTER_EXPIRE_3_NUM                                                         ((jl_uint32)0x00000001U)
typedef union ADAPTER_EXPIRE_3_u {
    struct {
        jl_uint32 expire_p3:5;                                              //[ 4: 0]
        jl_uint32 trigger_p3:5;                                             //[ 9: 5]
        jl_uint32 clr_p3:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p3:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p3:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_EXPIRE_3_t;

#define ADAPTER_TRIGGER_0_OFFSET                                                     ((jl_uint32)0x00000024U)
#define ADAPTER_TRIGGER_0_NUM                                                        ((jl_uint32)0x00000001U)
typedef union ADAPTER_TRIGGER_0_u {
    struct {
        jl_uint32 expire_p4:5;                                              //[ 4: 0]
        jl_uint32 trigger_p4:5;                                             //[ 9: 5]
        jl_uint32 clr_p4:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p4:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p4:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_TRIGGER_0_t;

#define ADAPTER_TRIGGER_1_OFFSET                                                     ((jl_uint32)0x00000025U)
#define ADAPTER_TRIGGER_1_NUM                                                        ((jl_uint32)0x00000001U)
typedef union ADAPTER_TRIGGER_1_u {
    struct {
        jl_uint32 expire_p5:5;                                              //[ 4: 0]
        jl_uint32 trigger_p5:5;                                             //[ 9: 5]
        jl_uint32 clr_p5:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p5:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p5:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_TRIGGER_1_t;

#define ADAPTER_TRIGGER_2_OFFSET                                                     ((jl_uint32)0x00000026U)
#define ADAPTER_TRIGGER_2_NUM                                                        ((jl_uint32)0x00000001U)
typedef union ADAPTER_TRIGGER_2_u {
    struct {
        jl_uint32 expire_p6:5;                                              //[ 4: 0]
        jl_uint32 trigger_p6:5;                                             //[ 9: 5]
        jl_uint32 clr_p6:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p6:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p6:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_TRIGGER_2_t;

#define ADAPTER_TRIGGER_3_OFFSET                                                     ((jl_uint32)0x00000027U)
#define ADAPTER_TRIGGER_3_NUM                                                        ((jl_uint32)0x00000001U)
typedef union ADAPTER_TRIGGER_3_u {
    struct {
        jl_uint32 expire_p7:5;                                              //[ 4: 0]
        jl_uint32 trigger_p7:5;                                             //[ 9: 5]
        jl_uint32 clr_p7:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p7:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p7:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_TRIGGER_3_t;

#define ADAPTER_CLR_OFFSET                                                           ((jl_uint32)0x00000028U)
#define ADAPTER_CLR_NUM                                                              ((jl_uint32)0x00000001U)
typedef union ADAPTER_CLR_u {
    struct {
        jl_uint32 expire_p8:5;                                              //[ 4: 0]
        jl_uint32 trigger_p8:5;                                             //[ 9: 5]
        jl_uint32 clr_p8:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p8:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p8:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_CLR_t;

#define ADAPTER_CFG_9_OFFSET                                                         ((jl_uint32)0x00000029U)
#define ADAPTER_CFG_9_NUM                                                            ((jl_uint32)0x00000001U)
typedef union ADAPTER_CFG_9_u {
    struct {
        jl_uint32 expire_p9:5;                                              //[ 4: 0]
        jl_uint32 trigger_p9:5;                                             //[ 9: 5]
        jl_uint32 clr_p9:1;                                                 //[10:10]
        jl_uint32 rx_dout_en_p9:1;                                          //[11:11]
        jl_uint32 tx_dout_en_p9:1;                                          //[12:12]
    } bf;
    jl_uint32 val[1];
} ADAPTER_CFG_9_t;

#define ADAPTER_QUEUE_TX_CFG_0_OFFSET                                                ((jl_uint32)0x0000002AU)
#define ADAPTER_QUEUE_TX_CFG_0_NUM                                                   ((jl_uint32)0x00000001U)
typedef union ADAPTER_QUEUE_TX_CFG_0_u {
    struct {
        jl_uint32 tx_aremptymask:8;                                         //[ 7: 0]
        jl_uint32 tx_awfullmask:8;                                          //[15: 8]
    } bf;
    jl_uint32 val[1];
} ADAPTER_QUEUE_TX_CFG_0_t;

#define ADAPTER_QUEUE_TX_CFG_1_OFFSET                                                ((jl_uint32)0x0000002BU)
#define ADAPTER_QUEUE_TX_CFG_1_NUM                                                   ((jl_uint32)0x00000001U)
typedef union ADAPTER_QUEUE_TX_CFG_1_u {
    struct {
        jl_uint32 tx_rthr:5;                                                //[ 4: 0]
        jl_uint32 tx_wthr:5;                                                //[ 9: 5]
        jl_uint32 tx_rctrl_mode:1;                                          //[10:10]
        jl_uint32 tx_wctrl_mode:1;                                          //[11:11]
    } bf;
    jl_uint32 val[1];
} ADAPTER_QUEUE_TX_CFG_1_t;

#define ADAPTER_QUEUE_RX_CFG_0_OFFSET                                                ((jl_uint32)0x0000002CU)
#define ADAPTER_QUEUE_RX_CFG_0_NUM                                                   ((jl_uint32)0x00000001U)
typedef union ADAPTER_QUEUE_RX_CFG_0_u {
    struct {
        jl_uint32 rx_aremptymask:8;                                         //[ 7: 0]
        jl_uint32 rx_awfullmask:8;                                          //[15: 8]
    } bf;
    jl_uint32 val[1];
} ADAPTER_QUEUE_RX_CFG_0_t;

#define ADAPTER_QUEUE_RX_CFG_1_OFFSET                                                ((jl_uint32)0x0000002DU)
#define ADAPTER_QUEUE_RX_CFG_1_NUM                                                   ((jl_uint32)0x00000001U)
typedef union ADAPTER_QUEUE_RX_CFG_1_u {
    struct {
        jl_uint32 rx_rthr:5;                                                //[ 4: 0]
        jl_uint32 rx_wthr:5;                                                //[ 9: 5]
        jl_uint32 rx_rctrl_mode:1;                                          //[10:10]
        jl_uint32 rx_wctrl_mode:1;                                          //[11:11]
    } bf;
    jl_uint32 val[1];
} ADAPTER_QUEUE_RX_CFG_1_t;

#define ADAPTERS_AFIFO_STATUS_OFFSET                                                 ((jl_uint32)0x0000002EU)
#define ADAPTERS_AFIFO_STATUS_NUM                                                    ((jl_uint32)0x00000001U)
typedef union ADAPTERS_AFIFO_STATUS_u {
    struct {
        jl_uint32 rx_afifo_empty:1;                                         //[ 0: 0]
        jl_uint32 rx_afifo_full:1;                                          //[ 1: 1]
        jl_uint32 tx_afifo_empty:1;                                         //[ 2: 2]
        jl_uint32 tx_afifo_full:1;                                          //[ 3: 3]
        jl_uint32 afifo_select:4;                                           //[ 7: 4]
        jl_uint32 afifo_state_clr:1;                                        //[ 8: 8]
    } bf;
    jl_uint32 val[1];
} ADAPTERS_AFIFO_STATUS_t;

#define P8_P9_AFIFO_RX_VALID_OFFSET                                                  ((jl_uint32)0x0000002FU)
#define P8_P9_AFIFO_RX_VALID_NUM                                                     ((jl_uint32)0x00000001U)
typedef union P8_P9_AFIFO_RX_VALID_u {
    struct {
        jl_uint32 p8_valid_out_en:1;                                        //[ 0: 0]
        jl_uint32 p9_valid_out_en:1;                                        //[ 1: 1]
    } bf;
    jl_uint32 val[1];
} P8_P9_AFIFO_RX_VALID_t;

#define ADAPTERS_AFIFO_CRS_COL_WIDEN_OFFSET                                          ((jl_uint32)0x00000030U)
#define ADAPTERS_AFIFO_CRS_COL_WIDEN_NUM                                             ((jl_uint32)0x00000001U)
typedef union ADAPTERS_AFIFO_CRS_COL_WIDEN_u {
    struct {
        jl_uint32 crs_widen_select_p0:2;                                    //[ 1: 0]
        jl_uint32 crs_widen_select_p1:2;                                    //[ 3: 2]
        jl_uint32 crs_widen_select_p2:2;                                    //[ 5: 4]
        jl_uint32 crs_widen_select_p3:2;                                    //[ 7: 6]
        jl_uint32 crs_widen_select_p4:2;                                    //[ 9: 8]
        jl_uint32 crs_widen_select_p5:2;                                    //[11:10]
        jl_uint32 crs_widen_select_p6:2;                                    //[13:12]
        jl_uint32 crs_widen_select_p7:2;                                    //[15:14]
        jl_uint32 crs_widen_select_p8:2;                                    //[17:16]
        jl_uint32 crs_widen_select_p9:2;                                    //[19:18]
    } bf;
    jl_uint32 val[1];
} ADAPTERS_AFIFO_CRS_COL_WIDEN_t;

#define ADAPTERS_AFIFO_COL_WIDEN_OFFSET                                              ((jl_uint32)0x00000031U)
#define ADAPTERS_AFIFO_COL_WIDEN_NUM                                                 ((jl_uint32)0x00000001U)
typedef union ADAPTERS_AFIFO_COL_WIDEN_u {
    struct {
        jl_uint32 col_widen_select_p0:2;                                    //[ 1: 0]
        jl_uint32 col_widen_select_p1:2;                                    //[ 3: 2]
        jl_uint32 col_widen_select_p2:2;                                    //[ 5: 4]
        jl_uint32 col_widen_select_p3:2;                                    //[ 7: 6]
        jl_uint32 col_widen_select_p4:2;                                    //[ 9: 8]
        jl_uint32 col_widen_select_p5:2;                                    //[11:10]
        jl_uint32 col_widen_select_p6:2;                                    //[13:12]
        jl_uint32 col_widen_select_p7:2;                                    //[15:14]
        jl_uint32 col_widen_select_p8:2;                                    //[17:16]
        jl_uint32 col_widen_select_p9:2;                                    //[19:18]
    } bf;
    jl_uint32 val[1];
} ADAPTERS_AFIFO_COL_WIDEN_t;

#endif /* __JL_REG_APB_TOP_H__ */

