#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2012 OpenWrt.org

START=99

USE_PROCD=1
PROG=/bin/auto_adapt.sh

start_service() {
	adapt_en=`uci -q get network.lan.port_adaptive`
	if [ "x$adapt_en" == "x1" ]; then
		/bin/auto_adapt.sh start
	fi
}
