#
# Copyright (c) 2016 siflower, Inc
# Written by neil zhang <neil@siflower.com.cn>
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-$(CONFIG_SFAX8_PINCTRL) += pinctrl_sfax8.o
obj-$(CONFIG_SFA28_PINCTRL) += pinctrl_sfa28.o
