CONFIG_SF16A18_FACTORY_READ_SYSFS_DEBUG=y
ccflags-$(CONFIG_SF16A18_FACTORY_READ_SYSFS_DEBUG) += -DCONFIG_SF16A18_FACTORY_READ_SYSFS_DEBUG

obj-$(CONFIG_SFAX8_FACTORY_READ) += sfax8_factory_read.o

sfax8_factory_read-y += sf_factory_read_sysfs.o
sfax8_factory_read-y += sf_factory_read_entry.o
